### ISSUE TITLE
comments inside sql

### ISSUE THREAD

**Issue by imudal** [StackExchange/Dapper#1005]
I have a big multiresult sql, for each diferent Select I have an explanation **line commented out**. Also some of the calculated fields are also explained with comments. When I try to execute this with QueryMultiple, all EOLs are removed, which leads to the whole SQL being commented out.

**Is there a way to tell Dapper not to format the string?**

-- Dati del contatto (persone fisiche e giuridiche) 
SELECT [CodCliente]
      ,RTRIM(LTRIM([Denominazione])) 'Denominazione' -- explanation here
      ,[Persona]
FROM [dbo].[Contatti] WITH(NOLOCK)

--ALIAS (CODICE SIGEA)
SELECT [CodCliCompagnia]
  FROM [Alias] WITH(NOLOCK)
 WHERE [Alias].[IDCompagnia] = @IDCompagnia
   AND [Alias].[IDAgenzia] = @IDAgenzia
   AND [Alias].[Azienda] = @Azienda
   AND [Alias].[CodCliente] = @CodCliente 
ORDER BY [Progressivo] ASC

**Comment by mgravell** [comment]
That's *very* odd an unexpected; I'm not aware of any EOL removal! If that's happening, that would definitely be a bug. Are you *absolutely sure* that the EOL removal isn't in the calling code? (sorry if that seems a silly question)

**Comment by mgravell** [comment]
Here's my minimal test; it doesn't show the issue:

```
using Dapper;
using System;
using System.Data.SqlClient;
using System.Linq;

class P
{

    static void Main()
    {
        using (var conn = new SqlConnection("Server=.;Database=master;Trusted_Connection=Yes;"))
        {
            using (var multi = conn.QueryMultiple(@"select 123, --test
                      'abc'; select -- test
                      'def' /* test */ select 456;"))
            {
                var (a,b) = multi.ReadSingle<(int, string)>();
                var c = multi.Read<string>().Single();
                var d = multi.Read<int>().ToList()[0];
                Console.WriteLine(a);
                Console.WriteLine(b);
                Console.WriteLine(c);
                Console.WriteLine(d);
            }
        }
    }
}
```

Output:

```
123
abc
def
456
```

Do you have a minimal repro that shows the issue?

**Comment by mgravell** [comment]
Is there any chance your code is more like:

    conn.QuerySomething(
        "select * " +
        "from SomeTable -- the source " +
        "where Id = @id", args).ToList();

?

This looks similar but is very different, and would have the symptom you describe.

**Comment by NickCraver** [comment]
Going to close this one out barring any new information - Dapper indeed does no line ending stripping itself. Modifying queries like this would be dangerous.
