### ISSUE TITLE
double quotes problem with postgresql

### ISSUE THREAD

**Issue by lbx1979** [StackExchange/Dapper#1008]
Dapper.Contrib Insert mothed will generate sql with double quotes, but the entity property is defined with Pasical Case, so the database throw exception with "not exist column colname". Can we use a parameter control the generate sql without double quotes?

**Comment by NickCraver** [comment]
This would happen in #722 - we can't change the behavior without breaking half the userbase one way or another...and when you think about how that deploy works, realistically we're only *breaking working code* with a change.

However, supporting control of this: yes, it's needed. That's what #722 is about - you should see plans there for what you're after :)
