### ISSUE TITLE
Any Way to Ignore A Field or Colume from sql not in C# Entity's Property

### ISSUE THREAD

**Issue by sgf** [StackExchange/Dapper#1009]
he all,does dapper support to ignore some fields or columes from sql result.
when need this feature:

> some times,u cant modify the lots of Entitys
> (such as some field is deprecated or other scenes)
> 
> and u want to return  TableName.* because the table has more than 200-300 fields(Columes)
> But The majority is required and excluded are just a few.

so any way to do that when Read<T> the  Entitys.

**Comment by sgf** [comment]
@mgravell  yes,body,thats my mean. its give me an Exception now.

**Comment by mgravell** [comment]
Please can you be specific? What exception is it giving? What is the exact scenario? The only thing I can think of that would cause an *exception* here is if you have a property with the same name as a column but with a completely incompatible data type. Is that what you mean? Or is it something else? A minimal example would be great.

**Comment by sgf** [comment]
ok it Seems to have Done? I'm not quite sure。
i cant  do that even at last week.im not sure why its OK Now.

**Comment by mgravell** [comment]
The only property that should work differently for the <T1,T2,T3> case is
"Id", simply because "Id" is the default value of "splitOn", which is the
column/property used to split the data horizontally. If your tables don't
have an "Id", you can supply the correct "splitOn" separately via the
parameter.

**Comment by sgf** [comment]
@mgravell thank you reply,
but i think if Dapper could be auto ignore or accept parameter to ignore is better.

**Comment by mgravell** [comment]
If the problem is, as I suspect, the "splitBy" : it cannot ignore that.
That is a fundamental requirement for that method - it is how it gets
partitioned horizontally. As I say, a minimal example would go a very long
way here.

**Comment by mgravell** [comment]
That isn't going to help me repro it. Do you have a minimal example with enough for me to actually repro it? I don't have your types and I don't know what your sproc returns, so I can't do much with that's sorry.

**Comment by mgravell** [comment]
No problem. Glad it is sorted.
