### ISSUE TITLE
.net core not support TransactionScope ?

### ISSUE THREAD

**Issue by huanent** [StackExchange/Dapper#1021]
I use EFCore2.1RC and dapper on a TransactionScope

```
            using (var scope = new TransactionScope())
            {
                //EF insert
                _demoRepository.AddAsync(new DemoModel { Name = "赵六" });

                //dapper query
                var records = _demoRepository.GetTopRecords(10);

                scope.Complete();
            }
```

**exception**

{
  "ClassName": "System.PlatformNotSupportedException",
  "Message": "This platform does not support distributed transactions.",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": "   at System.Transactions.Distributed.DistributedTransactionManager.GetDistributedTransactionFromTransmitterPropagationToken(Byte[] propagationToken)\r\n   at System.Transactions.TransactionInterop.GetDistributedTransactionFromTransmitterPropagationToken(Byte[] propagationToken)\r\n   at System.Transactions.TransactionStatePSPEOperation.PSPEPromote(InternalTransaction tx)\r\n   at System.Transactions.TransactionStateDelegatedBase.EnterState(InternalTransaction tx)\r\n   at System.Transactions.EnlistableStates.Promote(InternalTransaction tx)\r\n   at System.Transactions.Transaction.Promote()\r\n   at System.Transactions.TransactionInterop.ConvertToDistributedTransaction(Transaction transaction)\r\n   at System.Transactions.TransactionInterop.GetExportCookie(Transaction transaction, Byte[] whereabouts)\r\n   at System.Data.SqlClient.SqlInternalConnection.GetTransactionCookie(Transaction transaction, Byte[] whereAbouts)\r\n   at System.Data.SqlClient.SqlInternalConnection.EnlistNonNull(Transaction tx)\r\n   at System.Data.SqlClient.SqlInternalConnection.Enlist(Transaction tx)\r\n   at System.Data.SqlClient.SqlInternalConnectionTds.Activate(Transaction transaction)\r\n   at System.Data.ProviderBase.DbConnectionPool.PrepareConnection(DbConnection owningObject, DbConnectionInternal obj, Transaction transaction)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Infrastructure.Repositories.DemoRepository.GetTopRecords(Int32 count) in C:\\Users\\huanent\\source\\repos\\AspNetCoreQuickStart\\src\\Infrastructure\\Repositories\\DemoRepository.cs:line 85\r\n   at Web.Controllers.DemoController.RunTransaction() in C:\\Users\\huanent\\source\\repos\\AspNetCoreQuickStart\\src\\Web\\Controllers\\DemoController.cs:line 171\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.<>c__DisplayClass33_0.<WrapVoidMethod>b__0(Object target, Object[] parameters)\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.VoidResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": null,
  "HResult": -2146233031,
  "Source": "System.Transactions.Local",
  "WatsonBuckets": null
}

**Comment by mgravell** [comment]
A: there's a difference between transaction scope and distributed
transactions; not all uses of transaction scope involve distributed
transactions, so .NET Core might support one but not the other

B: this isn't really Dapper's area. Dapper just simplifies ADO.NET; if a
particular ADO.NET provider doesn't support a specific feature on .NET
Core, that's really a question for whoever owns that ADO.NET provider

**Comment by huanent** [comment]
Got it thinks!
