### ISSUE TITLE
Update System.Data.SqlClient to 4.5 version

### ISSUE THREAD

**Issue by whitebear-gh** [StackExchange/Dapper#1026]
Hello, 

There is an important fix released in `System.Data.SqlClient` in version `4.5` as described here: 
https://github.com/dotnet/corefx/issues/24282 
Could you please update package dependency to the current version? 

Regards
wb

**Comment by mgravell** [comment]
In theory... "Fine I guess"? Note: closing this means it is likely to
disappear off of our radar.

**Comment by whitebear-gh** [comment]
Sorry, I have closed it somehow by mistake I guess, It's still on the table.

**Comment by NickCraver** [comment]
@whitebear-gh Just trying to understand the motivation here: what's the reason for Dapper to *force* the upgrade? You are absolutely fine to directly use 4.5 in your `<PackageReference>` alongside Dapper and it'll use the newer version, while not forcing everyone else to upgrade.

Note that at this time, `System.Data.SqlClient` 4.5.0 is not stable, so we cannot depend on it. But as said above, you're perfectly fine to begin using it!

**Comment by SeanFeldman** [comment]
I've ran into this issue as well. For someone who's using Dapper directly and is not aware that a transient dependency `System.Data.SqlClient`, versions earlier than 4.5.0,  will not work with `TransactionScope` is not trivial to figure out.

**Comment by NickCraver** [comment]
We did this, but also removed the reference later on, because of the migration to `Microsoft.Data.SqlClient`, so Dapper now relies on neither and is agnostic. Closing out to tidy up!

**Comment by whitebear-gh** [comment]
I missed your previous message, but thanks for your help Nick!
