### ISSUE TITLE
Will Tiered-Compilation improve the performance of dynamic methods (emit)?

### ISSUE THREAD

**Issue by NMSAzulX** [StackExchange/Dapper#1029]

**Comment by NMSAzulX** [comment]
Anyone here?

**Comment by mgravell** [comment]
What exactly do you mean? Short version right now: no, there is nothing that would change there. There are some possible options to move some things to build time, but that adds complexity - so isn't an obvious next step.

**Comment by NMSAzulX** [comment]
我是想说，分层编译会对Emit生成的方法进行优化吗？Emit生成的方法会达到原生代码的性能吗？
I just want to ask if the method created by emit will be improved the perfomance by using the tiered compliation in core2.1?   I can't speak English. I hope this does not disturb your patience.

**Comment by NMSAzulX** [comment]
Does the Tiered Compliation have positive affect on the methods generated by the Emit? Will the method generated by the Emit work as well as the natived / runtime codes?

**Comment by mgravell** [comment]
Now I understand. Short version: I don't know. It is entirely up to the
runtime / JIT, and any answer I give may be both incomplete and may change
in the future. I would **imagine** that runtime generated UK would be
eligible for this feature, but I don't know. However, when you're dealing
with database latency, this isn't going to be the limiting factor.

**Comment by NMSAzulX** [comment]
Thanks a lot~

**Comment by mgravell** [comment]
Odd typo: my phone auto-corrected IL to UK. I meant runtime generated IL!
