### ISSUE TITLE
Error parsing column 4 (IsLock=0 - SByte)”

### ISSUE THREAD

**Issue by gorden1991** [StackExchange/Dapper#1035]
Error parsing column 4 (IsLock=0 - SByte)”
provider:mysql 
field type:tinyint(1)
c# type:int?
What should i do ?

**Comment by NickCraver** [comment]
Can you please provide a minimal repro here (at least the raw code)? And which MySQL provider are you using?

**Comment by bgrainger** [comment]
By default, MySQL ADO.NET providers will map `TINYINT(1)` to `bool` in C#. If you don't want this to happen, try one of the following:

* change the column type to `TINYINT`
* add `TreatTinyAsBoolean=false` to your connection string

**Comment by tutlane** [comment]
Thanks, for me adding TreatTinyAsBoolean=false to connection string fixed issue.

Regards
[Tutlane.com](https://www.tutlane.com/tutorials)

**Comment by NickCraver** [comment]
Closing out to cleanup!
