### ISSUE TITLE
Does dapper support multi entities parameterization?

### ISSUE THREAD

**Issue by NMSAzulX** [StackExchange/Dapper#1037]
For example:
In this case:

entityA.aid = 1;
entityB.bid = 2;
sql="Insert into Table (aid,bid) values (@aid,@bid)";

dbconenction.Execute(sql, entityA, entityB);

entityA.aid->@aid
entityB.bid->@bid

**Comment by NickCraver** [comment]
You can either use `DynamicParameters`, (if it needs to by dynamic), or create an intermediate object here, like this:
```c#
entityA.aid = 1;
entityB.bid = 2;
var sql = "Insert into Table (aid,bid) values (@aid,@bid)";
dbconenction.Execute(sql, new { entityA.aid, entityB.bid });
```

**Comment by NMSAzulX** [comment]
Tks, DynamicParameters.
