### ISSUE TITLE
I'm so excited about the solution in this issue. 

### ISSUE THREAD

**Issue by NMSAzulX** [StackExchange/Dapper#1043]
This is my issue. Come in and discuss it? 

[https://github.com/dotnet/roslyn/issues/27783](https://github.com/dotnet/roslyn/issues/27783)

**Comment by mgravell** [comment]
Does this relate in any way to Dapper? I don't see it. Not sure if I'm being slow, or...

**Comment by NMSAzulX** [comment]
Well, do you think we can make some improvement on the Dapper in future?  C# Scripte Instead of Emit?

**Comment by NMSAzulX** [comment]
Maybe I always like to ask some strange questions. :)

**Comment by mgravell** [comment]
But why? If you're talking about runtime generation: Emit works, is faster and more direct, etc. Build time generation is something I have been considering for unrelated scenarios, but that is completely unrelated to that discussion. So again: why? What problem are you trying to solve?

**Comment by NMSAzulX** [comment]
I think we are not on the same page. Stop it.

**Comment by mgravell** [comment]
> Stop it.

I was merely trying to understand an issue that you logged, so we could understand how it relates to this project. But fine; it is closed now.
