### ISSUE TITLE
SqlBuilder RawSql Is Not available

### ISSUE THREAD

**Issue by thedonmon** [StackExchange/Dapper#1064]
Hello, hoping this is a quick one but I seem very confused on how to use SQLBuilder properly. 
           var builder = new SqlBuilder();
           
            builder.AddTemplate("Select /**select**/ from [Orders] O /**where**/ ");
            builder.Select("O.OrderId")
                    .Join("dbo.Contacts UC ON UC.UserContactId = O.UserContactId")
                    .Join("dbo.OrderItems OMT ON OMT.OrderId = O.OrderId")
                    .Join("dbo.OrderInformation OI ON OI.OrderId = O.OrderId")
                    .LeftJoin("dbo.Log L ON L.OrderId = O.OrderId");
            builder.Where("O.UserId = {0}", request.UserId);
            builder.Where("O.InsertDate > {0}", LookBackDate);

When I try and pass it to the dapper query like so:

`conn.Query<int>(builder) `

it does not accept it for obvious reasons but I cant seem to get the raw SQL out of this builder. I tried builder.RawSql but that seems to only be a getter for the `Template` class. `builder.ToString();` returns `Dapper.SqlBuilder`
Am I using the builder wrong?

**Comment by PublicWC** [comment]
In short,
```csharp
var template = builder.AddTemplate("Select /**select**/ from [Orders] O /**where**/ ");
builder.Select("O.OrderId")
                .Join("dbo.Contacts UC ON UC.UserContactId = O.UserContactId")
                .Join("dbo.OrderItems OMT ON OMT.OrderId = O.OrderId")
                .Join("dbo.OrderInformation OI ON OI.OrderId = O.OrderId")
                .LeftJoin("dbo.Log L ON L.OrderId = O.OrderId");
        builder.Where("O.UserId = {0}", request.UserId);
        builder.Where("O.InsertDate > {0}", LookBackDate);
conn.Query<int>(template.RawSql)
```
Here is the [demo](https://github.com/PublicWC/dapper-sqlite)(in VSCode).

**Comment by thedonmon** [comment]
Yep, I guess I was missing the fact that everything was run off the template. Figured the builder would have the responsibility to produce the SQL.
This makes sense tho! Thank you
