### ISSUE TITLE
getting Null reference exception

### ISSUE THREAD

**Issue by danboone** [StackExchange/Dapper#1070]
I am having a hard time getting the below query to run, my database is an Oracle database.
This works sometimes and sometimes we get this random error.  I am giving the 2 examples i have tried and both have thrown errors.  I have included the code and stack trace for each query type:

Also the query does return data for the id's I'm trying to run it for.

Here is the first trying to do it asynchronously.:
`var sql = @"select ols.delivery_group_id 
                        from gfs_oe.gfs_oe_order_linegroups ol
                        ,gfs_oe.gfs_oe_order_lg_shipments ols 
                        where ols.linegroup_id = ol.linegroup_id 
                        and ol.header_id = :Id 
                        group by ols.delivery_group_id ";
            var _db = con.GetConnection();
            try
            {
                var deli = await _db.QueryAsync<int>(sql, new { Id = HeaderId });
                return deli.ToList();
            }`

stack trace of error thrown:
 System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\\projects\\dapper\\Dapper\\SqlMapper.Async.cs:line 442\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n 

Here is  trying to run the query with just query:

`var sql = @"select ols.delivery_group_id 
                        from gfs_oe.gfs_oe_order_linegroups ol
                        ,gfs_oe.gfs_oe_order_lg_shipments ols 
                        where ols.linegroup_id = ol.linegroup_id 
                        and ol.header_id = :Id 
                        group by ols.delivery_group_id ";
            var _db = con.GetConnection();
            try
            {
                var deli = _db.Query<int>(sql, new { Id = HeaderId });
                return deli.ToList();
            }`

here is the stack trace of the error it throws:
System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Dapper.SqlMapper.<QueryImpl>d__138`1.MoveNext() in C:\\projects\\dapper\\Dapper\\SqlMapper.cs:line 1103\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\\projects\\dapper\\Dapper\\SqlMapper.cs:line 723

**Comment by jpdillingham** [comment]
@danboone care to share what the resolution was?

**Comment by url00** [comment]
I just ran into this same issue today.

Here is the line of code that I'm calling into Dapper with:
`var serversTokenListing = await conn.QueryAsync<Guid>("select AccessToken from Servers s inner join Entities e on s.EntityId = e.Id");`

When I'm working locally, this line runs fine and has no issues.
However, when my WebApp is running on Azure, I get the same error on the same line in SqlMapper.Async.cs.

The fix was to use nullable Guid's instead. So this line works for both local and Azure:
`var serversTokenListing = await conn.QueryAsync<Guid?>("select AccessToken from Servers s inner join Entities e on s.EntityId = e.Id");`
