### ISSUE TITLE
How to execute a SQL query without any Dapper caching?

### ISSUE THREAD

**Issue by tompazourek** [StackExchange/Dapper#1075]
As mentioned [in Dapper docs](https://github.com/StackExchange/Dapper#limitations-and-caveats), Dapper uses a `ConcurrentDictionary` to store its own caches with information about the queries being executed.

> Dapper caches information about every query it runs, this allows it to materialize objects quickly and process parameters quickly. The current implementation caches this information in a `ConcurrentDictionary` object. Statements that are only used once are routinely flushed from this cache. Still, **if you are generating SQL strings on the fly without using parameters it is possible you may hit memory issues**.

---

**Is there some way to execute some SQL queries so that they explicitly would not be cached by Dapper?**

I have some queries that are very much dynamically assembled, use temporary tables with random identifiers in there, parameters inlined in the string, etc. I think it would be a good idea to execute those without any cache involved. I know that the **ideal solution would be to rewrite the queries** in a better way, but I'm looking for a short-term solution here while diagnosing some performance issues. One of the things I'm looking at is that the `ConcurrentDictionary` memory allocated by Dapper keeps growing over time and isn't released. I'd like to try some things to get it under control without having to rewrite lots of code.

Is something like that possible in Dapper; just to execute some selected queries in a way that they don't end up in cache?

**Comment by mgravell** [comment]
Yes, but *right now* the only way to do that is via `CommandDefinition`, for example:

```c#
var cmdDef = new CommandDefinition("select @a; select @b;",
    new { a, b }, commandType: CommandType.Text, flags: CommandFlags.NoCache);
```

the important bit here is the `CommandFlags.NoCache`. There are similar `Query` etc methods that take `CommandDefinition`.
