### ISSUE TITLE
hope add 'Column to ignore' By Dapper.Contrib

### ISSUE THREAD

**Issue by snowchenlei** [StackExchange/Dapper#1092]
In Readme.md #Multi Mapping
class Post
{
    public int Id { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }
    public User Owner { get; set; }
}

class User
{
    public int Id { get; set; }
    public string Name { get; set; }
}
Now,I want to Upgate/Insert Post use Dapper.Contrib.But throw exception('Owner is invalid column');
So,I hope.
Thank you very much

**Comment by fravelgue** [comment]
Hi, you could avoid updates using [Computed] attribute

**Comment by snowchenlei** [comment]
@fravelgue 
Thank you for solving my problem.
I just went to the documentation and found [Computed] attribute, so I should read more documentation next time.
