### ISSUE TITLE
How used Dapper.SqlBuilder

### ISSUE THREAD

**Issue by EynsherKiel** [StackExchange/Dapper#1099]
Hello!

How get sql string from Dapper.SqlBuilder or please, give me a sample used in Dapper

**Comment by mdockal** [comment]
Here's a piece of code that should help.  The documentation is quite sparse!

```
SqlBuilder sb = new SqlBuilder();
var selector = sb.AddTemplate("SELECT * FROM Invoices /**where**/");
sb.Where("CustomerName = @CustomerName", new { CustomerName = "Ferd Farkle" });
var invoiceResults = db.Query<Invoice>(selector.RawSql, selector.Parameters);
```

**Comment by EynsherKiel** [comment]
Soooo, then we're must be enough wise about  /**where**/ and similar things.. It's terrible

Why dosn't use stack or something and remove template as excess class ?
