### ISSUE TITLE
'SqlConnection' does not contain a definition for 'QueryMultipleAsync'

### ISSUE THREAD

**Issue by ceemafour** [StackExchange/Dapper#1106]
I've just run into the same issue (Core 2.1.0, Dapper 1.50.5)

// usings
using Dapper;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Threading.Tasks;

using (var connection = new SqlConnection(@"data source=source;initial catalog=catalog;MultipleActiveResultSets=True;")) { await connection.OpenAsync(); result = await connection.QueryMultipleAsync<IEnumerable<User>>("GET_Users", null, commandType: CommandType.StoredProcedure); }

I get compile error:

'SqlConnection' does not contain a definition for 'QueryMultipleAsync' and no extension method 'QueryMultipleAsync' accepting a first argument of type 'SqlConnection' could be found (are you missing a using directive or an assembly reference?)

Similar to the issue here [https://github.com/StackExchange/Dapper/issues/566](url)

**Comment by NickCraver** [comment]
Unfortunately that method isn't a Dapper method. It's something from "Dapper Plus", another entity that has (without our permission and without notice) used our name.

With Dapper (our library), your link would look like:
```c#
result = await connection.Query<User>("GET_Users", null, commandType: CommandType.StoredProcedure);
```
Also note: we handle opening and closing the connection - you need not do so.
