### ISSUE TITLE
InvalidCastException on stored procedure with parameter type ReturnValue in MS sql

### ISSUE THREAD

**Issue by AndrewTakker** [StackExchange/Dapper#1107]
Trying get bit param from sp and map it to bool value.
![image](https://user-images.githubusercontent.com/4475559/44779269-b5925180-ab87-11e8-8afb-dbf995c388ce.png)
c#:
`			var query = "SomeTestProc";
			var param = new DynamicParameters();
			param.Add("@retVal", dbType: DbType.Boolean, direction: ParameterDirection.ReturnValue);
			SqlMapper.Execute(ConnectionFactory.CoreConnection(), query, param, commandType: CommandType.StoredProcedure);
			var retVal = param.Get<bool>("@retVal");`

Sql:

`create procedure [dbo].[SomeTestProc]
as
begin
	DECLARE
		@retVal bit
	set @retVal=1
		RETURN @retVal
end`

**Comment by NickCraver** [comment]
In your case that parameter, though it has a matching name, isn't a parameter. It's just used internally in the stored procedure to return a value. The correct Dapper usage there with existing SQL would be:

```c#
var retVal = ConnectionFactory.CoreConnection().Query<bool>("SomeTestProc", commandType: CommandType.StoredProcedure);
```

But for what you're after exploring output parameters, the SQL side needs the love, like this:
```sql
CREATE PROCEDURE [dbo].[SomeTestProc]
   @retVal BIT OUTPUT  
AS  
BEGIN
   SET @retVal = 1;
END
```
Hope that helps!

**Comment by AndrewTakker** [comment]
This is different param direction. I have this scenario in legacy db. In that sp used ReturnValue param direction.

**Comment by AndrewTakker** [comment]
I am use latest 1.50.5.  You can setup my sample code in first message. This is replayable sample of this issue.

**Comment by AndrewTakker** [comment]
I found that MS SQL in stored procedures returns only integer expression and no matter how you decribe sql parameter with Direction  = ReturnValue.
[https://docs.microsoft.com/en-us/sql/t-sql/language-elements/return-transact-sql?view=sql-server-2017](url)

Will try do fix in legacy to use output param insted return.

**Comment by NickCraver** [comment]
Problem clarified above - mismatch on SQL Server expectations (thanks for following up @AndrewTakker!) Closing this out to tidy up.
