### ISSUE TITLE
why remove .net4.0  version support?

### ISSUE THREAD

**Issue by ratku** [StackExchange/Dapper#1117]
why remove the .net framework 4.0  support  in the last version?

**Comment by NickCraver** [comment]
.NET Framework 4.0 is no longer supported by Microsoft, or its toolchain. We can no longer reasonably build for it and maintaining the code for such an old version is an unreasonable burden.

Previous releases will remain on NuGet and available if you're constrained to .NET 4.0. We recommend upgrading if it's an option though, a ton has changed (and improved) in .NET in the past 8 years.
