### ISSUE TITLE
Type Handlers and dynamic parameter

### ISSUE THREAD

**Issue by dallasbeek** [StackExchange/Dapper#1118]
If I set a type handler
`           
SqlMapper.AddTypeHandler<Guid>(new GuidTypeHandler());
`
and issue a query like this
`
conn.Query<Person>("select * from Person where Id = @Id", new { Id = Guid.NewGuid() });
`
I would expect my type handler to be called to return a properly structured Guid (Endian or other).  I don't think it is.

**Comment by NickCraver** [comment]
This is a known issue, but also a breaking change we'd have to take a major version to do - see the existing #433 for details.
