### ISSUE TITLE
Why QueryMultiple  with Oracle  is so slowly ?

### ISSUE THREAD

**Issue by yilezhu** [StackExchange/Dapper#1121]
I use dapper with Oracle,and I would like to use the "QueryMultiple" functionality.like under code(copy from stackoverflow):
`using Dapper;
using Oracle.ManagedDataAccess.Client;
using System.Data;

int selectedId = 1;
var sql = "BEGIN OPEN :rslt1 FOR SELECT * FROM customers WHERE customerid = :id; " +
                "OPEN :rslt2 FOR SELECT * FROM orders WHERE customerid = :id; " +
                "OPEN :rslt3 FOR SELECT * FROM returns Where customerid = :id; " +
          "END;";

OracleDynamicParameters dynParams = new OracleDynamicParameters();
dynParams.Add(":rslt1", OracleDbType.RefCursor, ParameterDirection.Output);
dynParams.Add(":rslt2", OracleDbType.RefCursor, ParameterDirection.Output);
dynParams.Add(":rslt3", OracleDbType.RefCursor, ParameterDirection.Output);
dynParams.Add(":id", OracleDbType.Int32, ParameterDirection.Input, selectedId);

using (IDbConnection dbConn = new OracleConnection("<conn string here>"))
{
    dbConn.Open();
    var multi = dbConn.QueryMultiple(sql, param: dynParams);

    var customer = multi.Read<Customer>().Single();
    var orders = multi.Read<Order>().ToList();
    var returns = multi.Read<Return>().ToList();
    ...
    dbConn.Close();
}`

but when work on  multi.Read<Customer>().Single(); It's so slowly ,! what this happened? why It's so slowly?

**Comment by mgravell** [comment]
What are you seeing that makes it seem slow? I don't have context to
understand that part, and I can't run your query without Oracle and your
data... So: what are you seeing there?

**Comment by yilezhu** [comment]
When I was debugging one step by F10 ,`var customer = multi.Read<Customer>().Single();` It takes a minute or so to wait. the next step `(var orders = multi.Read<Order>().ToList();)` also takes a minute or so to wait ,and the `var returns = multi.Read<Return>().ToList()`  .It takes a long time to wait.

**Comment by mgravell** [comment]
Ok. And how long does the query itself take, when executed outside of dapper?

**Comment by yilezhu** [comment]
When I used QueryAsync<Customer> execute three queries separately, I came out instantly. So I think QueryMultiple should not be very friendly to  Oracle support?

**Comment by mgravell** [comment]
I can't comment on that, but: if that approach doesn't work well with
oracle... don't use it, and use three separate queries? Again, though, I'd
be curious how the query performs *when executed as-is, outside of dapper*
- perhaps via ExecuteReader and raw ado.net; if that behaves similarly
(which I strongly suspect it will), dapper can't do anything about it - the
problem is layer down.

**Comment by yilezhu** [comment]
Thank you very much for your answer. I also want to ask, can dapper print the SQL sentences from birth?

**Comment by mgravell** [comment]
I don't understand the question. Can you perhaps try rephrasing? If you are
asking about logging all commands: miniprofiler is good for that.

**Comment by yilezhu** [comment]
I'm Sorry!I want to ask How to print SQL statements generated after dapper's incoming parameters ？I want to see what the generated SQL statement looks like.

**Comment by mgravell** [comment]
With the minor exception of "in @foo" queries and oledb positional
parameters, dapper (core) doesn't generate *anything* - it leaves
parameters as parameters. The query that gets issued is exactly the query
you gave it.

**Comment by yilezhu** [comment]
Thank you very much! I got it !
