### ISSUE TITLE
MySql TimeStamp to C# DateTime

### ISSUE THREAD

**Issue by defoliation** [StackExchange/Dapper#1124]
hi i'm use Dapper Default Setting,
when i new Query for my Code 
Exapmle :  
```sql
table struct:
CREATE TABLE `timeZomeTest` (
  `RecordID` int(11) NOT NULL AUTO_INCREMENT,
  `CreationDate` datetime NOT NULL,
  `ModifiedDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`RecordID`)
)  DEFAULT CHARSET=utf8 ;
```
time zone :China Standard Time UT+8:00
Insert Data:
```sql
INSERT INTO `timeZomeTest` (`CreationDate`) VALUES ('2018-9-11 ');
```
query:
```sql
slect * from timeZomeTest
```
the result:
![queryresult](https://user-images.githubusercontent.com/13504360/45334504-98a94580-b5ad-11e8-90d4-e38b804ce08f.png)

this result look for perferct

but on the C# 
the C# Code
```c#
public class TimeZomeTest
{
    public int  RecordID {get;set}
    public Datetime CreationDate{get;set;}
    public Datetime  ModifiedDate{get;set;}
}
```
where i use dapper query `select * from timeZomeTest limit 1`
the result ModifiedDate.Kind=Utc but the Value is '2018-09-11 10:27:33'
so the time more the current time 8 hour

**Comment by NickCraver** [comment]
In your C# code, DateTime doesn't carry an offset portion to the data...you likely want `DateTimeOffset` here :)

**Comment by defoliation** [comment]
@NickCraver you mean is maybe i should use DateTimeOffset  to be adjusted ,Dapper do not this it?

**Comment by NickCraver** [comment]
@defoliation `DateTime` isn't the proper 1:1 type with the database there, you'll want a `DateTimeOffset` if your intent is to handle time zone data in the field :)

For more info, you can read about the differences here: https://docs.microsoft.com/en-us/dotnet/standard/datetime/choosing-between-datetime

Many apps don't store timezone info (all times are UTC in the database), and in those cases `DateTime` is fine. Since you care here, you need `DatetimeOffset` instead.

**Comment by defoliation** [comment]
@NickCraver Thanks for your answer very much
i try use DatetimeOffset fix the problem 
if i have done ,i can relpay again

**Comment by defoliation** [comment]
i am so sorry, the DatetimeOffset not fix my question ,becaue  mysql rentu value is contanin my timezone ,mysql handle the timezone,but dapper handle timestamp type value , again ,

for exapmle :
mysql time value is 1536632853 , show is  2018-09-11 10:27:33(China Standard Time UT+8:00)

mysql retun value  is  2018-09-11 10:27:33(China Standard Time UT+8:00)
but
Dapper Value is 2018-09-11 10:27:33(UTC)

**Comment by bgrainger** [comment]
MySQL Server doesn't store any time zone information. As per [time zone support](https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html):

> The current session time zone setting affects display and storage of time values that are zone-sensitive. This includes the values displayed by functions such as NOW() or CURTIME(), and values stored in and retrieved from TIMESTAMP columns. Values for TIMESTAMP columns are converted from the current time zone to UTC for storage, and from UTC to the current time zone for retrieval.

When a DateTime column value is sent from the MySQL Server to the client, it's sent without any time zone information. Connector/NET (i.e., MySql.Data) tries to synthesize the time zone based on some heuristics about the difference between the server's and client's time zone. You can see the history of how this has changed in these bugs: [63812](https://bugs.mysql.com/bug.php?id=63812), [66964](https://bugs.mysql.com/bug.php?id=66964).

I think you're running into a (as yet unreported?) bug in Connector/NET where the value of `MySqlDataReader.GetDateTime()` differs from `MySqlDataReader.GetValue()`. This can be demonstrated with the following code:

```csharp
using (var connection = new MySqlConnection("..."))
{
	connection.Open();
	
	using (var cmd = new MySqlCommand("select * from hello_world.timeZomeTest;", connection))
	using (var reader = cmd.ExecuteReader())
	{
		reader.Read();
		Console.WriteLine(reader.GetDateTime(2).Kind); // Local
		
		Console.WriteLine(((DateTime) reader.GetValue(2)).Kind); // Utc
	}

	var tz = connection.Query<TimeZomeTest>("select * from hello_world.timeZomeTest").Single();
	Console.WriteLine(tz.ModifiedDate.Kind); // Utc
}
```

Dapper just reports the `DateTimeKind` that is provided to it by Connector/NET; it relies on the database connection library to report correct values.

FWIW, [MySqlConnector](https://github.com/mysql-net/MySqlConnector) doesn't have any time zone heuristics and just reports `Unspecified` for all the examples above. It does provide a `DateTimeKind` connection string option if you'd like to force Local or Utc on the returned values. (This isn't always appropriate; for example, `select utc_timestamp(), current_timestamp();` will return two timestamps with different (implied) time zones.)

**Comment by bgrainger** [comment]
Filed this (with Oracle) as [bug 92367](https://bugs.mysql.com/bug.php?id=92367).

**Comment by defoliation** [comment]
@NickCraver i am use MySql.Data.6.9.9 
Thank you very much @NickCraver @bgrainger   
may be i need update my driver for MySql
