### ISSUE TITLE
connection.ExecuteReaderAsync returns IDataReader which has no ReadAsync

### ISSUE THREAD

**Issue by jnm2** [StackExchange/Dapper#1140]
It's currently necessary to cast the returned IDataReader to DbDataReader in order to do anything asynchronous with it:

```c#
using (var reader = (DbDataReader)await connection.ExecuteReaderAsync(command).ConfigureAwait(false))
{
    while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
    {
        // ..
    }
}
```

The extension method takes an IDbConnection, so this makes sense:

https://github.com/StackExchange/Dapper/blob/48f6754ad69c5bc196612ec23f4887062fa87e17/Dapper/SqlMapper.Async.cs#L1116

Would you please define this extension method next to it?

```c#
public static Task<DbDataReader> ExecuteReaderAsync(this DbConnection cnn, CommandDefinition command)
```

That way this code sample just works:

```c#
using (var reader = await connection.ExecuteReaderAsync(command).ConfigureAwait(false))
{
    while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
    {
        // ..
    }
}
```

**Comment by thomas-rose** [comment]
+1

**Comment by mgravell** [comment]
I see your point, and that's very nice. Would be happy to take that as a PR (probably the quickest way to get it implemented).

This also probably also ties into v2 API refactors, though. I'll start a separate issue for that.

**Comment by mgravell** [comment]
cross-ref https://github.com/StackExchange/Dapper/issues/1293

**Comment by jnm2** [comment]
@mgravell #1293 has a bunch of exciting plans and now I'm really looking forward to v2. In the meantime, I'll definitely work on a PR.

**Comment by jnm2** [comment]
I didn't see this at first, but this is a source-breaking change. Explained at https://github.com/StackExchange/Dapper/pull/1295.
