### ISSUE TITLE
NVarchar insert issue

### ISSUE THREAD

**Issue by anujithramanan** [StackExchange/Dapper#1157]
while Inserting a nvarchar string to mysql db it becomes to ?????

**Comment by mgravell** [comment]
There really isn't enough detail to investigate that. What was the column
def? What was the value? What was the insert SQL? What was the dB version?
We need somewhere to start...

**Comment by znyet** [comment]
when create mysql table , maybe you must choose utf8 encoding.

**Comment by NickCraver** [comment]
Not enough info to go on here and no updates - closing out.

**Comment by bgrainger** [comment]
@znyet `utf8mb4` should be preferred over `utf8` for MySQL: https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434
