### ISSUE TITLE
Dapper can't find POCO mapping from SELECT CASE query

### ISSUE THREAD

**Issue by Jakemangan** [StackExchange/Dapper#1158]
I'm extracting information from a SQL Server database using Dapper. The POCO for the information in question is below.

    public class Client
        {
            public string ShortName { get; set; }
            public string ContactDetail { get; set; }
            public string Street { get; set; }
            public string District { get; set; }
            public string Town { get; set; }
            public string County { get; set; }
            public string Postcode { get; set; }
        }

When I extract the information for the above object using the query below all the information is mapped correctly, apart from the following line `max(case when cd.Type = 1 OR cd.Type = 2 then cd.Detail end) as 'ContactDetail'` I believe this may be because I am not simply extracting the data from a table column and I am instead doing some processing using the CASE clause beforehand and therefore Dapper cannot find the correct place to map the information onto.

I thought including the `AS` clause would help Dapper to find the correct mapping but this didn't actually work.

How can I change my query so that Dapper can map the ContactDetail data correctly?

    select 
	tp.ShortName as 'ShortName', 
	max(case when cd.Type = 1 OR cd.Type = 2 then cd.Detail end) as 'ContactDetail',
	tp.Street, 
	tp.District, 
	tp.Town, 
	tp.County, 
	tp.PostCode
	... (rest of query snipped as unneeded)

I know the query works correctly as I can run it in SSMS and it returns the correct information.

**Comment by mgravell** [comment]
Can I please see how you're invoking this? It looks like it *should* work fine. To be explicit: dapper doesn't care *at all* what is in the query - it doesn't inspect it or do anything (except some initial parameter detection); and assuming you're just using `Query<T>` (etc), then the mapping afterwards is based *just* on the shape of the results grid. If the grid has a column called `ContactDetail`, and the class has a matching property called `ContactDetail`, then it *should* work.

The most likely reason I can think of for failure here would be if it was neither type 1 nor type 2 - as a quick test, can I suggest that you try:

    max(case when cd.Type = 1 OR cd.Type = 2 then cd.Detail else 'N/A' end) as 'ContactDetail',

just to see if that is the problem?

**Comment by Jakemangan** [comment]
So the way this is being invoked is through the standard way using Query<T> the code is below.

```
public List<Client> ReadClientByApplicationNumber(int applicationNumber)
        {
            using (IDbConnection db = CreateConnection())
            {
                return db.Query<Client>(BuildQuery(), new{applicationNumber}).ToList();
            }
        }
```
I changed the line of my query as you suggested and the results are quite strange. With my original query the results are not returned as I previously described. However when I include your line the results are returned how I originally expected them to be.

Why does adding ```else 'N/A'``` allow the results to be printed?

**Comment by mgravell** [comment]
@Jakemangan  without data that let's me actually reproduce what you're seeing, it is *really* hard to comment; I *suspect* that it is a null coalescing issue, perhaps related to `MAX`, but... almost impossible to investigate without representative data.

Note also: ADO.NET (`SqlClient`) and SSMS actually have subtly different `SET` option defaults, so it could also be that the difference is related to a `SET` behaviour option.

Dapper really doesn't care - it just processes what it gets back :)
