### ISSUE TITLE
Signature problem?

### ISSUE THREAD

**Issue by 107295472** [StackExchange/Dapper#1161]
Failed to load a file or assembly of "Dapper, Version=1.50.5.0, Culture=neutral, PublicKeyToken=null" or one of its dependencies. A strong name assembly is required. (exceptions come from HRESULT:0x80131044)

**Comment by mgravell** [comment]
If you need a strong-named version: [Dapper.StrongName](https://www.nuget.org/packages/Dapper.StrongName/) - same code, different package.

It would be nice to unify them, but adding a strong name is an identity breaking change. That doesn't mean we can't do it - it just needs to be planned, communicated, etc.

**Comment by 107295472** [comment]
Thank you
