### ISSUE TITLE
Connect to Oracle using dapper.contrib

### ISSUE THREAD

**Issue by EminemJK** [StackExchange/Dapper#1165]
Hi，I like the component dapper.contrib very much, but it doesn't support Oracle. Do you have any plans to add support for Oracle in dapper.contrib ?

**Comment by znyet** [comment]
my DapperExtensions can reslove your problem
https://github.com/znyet/DapperExtensions

**Comment by EminemJK** [comment]
> my DapperExtensions can reslove your problem
> https://github.com/znyet/DapperExtensions

I solved the problem on my own ,
https://github.com/EminemJK/Banana
