### ISSUE TITLE
Dapper prevent Blazor Client to compile

### ISSUE THREAD

**Issue by Safirion** [StackExchange/Dapper#1174]
Hello,

When I add dapper to a Blazor Client projet dependencies, the project fail to compile with this error : 

`Gravité	Code	Description	Projet	Fichier	Ligne	Suppression State
Erreur	MSB3073	La commande "dotnet "C:\Users\gauth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0\targets\../tools/illink/illink.dll" -l none --verbose --strip-security true --exclude-feature com --exclude-feature sre -v false -c link -u link -b true -d "C:\Users\gauth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0\targets\../tools/mono/bcl/" -d "C:\Users\gauth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0\targets\../tools/mono/bcl/Facades/" -o "D:\Dev\Projects\BlazorApp1\obj\Debug\netstandard2.0\blazor\linker/" -x "C:\Users\gauth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0\targets\BuiltInBclLinkerDescriptor.xml" -x "D:\Dev\Projects\BlazorApp1\obj\Debug\netstandard2.0\blazor\linker.descriptor.xml" -a "C:\Users\gauth\.nuget\packages\dapper\1.50.5\lib\netstandard2.0\Dapper.dll" -a "C:\Users\gauth\.nuget\packages\microsoft.aspnetcore.blazor\0.7.0\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.dll" -a "C:\Users\gauth\.nuget\packages\microsoft.aspnetcore.blazor.browser\0.7.0\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.Browser.dll" -a "C:\Users\gauth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0\lib\netstandard1.0\Microsoft.AspNetCore.Blazor.TagHelperWorkaround.dll" -a "C:\Users\gauth\.nuget\packages\microsoft.extensions.dependencyinjection\2.1.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.dll" -a "C:\Users\gauth\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\2.1.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "C:\Users\gauth\.nuget\packages\microsoft.jsinterop\0.7.0\lib\netstandard2.0\Microsoft.JSInterop.dll" -a "C:\Users\gauth\.nuget\packages\microsoft.win32.registry\4.4.0\lib\netstandard2.0\Microsoft.Win32.Registry.dll" -a "C:\Users\gauth\.nuget\packages\mono.webassembly.interop\0.7.0\lib\netstandard2.0\Mono.WebAssembly.Interop.dll" -a "C:\Users\gauth\.nuget\packages\system.data.sqlclient\4.4.0\lib\netstandard2.0\System.Data.SqlClient.dll" -a "C:\Users\gauth\.nuget\packages\system.diagnostics.diagnosticsource\4.4.1\lib\netstandard1.3\System.Diagnostics.DiagnosticSource.dll" -a "C:\Users\gauth\.nuget\packages\system.reflection.emit.ilgeneration\4.3.0\lib\netstandard1.3\System.Reflection.Emit.ILGeneration.dll" -a "C:\Users\gauth\.nuget\packages\system.reflection.emit.lightweight\4.3.0\lib\netstandard1.3\System.Reflection.Emit.Lightweight.dll" -a "C:\Users\gauth\.nuget\packages\system.reflection.typeextensions\4.4.0\lib\netstandard2.0\System.Reflection.TypeExtensions.dll" -a "C:\Users\gauth\.nuget\packages\system.security.accesscontrol\4.4.0\lib\netstandard2.0\System.Security.AccessControl.dll" -a "C:\Users\gauth\.nuget\packages\system.security.principal.windows\4.4.0\lib\netstandard2.0\System.Security.Principal.Windows.dll" -a "C:\Users\gauth\.nuget\packages\system.text.encoding.codepages\4.4.0\lib\netstandard2.0\System.Text.Encoding.CodePages.dll" -a "C:\Users\gauth\.nuget\packages\system.threading\4.3.0\lib\netstandard1.3\System.Threading.dll" -a "C:\Users\gauth\.nuget\packages\microsoft.win32.registry\4.4.0\runtimes\win\lib\netstandard1.3\Microsoft.Win32.Registry.dll" -a "C:\Users\gauth\.nuget\packages\runtime.win-arm64.runtime.native.system.data.sqlclient.sni\4.4.0\runtimes\win-arm64\native\sni.dll" -a "C:\Users\gauth\.nuget\packages\runtime.win-x64.runtime.native.system.data.sqlclient.sni\4.4.0\runtimes\win-x64\native\sni.dll" -a "C:\Users\gauth\.nuget\packages\runtime.win-x86.runtime.native.system.data.sqlclient.sni\4.4.0\runtimes\win-x86\native\sni.dll" -a "C:\Users\gauth\.nuget\packages\system.data.sqlclient\4.4.0\runtimes\unix\lib\netstandard2.0\System.Data.SqlClient.dll" -a "C:\Users\gauth\.nuget\packages\system.data.sqlclient\4.4.0\runtimes\win\lib\netstandard2.0\System.Data.SqlClient.dll" -a "C:\Users\gauth\.nuget\packages\system.security.accesscontrol\4.4.0\runtimes\win\lib\netstandard1.3\System.Security.AccessControl.dll" -a "C:\Users\gauth\.nuget\packages\system.security.principal.windows\4.4.0\runtimes\win\lib\netstandard1.3\System.Security.Principal.Windows.dll" -a "C:\Users\gauth\.nuget\packages\system.text.encoding.codepages\4.4.0\runtimes\win\lib\netstandard2.0\System.Text.Encoding.CodePages.dll" -a "D:\Dev\Projects\BlazorApp1\obj\Debug\netstandard2.0\BlazorApp1.dll"" s'est arrêtée avec le code 1.	BlazorApp1	C:\Users\gauth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0\targets\Blazor.MonoRuntime.targets	439	
`

`
1>BlazorApp1 -> D:\Dev\Projects\BlazorApp1\bin\Debug\netstandard2.0\BlazorApp1.dll
1>Fatal error in IL Linker
1>System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
1>   at Mono.Cecil.PE.ImageReader.ReadOptionalHeaders(UInt16& subsystem, UInt16& dll_characteristics, UInt16& linker)
1>   at Mono.Cecil.PE.ImageReader.ReadImage()
1>   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable1 stream, String file_name)
1>   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
1>   at Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName, ReaderParameters parameters)
1>   at Mono.Linker.LinkContext.Resolve(String name)
1>   at Mono.Linker.Steps.ResolveFromAssemblyStep.Process()
1>   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
1>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>   at Mono.Linker.Pipeline.Process(LinkContext context)
1>   at Mono.Linker.Driver.Run(ILogger customLogger)
1>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
1>C:\Users\gauth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0\targets\Blazor.MonoRuntime.targets(439,5): error MSB3073: La commande "dotnet "C:\Users\gauth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0\targets\../tools/illink/illink.dll" -l none --verbose --strip-security true --exclude-feature com --exclude-feature sre -v false -c link -u link -b true -d "C:\Users\gauth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0\targets\../tools/mono/bcl/" -d "C:\Users\gauth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0\targets\../tools/mono/bcl/Facades/" -o "D:\Dev\Projects\BlazorApp1\obj\Debug\netstandard2.0\blazor\linker/" -x "C:\Users\gauth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0\targets\BuiltInBclLinkerDescriptor.xml" -x "D:\Dev\Projects\BlazorApp1\obj\Debug\netstandard2.0\blazor\linker.descriptor.xml" -a "C:\Users\gauth\.nuget\packages\dapper\1.50.5\lib\netstandard2.0\Dapper.dll" -a "C:\Users\gauth\.nuget\packages\microsoft.aspnetcore.blazor\0.7.0\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.dll" -a "C:\Users\gauth\.nuget\packages\microsoft.aspnetcore.blazor.browser\0.7.0\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.Browser.dll" -a "C:\Users\gauth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0\lib\netstandard1.0\Microsoft.AspNetCore.Blazor.TagHelperWorkaround.dll" -a "C:\Users\gauth\.nuget\packages\microsoft.extensions.dependencyinjection\2.1.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.dll" -a "C:\Users\gauth\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\2.1.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "C:\Users\gauth\.nuget\packages\microsoft.jsinterop\0.7.0\lib\netstandard2.0\Microsoft.JSInterop.dll" -a "C:\Users\gauth\.nuget\packages\microsoft.win32.registry\4.4.0\lib\netstandard2.0\Microsoft.Win32.Registry.dll" -a "C:\Users\gauth\.nuget\packages\mono.webassembly.interop\0.7.0\lib\netstandard2.0\Mono.WebAssembly.Interop.dll" -a "C:\Users\gauth\.nuget\packages\system.data.sqlclient\4.4.0\lib\netstandard2.0\System.Data.SqlClient.dll" -a "C:\Users\gauth\.nuget\packages\system.diagnostics.diagnosticsource\4.4.1\lib\netstandard1.3\System.Diagnostics.DiagnosticSource.dll" -a "C:\Users\gauth\.nuget\packages\system.reflection.emit.ilgeneration\4.3.0\lib\netstandard1.3\System.Reflection.Emit.ILGeneration.dll" -a "C:\Users\gauth\.nuget\packages\system.reflection.emit.lightweight\4.3.0\lib\netstandard1.3\System.Reflection.Emit.Lightweight.dll" -a "C:\Users\gauth\.nuget\packages\system.reflection.typeextensions\4.4.0\lib\netstandard2.0\System.Reflection.TypeExtensions.dll" -a "C:\Users\gauth\.nuget\packages\system.security.accesscontrol\4.4.0\lib\netstandard2.0\System.Security.AccessControl.dll" -a "C:\Users\gauth\.nuget\packages\system.security.principal.windows\4.4.0\lib\netstandard2.0\System.Security.Principal.Windows.dll" -a "C:\Users\gauth\.nuget\packages\system.text.encoding.codepages\4.4.0\lib\netstandard2.0\System.Text.Encoding.CodePages.dll" -a "C:\Users\gauth\.nuget\packages\system.threading\4.3.0\lib\netstandard1.3\System.Threading.dll" -a "C:\Users\gauth\.nuget\packages\microsoft.win32.registry\4.4.0\runtimes\win\lib\netstandard1.3\Microsoft.Win32.Registry.dll" -a "C:\Users\gauth\.nuget\packages\runtime.win-arm64.runtime.native.system.data.sqlclient.sni\4.4.0\runtimes\win-arm64\native\sni.dll" -a "C:\Users\gauth\.nuget\packages\runtime.win-x64.runtime.native.system.data.sqlclient.sni\4.4.0\runtimes\win-x64\native\sni.dll" -a "C:\Users\gauth\.nuget\packages\runtime.win-x86.runtime.native.system.data.sqlclient.sni\4.4.0\runtimes\win-x86\native\sni.dll" -a "C:\Users\gauth\.nuget\packages\system.data.sqlclient\4.4.0\runtimes\unix\lib\netstandard2.0\System.Data.SqlClient.dll" -a "C:\Users\gauth\.nuget\packages\system.data.sqlclient\4.4.0\runtimes\win\lib\netstandard2.0\System.Data.SqlClient.dll" -a "C:\Users\gauth\.nuget\packages\system.security.accesscontrol\4.4.0\runtimes\win\lib\netstandard1.3\System.Security.AccessControl.dll" -a "C:\Users\gauth\.nuget\packages\system.security.principal.windows\4.4.0\runtimes\win\lib\netstandard1.3\System.Security.Principal.Windows.dll" -a "C:\Users\gauth\.nuget\packages\system.text.encoding.codepages\4.4.0\runtimes\win\lib\netstandard2.0\System.Text.Encoding.CodePages.dll" -a "D:\Dev\Projects\BlazorApp1\obj\Debug\netstandard2.0\BlazorApp1.dll"" s'est arrêtée avec le code 1.
1>Génération du projet "BlazorApp1.csproj" terminée -- ÉCHEC.
`

To reproduce, just create a Blazor project with the command :
`dotnet new blazor -o BlazorApp1`

Add dapper in nuget dependencies
And run

**Comment by Rymix** [comment]
I got the same issue with the sample project.
issou

**Comment by Safirion** [comment]
This may be a problem with your nuget package generation.
I tried to compile dapper from the version of the github repository and adding the .netstandard2.0 version to the dependencies of my Blazor project and it finaly compile perfectly.

**Comment by chrgraefe** [comment]
@Safirion What have you exactly done? Is there a PR

**Comment by NickCraver** [comment]
Is this an issue for Blazor today? It's progressed a _lot_ since the early-early days. I tried the following:

```bash
dotnet new blazor -o BlazorApp1
```
Added:
```xml
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.0.35" />
  </ItemGroup>
```
Then:
```bash
cd BlazorApp1
dotnet restore
dotnet build
```
All green on the build front here:
![image](https://user-images.githubusercontent.com/454813/80894190-fcaedf00-8ca6-11ea-9892-a0e4366c6aef.png)
...so I'm guessing this was an issue with the earlier version of the linker.
