### ISSUE TITLE
New transaction is not allowed

### ISSUE THREAD

**Issue by digitalmedia34** [StackExchange/Dapper#1183]
I am using polly with dapper orm in one of my projects. The issue that I am getting is that sometimes when I try to do update I get error 'New transaction is not allowed because there are other threads running in the session.' I need to mention that I am creating a new 'Idbtransanction' transaction when doing this update. The update also had a retry policy on sql timeout. Trying to mitigate the issue, I removed all async code, and my suspicion is that I am encountering an error with sql server, polly is retrying (like it should) but the transaction still active.

Has anybody encountered this issue? Any ideas on how to handle this scenario are welcome.

Ps, dont know if this is the right place to post this question.

**Comment by NickCraver** [comment]
Are you re-using the same connection in multiple things? This often happens with `async`. Or possibly Entity Framework or some other ORM also in play? These are the 2 places we see this kind of behavior users hit unexpectedly. It's not Dapper specific, it's something you'd hit in raw ADO.NET as well.

**Comment by NickCraver** [comment]
Is Polly retrying in the background? Sorry, I'm not familiar with it.

**Comment by NickCraver** [comment]
@digitalmedia34 There's not a lot we can do there...that's multiple things fighting for the same connection. You'd see the same behavior without Dapper in those scenarios.

**Comment by digitalmedia34** [comment]
@NickCraver havent tried with out Dapper but polly reuses the same connection, dont think that's the issue. The problem, I think, is that second time it tries, it tries to reuse the same transaction. It is like the PREV transaction is not done when it retries.

**Comment by digitalmedia34** [comment]
Ps, it works fine if I remove the transaction part

**Comment by NickCraver** [comment]
Going to close this one out to tidy up since it is a Polly issue with overlaps and not Dapper (more importantly: there's nothing we can do to fix it). The transaction removal which removes contention and allows more success with fewer needs to retry makes sense, and if that's a solution in this case: awesome! Either way...there's nothing we can do to help here and I do recommend poling Polly about this issue (I'd be surprised if it wasn't filed already).
