### ISSUE TITLE
SQL Server，Select IN Exception

### ISSUE THREAD

**Issue by iexapl** [StackExchange/Dapper#1185]
SQL Server：
SELECT [ColumnName] FROM [TableName] WHERE [Id] IN (1085070765231050752,1085070765231050753,1085070765231050754)

Exception：
Error parsing column 0 (Id=1085070765231050752 - Int64)

**Comment by pedroinfo** [comment]
Can you put your code? Probably a problem with your logic.

**Comment by mgravell** [comment]
I'm still not seeing any dapper specific code here; I'd be happy to assist, but ... there really isn't enough to go on here. Happy to reopen to investigate, but kinda needs a minimal repro

**Comment by lyzcren** [comment]
your "id" column is so long, are you sure your "id" column is type of "int"? or it would be varchar?
if it's varchar, your IN should be as below
`IN ('1085070765231050752','1085070765231050753','1085070765231050754')`
I recommend you should try this, and good luck to you.
