### ISSUE TITLE
datetime parameter not working in docker linux instance

### ISSUE THREAD

**Issue by cburgerCA** [StackExchange/Dapper#1189]
Unfortunately don't have a lot of information, but here goes.
Dapper 1.50.5 won't pass DateTime values as parameters when running in a docker instance. This functionality works in 1.50.4.
Passing as a DynamicParameter or as an anonymous object type does not work.
This works:
`await sqlConnection.ExecuteAsync("Insert Into DateTest (NowDate) value '2018-02-08 00:00:00'");` 
This does not:
`var dynParams = new DynamicParameters();`
`dynParams.Add("NowDate", DateTime.Now, DbType.DateTime);`
`await sqlConnection.ExecuteAsync("Insert Into DateTest (NowDate) value @NowDate", dynParams);`

**Comment by NickCraver** [comment]
When you say "this does not"...what happens? What's the error? What's the failure? Saying "it doesn't work" gives us almost nothing to go on - always include what happens :)

**Comment by NickCraver** [comment]
Closing out due to inactivity - not enough info to go on.
