### ISSUE TITLE
Need to use MakeByRefType to avoid problems with GC

### ISSUE THREAD

**Issue by AndyAyersMS** [StackExchange/Dapper#1190]
See dotnet/coreclr#18865

cc @xPaw

`unbox` of a struct produces a managed pointer (type `&`) so the local here needs to be declared as a ByRef. Otherwise the jit won't track the pointer and report it to GC, leading to eventual badness when GC moves things.

https://github.com/StackExchange/Dapper/blob/1cd3efd89485ccd0bdcc6036eaa5a12a311189fd/Dapper/SqlMapper.cs#L2410-L2426

```diff
-            il.DeclareLocal(type.MakePointerType());
+            il.DeclareLocal(type.MakeByRefType());
```

**Comment by mgravell** [comment]
Thanks Andy. I was about to do a "just let me check some equivalent IL disassembly to be sure", and then I noticed it was you - so... that saves me some time :) will fix.

**Comment by xPaw** [comment]
Thanks for the quick fix

**Comment by mgravell** [comment]
[1.50.7](https://www.nuget.org/packages/Dapper/1.50.7) deployed to nuget
