### ISSUE TITLE
SqlGeography not supported on Dapper 1.50.5

### ISSUE THREAD

**Issue by tejamaripuri** [StackExchange/Dapper#1192]
I am having the same issue as this https://stackoverflow.com/questions/12090549/mapping-sqlgeography-with-dapper with Dapper 1.50.5

**Comment by NickCraver** [comment]
Are you referencing the https://www.nuget.org/packages/Microsoft.SqlServer.Types/ package? That's necessary, until the types are baked into the managed framework (which is coming to .NET Core, possibly in 3.0).

If so, an this isn't working, what version of SQL Server are you connecting to? And which version of .NET is your project targeting?

**Comment by d-sky** [comment]
I have the same problem as described in original post. Insertion of SqlGeography doesn't work with error **The member [field name] of type Microsoft.SqlServer.Types.SqlGeography cannot be used as a parameter value**. Although mapping from DB to SqlGeography works fine.
Dapper version is 1.60.6
SQL Server 2017 Developer

**Comment by NickCraver** [comment]
@d-sky same question - are you explicitly including that package? If so, can you please include a stack trace?

**Comment by mgravell** [comment]
Also: please let us know version numbers. I rechecked things for 2.* and
they worked. So if you're using 1.*, I'd say "try 2.*"

**Comment by d-sky** [comment]
Confirmed! Works fine with 2.0.4. Thanks!

**Comment by NickCraver** [comment]
Awesome - going to close this out then :)
