### ISSUE TITLE
Linking to issues in release notes

### ISSUE THREAD

**Issue by NRKirby** [StackExchange/Dapper#1194]
When I was looking through the [release notes](https://stackexchange.github.io/Dapper/) yesterday I noticed the fixes in each release don't link to the issues on GitHub.

Would you accept a pull request which adds links to issues for all of the fixes on the [docs page](https://github.com/StackExchange/Dapper/blob/master/docs/index.md)?

For example, adding a link to issue 1190 fixed in the latest release:

> Fix [#1190](https://github.com/StackExchange/Dapper/issues/1190) - incorrect unmanaged pointer when processing parameters that are a boxed struct (rare error relating to GC)

If you'll accept, I'll happily do a PR

**Comment by NickCraver** [comment]
@NRKirby Absolutely - we always appreciate such PRs!

**Comment by NRKirby** [comment]
Great, thanks @NickCraver

Will submit a PR soon!

**Comment by NickCraver** [comment]
Fixed via #1195, thanks!!
