### ISSUE TITLE
Add a string paramer without quotes in Dapper

### ISSUE THREAD

**Issue by LuisSerrano** [StackExchange/Dapper#1197]
I have this query:
**SELECT ClientId, FileName, Text, LogType, CreationDate 
FROM dbo.Logs 
WHERE TaskName = @taskName 
AND LogType = @logType 
AND AppDescription = @appDescription**

And I have three types of log (Error, Info and Warning).
 If I want to see all the log entries I put this:
**AND LogType = LogType** (in SQL works)

But with Dapper when a try to put the dynamis parameter @logType  = Logtype, dapper puts quotes.

There is some way that dapper does not put the quotes (LogType is a varchar)

Thanks in advance

**Comment by NRKirby** [comment]
What overload are you using? Can you show us your code?

**Comment by mgravell** [comment]
Dapper never adds quotes. In the query you've issued, it won't be changed **at all** - it will be sent verbatim. Can you show your actual usage here including the parameters *and their types/values*? It doesn't have to be "real" values, something like:

``` c#
connection.Execute(yourSqlFromAbove, new {
    taskName = "abc", LogType = 42, appDescription = "Fred"
});
```

should be enough. Also: what database is this? Specifically, what **actual type** is `connection? What a **specific provider** does with the parameters can be provider specific; the OleDb provider might behave very differently to the SqlClient provider, for example.
