### ISSUE TITLE
Why Entityframwork.net has used Dapper?

### ISSUE THREAD

**Issue by RezaAb** [StackExchange/Dapper#1200]
I just found this error on https://entityframework.net/ and I understood that it uses Dapper. 
Why it doesn't use its own? :)
![entityframwork](https://user-images.githubusercontent.com/1415078/53411289-5947a780-39db-11e9-95d5-950cd1226f3c.jpg)

**Comment by imanfattahi** [comment]
😁😁😁😁

**Comment by shahabkamali** [comment]
ah you mean entityframework website is using Dapper?

**Comment by kelvindules** [comment]
So you opened an issue that is not an issue to talk about something completely out of the scope of the repository?

**Comment by RezaAb** [comment]
> 
> 
> So you opened an issue that is not an issue to talk about something completely out of the scope of the repository?

Yes, you right but it's so weird.

**Comment by mgravell** [comment]
Very interesting report, but I suspect that only the EF website folks could answer this.

As a purely speculative answer: "because it was a perfectly applicable tool for whatever job the website needed to do at that point".

You're allowed to use multiple tools, and I could quite happily believe that they're using EF in some places, Dapper in others, depending on what makes most sense on a particular route.

**Comment by mgravell** [comment]
oh, actually I take that back; that site isn't by the EF team at all; it is by ... well, let's just say that "making things look like they might be official / sanctioned / etc" isn't new to them. Again: that site is nothing whatsoever to do with the EF team.

**Comment by kelvindules** [comment]
> oh, actually I take that back; that site isn't by the EF team at all; it is by ... well, let's just say that "making things look like they might be official / sanctioned / etc" isn't new to them. Again: that site is nothing whatsoever to do with the EF team.

Thats why I found it strange to be discussed here. Maybe reacted too strong tho.

Theres even a *Dapper Plus* download provided by this ZZZ Projects... company?

It's strange.

**Comment by fuzzzerd** [comment]
At the risk of further contributing to off-topic discussion; I've run across several of their products. They aren't bad and often provide some extra functionality over the product who's name they've coopted, but the way they operate is fairly shady. As evidenced by their domain and product naming scheme.
