### ISSUE TITLE
Documention Incorrect for Contrib Inserts

### ISSUE THREAD

**Issue by markalanevans** [StackExchange/Dapper#1202]
The documentation here: 
https://github.com/StackExchange/Dapper/tree/master/Dapper.Contrib#special-attributes

Says "[Table("Tablename")] - use another table name instead of the name of the class"

But that is not correct, the code here:
https://github.com/StackExchange/Dapper/blob/master/Dapper.Contrib/SqlMapperExtensions.cs#L309

takes the class name and add's an "s".

So it seems to me that the example is backwards.

**Comment by NickCraver** [comment]
Thanks for the poke! The docs now correctly indicate pluralization is the default in https://github.com/StackExchange/Dapper/commit/601a5c28fb39ae8a1f4889dfb65f21f556e27df1 :)
