### ISSUE TITLE
Why Dapper QueryFirst Core DataReader read to end instead of just doing one read

### ISSUE THREAD

**Issue by shps951023** [StackExchange/Dapper#1210]
**Source Code** : [Dapper/SqlMapper.cs at master · StackExchange/Dapper](https://github.com/StackExchange/Dapper/blob/master/Dapper/SqlMapper.cs#L1210)

#### Dapper QueryFirst Core Demo

```C#
using System.Data;
using System.Data.Common;

public static class DapperDemo
{
	public static T QueryFirstOrDefault<T>(this IDbConnection connection,string sql,Func<IDataRecord,T> selector)
	{
		using (var cmd = connection.CreateCommand())
		{
			cmd.CommandText = sql;
			using (var reader = cmd.ExecuteReader(CommandBehavior.SequentialAccess | CommandBehavior.SingleResult | CommandBehavior.SingleRow))
			{
				var data = (reader.Read() && reader.FieldCount != 0) ? selector(reader) : default(T);
				while (reader.Read()) { }
				while (reader.NextResult()) { }
				return data;
			}
		}
	}
}
```

[![enter image description here][1]][1]

Why Dapper QueryFirst Core DataReader read to end instead of just doing one read?

```C#
public static class DapperDemo
{
	public static T QueryFirstOrDefault<T>(this IDbConnection connection,string sql,Func<IDataRecord,T> selector)
	{
		using (var cmd = connection.CreateCommand())
		{
			cmd.CommandText = sql;
			using (var reader = cmd.ExecuteReader(CommandBehavior.SequentialAccess | CommandBehavior.SingleResult | CommandBehavior.SingleRow))
			{
				var data = (reader.Read() && reader.FieldCount != 0) ? selector(reader) : default(T); //Read only one time
				return data;
			}
		}
	}
}
```

  [1]: https://i.stack.imgur.com/IVT20.png

**Comment by mgravell** [comment]
Because in many cases an error can *follow* the results, and if you don't consume the data reader properly by closing prematurely, you can cause a RDBMS error message to be ignored. Since we're including the single hints, this shouldn't actually add any cost in real usage.

**Comment by shps951023** [comment]
> Because in many cases an error can _follow_ the results, and if you don't consume the data reader properly by closing prematurely, you can cause a RDBMS error message to be ignored. Since we're including the single hints, this shouldn't actually add any cost in real usage.

thanks

**Comment by tmasternak** [comment]
@mgravell 

> Because in many cases an error can follow the results, and if you don't consume the data reader properly by closing prematurely, you can cause a RDBMS error message to be ignored. Since we're including the single hints, this shouldn't actually add any cost in real usage.

Unfortunately, there is no documentation (at least I could not find it) that would elaborate on the scenario, and I couldn't find any context in the repository either. Would you be able to share more information on when this could happen? 

More concretely, is it possible to have `SqlDataReader` return false from `ReadAsync` and fail on one of the `ReadNextAsync`? Is it possible to have the connection and transaction operational after executing `ExecuteReader` that had un-read errors in the `SqlDataReader`.

Thank you very much for any insights!

**Comment by mgravell** [comment]
I already discussed the scenario; but imagine SQL that selects some row/rows, then (perhaps after a short delay) causes an error to be sent to the result stream: in that case, if we stop reading *before* consuming the row, it is possible (I've literally seen it) for the error to be omitted. Errors should not usually be ignored, so: Dapper takes steps to *not ignore it*.

Will the connection/transaction still be operable? probably, depending on what exactly the error was; but: you probably don't *want* to commit things if you've just ignored an error...

**Comment by tmasternak** [comment]
@mgravell thank you for the clarification!
