### ISSUE TITLE
Clarify Tracking

### ISSUE THREAD

**Issue by Blastnsmash** [StackExchange/Dapper#1217]
I've read several articles and stackoverflow posts that claim Dapper.Contrib has change tracking when you use an interface. However, it looks like it's simply per row change tracking and not per column change tracking. Is that correct?

In other words:

connection.Update<Car>(new Car() { Id = 1, Name = "Maruti" });

Will translate into (blanket update statement): 

Update Car set id=1, Name="Maruti", OtherProp = @OtherProp, @Otherprop2 = @Otherprop2 where id = @aidmsu 

and it will not translate into (distinct update statement):

Update Car set id=1, Name="Maruti" where id = @aidmsu 

Can someone confirm?

**Comment by JaseRandall** [comment]
Yes, that sounds correct.

Dapper creates an IsDirty property for the object created against the interface.  If a property is changed then the IsDirty property is set to true and when you save the object back into the database, the object is ignored if it's not dirty.

`/// <returns>true if updated, false if not found or not modified (tracked entities)</returns>`

`        public static bool Update<T>(this IDbConnection connection, T entityToUpdate, IDbTransaction transaction = null, int? commandTimeout = null) where T : class `
        
`
            if (entityToUpdate is IProxy proxy && !proxy.IsDirty)
            {
                return false;
            }
`
