### ISSUE TITLE
Update System.Data.SqlClient to 4.6.0

### ISSUE THREAD

**Issue by PureKrome** [StackExchange/Dapper#1228]
Dapper is currently set to using `System.Data.SqlClient` 4.4.0 which doesn't work with `TransactionScope`'s.

e.g.

```
using (var scope = new TransactionScope())
{
    using (var db = new SqlConnection(connectionString))
    {
        var result = db.Query......
    }
}
```
and same goes with `async` which requires the Transaction Flow Options enabled.

This was fixed in _I think_ 4.5.0. but 4.6.0 is now the most recent _stable_

![image](https://user-images.githubusercontent.com/899878/55606482-ac73fd80-57c4-11e9-8c25-9a2691b987ed.png)

This was also mentioned in Issue #1026 .

I'm happy to do a PR - if you are all happy with the update.

NOTE: As mentioned by @NickCraver in [this comment](https://github.com/StackExchange/Dapper/issues/1026#issuecomment-390473120) from that issue, we can of course _manually_ NuGet install the package and we're good to go. But the worry is that, this fix is not obviously known by consumers/developers. When we first try the queries with Dapper (as above) we will get an exception and it's not obvious that the 'fix' is to _manually_ install the more recent version.

So yeah .. this would be a nice fix IMO.

Thoughts, lovely repo org members?

**Comment by mgravell** [comment]
PR added; green lights seem fine locally; PR here is just to sanity-check; we might also want to consider:

- System.Reflection.TypeExtensions (Dapper[.StrongName]) 4.4.0 => 4.5.1
- Microsoft.CSharp (Controb, Rainbow, SqlBuilder) 4.3.0 => 4.5.0
- EntityFramework (Dapper.EntityFramework[.StrongName]) 6.1.3 => 6.2.0
- Microsoft.SqlServer.Types (Dapper.EntityFramework[.StrongName]) 11.0.2 => 14.0.1016.290

**Comment by NickCraver** [comment]
EF 6.2 specifically has some regressions (e.g. breaks MiniProfiler in some cases) that won't be released until 6.3...though they've been fixed in source for 18 months :( - I wouldn't require stuff here unless we know them to be fixes for something big we expect to work.

**Comment by PureKrome** [comment]
Thank you kindly, awesome repo members!

![](https://media.giphy.com/media/Yj7W2XmLSyiEGSPLTQ/giphy.gif)

**Comment by mgravell** [comment]
1.60.9 isn't listed, but: it exists, and contains this change; I need to do a pass to see what else we should squeeze in to a "listed" deploy...
