### ISSUE TITLE
QuerySingleOrDefault throws NullReferenceException on NULL return

### ISSUE THREAD

**Issue by tauchmi** [StackExchange/Dapper#1269]
Hi,

when calling a user function that returns a Guid or NULL I discovered that SingleOrDefault(Async)<Guid> threw a NullReferenceException. On further investigation this also happens with bool, int, long, etc.

Simple example to reproduce
            

            using (var db = new SqlConnection(""))
            {
                string sql = "Select null;";
                db.Open();
                var result = db.QuerySingleOrDefault<Guid>(sql);
                Console.WriteLine(result);
            }

The error occurs on casting NULL to the type (SqlMapper.cs line 1202, SqlMapper.Async line 503)

Is this expected behavior?

**Comment by NickCraver** [comment]
This is expected, since you're trying to select `null` into something that's a not-nullable value type. If you intend to accept `null`, you should use `.QuerySingleOrDefault<Guid?>` instead, where `null` is validly converted to the `Nullable<Guid>`.

**Comment by tauchmi** [comment]
The name of the method was misleading for me then, I expected it to return the default(Guid) instead in case of a null value. Thank you for your feedback.

**Comment by szmcdull** [comment]
`await conn.QuerySingleOrDefaultAsync<int>("SELECT MAX(trade_id) FROM trades WHERE currency_id = 132 AND currency_trade_id = 104");`
This is also throws NullReferenceException. I was expecting this returns 0:(
