### ISSUE TITLE
Dapper.Contrib Insert or Update Type error,Cant not find table name

### ISSUE THREAD

**Issue by JiangJiaqi90** [StackExchange/Dapper#1274]
if I use a supper class in this method
![image](https://user-images.githubusercontent.com/44488028/59185683-a115c780-8ba3-11e9-85f0-d6a2520120c8.png)
it cant not find the right table name. when i change the code in line 414 var type = typeof(T) to var type = entityToInsert.GetType(); it can find the right table name.

**Comment by starskythehutch** [comment]
Is this still an issue? Do you have steps to reproduce the problem?

**Comment by NickCraver** [comment]
Without code to repro the problem - we'll be unable to help here. If you have a repro, we'd be able to say what needs some love here.
