### ISSUE TITLE
Issue with ExecuteReaderAsync on MySQL

### ISSUE THREAD

**Issue by walkindude** [StackExchange/Dapper#1277]
**Dapper version:** 1.60.6
**Target framework version:** .NET 4.7
**MySQL version:** 5.6.22
**MySql.Data version:** 8.0.16

Code:

        public async Task<DataTable> GetDataTable(string sql, object parameters = null)
        {
            using (var conn = await GetConnection())
            using (var reader = conn.ExecuteReader(sql, parameters))
            {
                var table = new DataTable();
                table.Load(reader);
                return table;
            }
        }

(I'm using Dapper just to take advantage of its parameter handling, since it's so well designed). 

With the same simple SELECT, the code above works as intended.

The code below, however, unless I'm doing something horribly wrong or stupid, does not:

        public async Task<DataTable> GetDataTable(string sql, object parameters = null)
        {
            using (var conn = await GetConnection())
            using (var reader = await conn.ExecuteReaderAsync(sql, parameters))
            {
                var table = new DataTable();
                table.Load(reader);
                return table;
            }
        }

The only difference is that in the latter I'm using `ExecuteReaderAsync` instead of `ExecuteReader`.

The `DataTable` that gets returned is completely empty: no columns, no rows, no nothing. I can't quite figure out why. Using the non-async version, as I said, works as expected.

Right now I can't try this on either Postgres or SQL Server or even a more recent version of MySql, so I can't tell whether it happens with other database engines as well.

Using the non-async version is no big deal, I'm doing this for a tiny internal utility and it's not a deal breaker, I just thought I would point this out.

EDIT: I'm adding a screenshot of the debugger with the cursor hovering over the `DataReader` just in case it's helpful.

![Debugger](https://i.imgur.com/pEodETt.png)

**Comment by mgravell** [comment]
That is very curious; I've tested with SqlClient (for convenience, since I always have that available locally) and it works fine there, so I *suspect* that this is something specific to the MySql implementation. However, in testing, I notice that there *is* one completely brain-dead issue (my fault) that might be causing it.

Question: was the connection passed in *open*? or *closed*? (it *should* work with either, but I think I can see a fun way it can fail in the latter case)

**Comment by mgravell** [comment]
(hmmm; actually, no, the thing I thought was a problem: probably isn't)

**Comment by mgravell** [comment]
a very common problem with readers and the debugger is the IDE "helpfully" enumerating the data to display it to the developer - a consequence of which being that the IDE ends up burning the reader. Are you *absolutely sure* that this isn't just the IDE / debugger ruining it for you ?

**Comment by mgravell** [comment]
OK, I think I understand now; I will prepare what I think the fix is and release it as an alpha; I think we already fixed this once for the "sync" path, but obviously we didn't do the same for the async

**Comment by walkindude** [comment]
Hello Marc, thanks for your reply. The connection is already open. I have a `GetConnection` method which instantiates a new `MySqlConnection` and opens it before returning.

I just tried running the program outside of the IDE both compiled in Debug and Release configurations, and the sync version works but the async one does not.

**Comment by mgravell** [comment]
This should be fixed in 1.60.12+ - would you be open to validating the change from myget? if so: https://www.myget.org/feed/stackoverflow/package/nuget/Dapper (although the two tests I added based on this issue are coming up green)

**Comment by walkindude** [comment]
Thanks Marc! By all means, I will give it a try as soon as I can, most probably tomorrow.

**Comment by walkindude** [comment]
Hey there. The tests don't lie, I installed v1.60.15 from MyGet and I can confirm it's fixed. Thumbs up from me.

Thank you very much.

**Comment by mgravell** [comment]
Great. I want to do another sweep of the inbound PR list, but : this should be out next nuget drop

**Comment by walkindude** [comment]
Awesome. Thank you very much Marc, and thanks to everybody involved with this library.

**Comment by MaceWindu** [comment]
BTW, MySql.Data fakes async operations using synchronous execution, so it doesn't make much sense to use async API for this provider. You should consider MySqlConnector if you need async support.

**Comment by walkindude** [comment]
Oh thanks, I didn't know! Luckily I rarely have to work with MySQL anymore, in this instance I used it just because I had to pull some data from a legacy database.

That's good to know, though.
