### ISSUE TITLE
How to change name of parameter at the last moment before running a query?

### ISSUE THREAD

**Issue by Larry57** [StackExchange/Dapper#1281]
Is there a way to modify the names of the query parameters at the last minute, using an event or other, for example, to add a prefix?

Our need is to add "p_" before each parameter name to respect an Oracle convention, just as Dapper seems to add the "@" of SQLServer parameters automatically.

Our application runs on SQLServer with only stored procedures, and we need to make it compatible with Oracle, without having to rewrite all calls to the database.

Thank you for your help.

**Comment by mgravell** [comment]
Hmmm. No, this isn't something that is built in currently, and it would need somet thought.

Speaking for the core lib only: we don't add the `@` - that is inferred by the provider. Not sure if rainbow etc do anything different there.

**Comment by Larry57** [comment]
Well I used a workaround that consists in wrapping the anonymous classes that contain the parameters in a function that builds a DynamicParameters object with the names correctly prefixed. Although it seems a little less effective, it works very well. Thanks anyway Marc.

**Comment by NickCraver** [comment]
In this case, I think the already taken route is probably the correct one - closing out to cleanup.
