### ISSUE TITLE
[sqlite]Error parsing column 8 (X=0 - Int64)

### ISSUE THREAD

**Issue by akaylh** [StackExchange/Dapper#1285]
I have query,the result is :
![image](https://user-images.githubusercontent.com/437330/59814647-a6fc6d00-9348-11e9-9c72-b35e631eca8d.png)

use `dapper 1.60.1` and` microsoft.data.sqlite.core 2.2.3`, my application report :

```
---- System.Data.DataException : Error parsing column 8 (IS_SEARCH=0 - Int64)
-------- System.InvalidCastException : Unable to cast object of type 'System.Int64' to type 'System.Int32'.
```

these filed is interger in sqlite, my class like this:

```
public class T
{

        public int IsList { get; set; }
        public int IsAdd { get; set; }
        public int IsEdit { get; set; }
        public int IsSearch { get; set; }
        public int IsMany { get; set; }
}
```
when change `int` to `int?` or `int` to `long?` still  not working 。

If change the provider to `System.Data.SQLite.Core` is working fine.

**Comment by kelvindules** [comment]
> Unable to cast object of type 'System.Int64' to type 'System.Int32'

Sqlite is weird with INTEGER. 
From what I can see, when your column value is null, Sqlite returns it as a `long/Int64 (8 bytes)` so you should have a `long` property to map to, not an `int/Int32 (4 bytes)`.
```c#
public long IsSearch { get; set; }
```
Theres is no need to make it nullable unless you need nulls. 
When querying a null column value to a non-nullable type, you'll get it's `default`, in this case 0.

**Comment by akaylh** [comment]
@kelvindules  `long` property also test, bug  still not working..

**Comment by kelvindules** [comment]
@akaylh This looks like #524 . Try casting it as bigint
```sql
select cast(Is_Search as bigint) from table
```
Not sure if that is already addressed.

**Comment by akaylh** [comment]
@kelvindules thank you very much.
