### ISSUE TITLE
NETFramework 4.5.1 TLS 1.2 not default protocol

### ISSUE THREAD

**Issue by tienfahsu** [StackExchange/Dapper#1286]
NETFramework 4.5.1 TLS 1.2 not default protocol

**Comment by mgravell** [comment]
I'm a little late here, but: can you provide more words here? How does this manifest? Is this a problem specific to Dapper? Since Dapper doesn't have anything to do with TLS, I'm not quite sure what Dapper can do here, but a specific example of what problem you're seeing would go a long way.

**Comment by f1ana** [comment]
TLS 1.2 is only the default in .NET 4.6.2 and onward- nothing specific to Dapper here.

**Comment by NickCraver** [comment]
Closing this out as it isn't a Dapper issue - that's a process-level issue. You're likely looking to adjust https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.securityprotocol?view=netframework-4.5.2 :)
