### ISSUE TITLE
decimal  precision changed

### ISSUE THREAD

**Issue by flybalance** [StackExchange/Dapper#1288]
When I use dapper to extract the result set from the database and map it to the List set, the data precision of the attribute of decimal type defined in the entity object has changed. Is there a way to set the fixed precision?

create table tableName
(
  mount        NUMBER(30,3)
)

 public class CheckCustomerIndex
 {
        public decimal Mount { get; set; }
 }

![image](https://user-images.githubusercontent.com/16532116/60225884-4676ae00-98bb-11e9-8155-fee3c6b5eae2.png)

![image](https://user-images.githubusercontent.com/16532116/60225931-89388600-98bb-11e9-9383-05cf46168e77.png)

I use the Oracle database and the dapper version is 1.60.6

**Comment by mgravell** [comment]
Mostly dapper is just getting the value from ado.net; I don't even know if
ado.net tells us the quoted precision - it just does GetValue or similar.
So : without a lot of work, "no".
