### ISSUE TITLE
I want to add this to Dapper, and I hope the authorities will support and maintain it.

### ISSUE THREAD

**Issue by 1448376744** [StackExchange/Dapper#1291]
https://github.com/1448376744/Dapper.Common
https://www.cnblogs.com/chaeyeon/p/11028480.html

**Comment by mgravell** [comment]
Simple answer: "no".

Every project needs a reasonable level of scope and definition. I do not wish to expand Dapper's scope to include that, nor do I desire the additional maintenance burden. If you think that it has a place as additional extensions: then great, I wish you the absolute best of luck with that project. 

However, I *would* ask that you choose a name other than "Dapper.Common". The name "Dapper.Common" suggests something that is "core" to Dapper, i.e. some shared core or official feature. This isn't the case. A good thing to include in a name would be something that describes what extra feature / scenario is unique or special about your library. "Common"... doesn't tell me that.
