### ISSUE TITLE
Global.json is causing projects to fail to load in VS unless I install an older SDK

### ISSUE THREAD

**Issue by jnm2** [StackExchange/Dapper#1294]
I have 2.2.301 installed. For now, I'm just locally deleting the global.json file because it's less of a pain than going out and downloading 2.2.2xx and having to uninstall it later.

https://github.com/StackExchange/Dapper/blob/8b49eb691dd4eaca6d80993130ca8a3d88455111/global.json#L2-L6

**Comment by mgravell** [comment]
We'll be updating this to 3.0 when RTM ships, but ultimately: global.json here is intended for the convenience of the primary maintainers and the build chain - if people are self-building, *that's fine*, but they need to either have the same build chain, or make whatever changes are necessary; what we *support* is the nupkg. I've updated this to preview9 for now.

**Comment by mgravell** [comment]
(note to self: I've probably just hosed our CI server)

**Comment by NickCraver** [comment]
@jnm2 Yep, that's exactly the format I have in mind as well

**Comment by NickCraver** [comment]
This was fixed in 4ad80f880eddd20885d515068a4ba1f1a930a90c - so closing this out :)
