### ISSUE TITLE
Security Risk: When initializing the database connection, the connection string is logged which will display database user name and password in the log file

### ISSUE THREAD

**Issue by OmnicellMike** [StackExchange/Dapper#1300]
There is a big security risk when initializing.  The constructor allows for the database connect string to connect to the database.  When the connection to SQL is successful it logs the connection string which can contain the database user name and password.  If the password exists in the connection string is should not be added to the logging or at least don't display that actual password in the log.

**Comment by mgravell** [comment]
Which constructor, exactly? Which API are we talking about here?

**Comment by OmnicellMike** [comment]
issue is in an extension of this app
