### ISSUE TITLE
Dapper's unfriendly support for anonymous types bothers me.

### ISSUE THREAD

**Issue by 1448376744** [StackExchange/Dapper#1304]
A parameterless default constructor or one matching signature (System.Int32 Pid, System.Int64 Count) is required for <>f__AnonymousType0`2[[System.Nullable`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] materialization

**Comment by mgravell** [comment]
You actively need to go out of your way to use anonymous types with dapper, so I don't imagine this will be a common scenario, but: do you have an illustration of your usage here (and the anonymous signature), so we can consider? Note: dapper *does* work with value-tuples (positional, not by name), and frankly I would suggest: use value-tuples for things that are locally scoped and don't need formal type definitions. Usage is very simple:

``` c#
var data = conn.Query<(int id, string name)>(...).AsList();
```

**Comment by 1448376744** [comment]
> 
> 
> You actively need to go out of your way to use anonymous types with dapper, so I don't imagine this will be a common scenario, but: do you have an illustration of your usage here (and the anonymous signature), so we can consider? Note: dapper _does_ work with value-tuples (positional, not by name), and frankly I would suggest: use value-tuples for things that are locally scoped and don't need formal type definitions. Usage is very simple:
> 
> ```cs
> var data = conn.Query<(int id, string name)>(...).AsList();
> ```
I wrote an extension based on dapper, open source in github, because based on LINQ grammar, anonymous types are very important, you can see it
https://github.com/1448376744/Dapper.Common

**Comment by 1448376744** [comment]
> 
> 
> You actively need to go out of your way to use anonymous types with dapper, so I don't imagine this will be a common scenario, but: do you have an illustration of your usage here (and the anonymous signature), so we can consider? Note: dapper _does_ work with value-tuples (positional, not by name), and frankly I would suggest: use value-tuples for things that are locally scoped and don't need formal type definitions. Usage is very simple:
> 
> ```cs
> var data = conn.Query<(int id, string name)>(...).AsList();
> ```
Example:
DbContext.From<Student>()
.Select(s=>new 
{
s.Id,//(dbtype:int,CsharpType int)
s.IsDelete//(dbtype:bit(1),CsharpType bool)
})

**Comment by 1448376744** [comment]
DbContext.From（）.Select（
s => new 
{ 
s.Id，//（dbtype：int，CsharpType int）
s.IsDelete //（dbtype：bit（1），CsharpType bool）
}）This throws an exception.

**Comment by 1448376744** [comment]
> 你主动需要尽量使用带有精巧的匿名类型，所以我不认为这将是一个常见的场景，但是：你在这里有一个你的用法说明（和匿名签名），所以我们可以考虑？注意：dapper _确实_可以使用value-tuples（位置，而不是名称），坦率地说我建议：对于本地作用域的东西使用value-tuples并且不需要正式的类型定义。用法很简单：
> 
> ```cs
> var  data  =  conn。查询 <（int  id，string  name）>（...）。AsList（）;
> ```

example
 public static IEnumerable<TResult> Query<TResult>(TResult func, string sql)
 {
     return connection.Query<TResult>(sql);
 }
I think anonymous types are very useful.

**Comment by 1448376744** [comment]
> 
> 
> You actively need to go out of your way to use anonymous types with dapper, so I don't imagine this will be a common scenario, but: do you have an illustration of your usage here (and the anonymous signature), so we can consider? Note: dapper _does_ work with value-tuples (positional, not by name), and frankly I would suggest: use value-tuples for things that are locally scoped and don't need formal type definitions. Usage is very simple:
> 
> ```cs
> var data = conn.Query<(int id, string name)>(...).AsList();
> ```

example
 public static IEnumerable<TResult> Query<TResult>(Func<TResult> func, string sql)
 {
     return connection.Query<TResult>(sql);
 }
I think anonymous types are very useful.

**Comment by 1448376744** [comment]
Example
public IEnumerable<TResult> Query<TResult>（Func<TResult> func,string sql）
{
         return connection.Query<TResult>(sql);
}
I think anonymous types are very useful.

**Comment by 1448376744** [comment]
All of this causes the dapper to fail to find a matching constructor of anonymous type, thus throwing an exception. Anonymous types greatly simplify the code and facilitate programming. For example, I need to query some fields of a type. I return an anonymous type of this class through func, but dapper can't support it very well.

**Comment by mgravell** [comment]
Ok, can I distill this down for clarity? Is this a correct re-statement?

1. You believe there are valid use-cases for anonymous types with Dapper, in particular via LINQ-style projections
2. Currently Dapper doesn't work well with this scenario, citing constructor issues
3. You'd like it to work better

?

**Comment by 1448376744** [comment]
Yes, I hope Dapper can do better and better.




------------------ 原始邮件 ------------------
发件人: "Marc Gravell"<notifications@github.com>; 
发送时间: 2019年8月11日(星期天) 凌晨2:45
收件人: "StackExchange/Dapper"<Dapper@noreply.github.com>; 
抄送: "花间岛"<1448376744@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [StackExchange/Dapper] Dapper's unfriendly support for anonymoustypes bothers me. (#1304)




Ok, can I distill this down for clarity? Is this a correct re-statement?
  
You believe there are valid use-cases for anonymous types with Dapper, in particular via LINQ-style projections
 
Currently Dapper doesn't work well with this scenario, citing constructor issues
 
You'd like it to work better
  
?
 
&mdash;

**Comment by jogibear9988** [comment]
@1448376744 if you use linq, why don't you try a orm has linq and anonymous types support like ef.core or linq2db?

**Comment by NickCraver** [comment]
Closing this in favor of #1305 to discuss in one place.
