### ISSUE TITLE
Updating a nullable DateTime value fails with error

### ISSUE THREAD

**Issue by scgough** [StackExchange/Dapper#1310]
Hi,
I have a weird issue that I've not faced before...I'm adding to a working system and for some reason updating a record with a DateTime value gives an error. Details below...

Here is my sample code:

```
myObject.Id = 1;
myObject.updatedDate = DateTime.UtcNow;
int count = await conn.UpdateAsync<MyObjectType>(myObject);
```
this gives an error: 
`Conversion failed when converting date and/or time from character string.`

Notes:
`updatedDate` is a `DateTme?` in my model and a `datetime2(7)` (NULLABLE) in the database.
there is another DateTime (non-nullable) in my model that is passing back the existing value. 

- .NET Core 2.1
- SQL Server (Azure)
- Dapper v1.60.6
- Dapper.SimpleCRUD.NetCore 1.0.0

**Update - Test without SimpleCRUD**

The same thing happens in the following scenario (just Dapper, no SimpleCRUD):

```
string cmdUpd = @"UPDATE MyTable SET updatedDate = GETUTCDATE() WHERE Id = @id";
int c = await conn.ExecuteAsync(cmdUpd, new
                            {
                                id = myObject.Id
                            });
```

**Comment by mrgchr** [comment]
Hi,

Not reproduced in my environment.
How about using `SYSUTCDATETIME()` instead of `GETUTCDATE()` in your `update` section code?
`SYSUTCDATETIME()` returns `datetime2` (as well as your `updatedDate` field).

**Comment by scgough** [comment]
I've not had this issue since...I'm not certain why it was happening. 
For now I will close this issue.
