### ISSUE TITLE
Dynamic WebForm compilation issue with Dapper 2.0.4

### ISSUE THREAD

**Issue by fredericDelaporte** [StackExchange/Dapper#1320]
Use case: an aspx Web application dynamically compiled. It does use a csproj, but has been setup for dynamically compiling the code behind. So mainly source is deployed on the web server, along with dependencies assemblies.

This was running fine with Dapper 1.60.6.
With Dapper 2.0.4, the Web site fails starting with a compilation error:
```
CS0012: The type 'Object' is defined in an assembly that is not referenced.
You must add a reference to assembly
'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

It may be another type than `Object`, like `IEnumerable`. This happens when using any Dapper type.

Adding that reference into the web.config solves the trouble.

```xml
    <compilation debug="true" targetFramework="4.7.2">
      <assemblies>
        ...
        <add assembly="netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" />
      </assemblies>
    </compilation>
```

I would rather not have to do that. Anyway, I understand you may not be willing to go back to adding a .Net Framework target into your release, in order to avoid that corner case trouble. But maybe you should add a possible breaking change note into your release notes.

In case you would like to repro the issue and need instructions for dynamically compiling webforms into a web application, here is how to convert a regular WebForm added into an Asp.Net project into a dynamically compiled one:
- Delete the designer.cs dependent file.
- Change the `Build Action` of the aspx.cs dependent file to `Content`.
- Change in the aspx file the `Page` directive `CodeBehind` attribute name to `CodeFile`.
- Have your project referencing the NuGet package Microsoft.CodeDom.Providers.DotNetCompilerPlatform
- Under the `configuration` node of the web.config, ensure you have:
```xml
  <system.codedom>
    <compilers>
      <compiler language="c#;cs;csharp" extension=".cs" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=2.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:default /nowarn:1659;1699;1701" />
      <compiler language="vb;vbs;visualbasic;vbscript" extension=".vb" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.VBCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=2.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:default /nowarn:41008 /define:_MYTYPE=\&quot;Web\&quot; /optionInfer+" />
    </compilers>
  </system.codedom>
```

**Comment by mgravell** [comment]
the next build adds back net461 as a target; this *should* fix this. If web-forms needs something prior to net461, all I can say is: stay on 1.*
