### ISSUE TITLE
'Error parsing column 0' when trying to use string as UNIQUEIDENTIFIER column parameter

### ISSUE THREAD

**Issue by RestoreMonarchy** [StackExchange/Dapper#1321]
I'm using ASP.NET Core 2.2 and Postman to test API.

I try to query ProductOwned from database using Dapper, but if I use string `token.SecretKey` as CustomerSecretID it fails (I also tried using `new Guid(token.SecretKey`).

When I execute the query below inside database it works (the GUID is the same in API request too).

```sql
SELECT p.*, c.* FROM dbo.ProductsOwned as p INNER JOIN dbo.Customers AS c ON p.CustomerSecretID = c.CustomerSecretID WHERE p.CustomerSecretID = '913DE5A3-EAD5-4F61-81CE-1225F292B271' AND p.PluginId = 1;
```

![https://i.imgur.com/h2BikR7.png](https://i.imgur.com/h2BikR7.png)

I believe that this is a Dapper issue.

**Comment by visualsanity** [comment]
Google is your friend. 

[https://docs.microsoft.com/en-us/dotnet/api/system.iconvertible?view=netframework-4.8](https://docs.microsoft.com/en-us/dotnet/api/system.iconvertible?view=netframework-4.8)

**Comment by RestoreMonarchy** [comment]
Sorry my bad I had a property in `ProductOwned` type CustomerSecretID as string instead of Guid
