### ISSUE TITLE
Can't update to Dapper-2.0.4 with Visual Studio 2015

### ISSUE THREAD

**Issue by nhathongly** [StackExchange/Dapper#1325]
We are stuck with Visual Studio 2015 due to the license. Dapper-2.0.4 only targets to .net standard 2.0, so that we can't update it in our projects. Could you please support it to run on .Net Framework 4.6.1?

**Comment by mgravell** [comment]
Well, the good news is that the old version will continue to work. It isn't realistic to promise eternal support on old platforms, but let me.have some conversations here about minimum versions. Net461 is pretty much the minimum I'd be willing to look at.

I'm morbidly curious, though - but maybe it is an irrelevant tangent - I'm not aware of any major license changes between VS2015 and later. I doubt it is key here, but if you have more details on that I'm curious :)

**Comment by mgravell** [comment]
I've reinstated the net461 TFM; whether that works in VS2015 is another question...

**Comment by nhathongly** [comment]
> Well, the good news is that the old version will continue to work. It isn't realistic to promise eternal support on old platforms, but let me.have some conversations here about minimum versions. Net461 is pretty much the minimum I'd be willing to look at.
> 
> I'm morbidly curious, though - but maybe it is an irrelevant tangent - I'm not aware of any major license changes between VS2015 and later. I doubt it is key here, but if you have more details on that I'm curious :)

I'm working in a company which has more than 150 developers. We are not allowed to use VS2017 Community, and it costs us a lot to upgrade VS2015 PRO to VS2017 PRO for all developers, as what I'm told
