### ISSUE TITLE
Latest version is 2.0.30? 

### ISSUE THREAD

**Issue by sextondjc** [StackExchange/Dapper#1341]
Latest version on Nuget is 2.0.30 - is that intentional? 
It may well be. Just looks weird in reverse chronological order

2.0.30
2.0.4
1.60.6
... etc. 

https://www.nuget.org/packages/Dapper/

**Comment by sextondjc** [comment]
Looks like it's related to [this](https://github.com/StackExchange/Dapper/issues/1332) issue and is indeed intentional.

**Comment by mgravell** [comment]
I don't understand the "order" thing. That looks perfectly semver to me. Can you elaborate?

**Comment by sextondjc** [comment]
Mostly me being an idiot. I've got a flu and should probably be sleeping. 

I think it's the .30 that got me. Had it been .29 or .31 (or basically anything other than ending in a zero) it would've been more obvious to me. Coupled with the alignment (number 3 above the number 4) it caught me off guard. 

Feel pretty silly, really.
