### ISSUE TITLE
Npgsql.PostgresException (0x80004005): 42P01: \"contentss\"

### ISSUE THREAD

**Issue by aplib** [StackExchange/Dapper#1351]
```
CREATE TABLE IF NOT EXISTS contents
(
  content_id BIGINT PRIMARY KEY CHECK (content_id > 0)
);

public class contents
{
  public long content_id { get; set; }
}
...
conn.Insert(new contents() { content_id = 111 });
```

 "42P01: отношение \"contents**s**\" не существует"
also: \"content_to_reindexs\"
I propose to check the existence of the Table with the fully corresponding name.

**Comment by mrgchr** [comment]
It does not looks `Dapper`'s issue to me.
I recommend you checking ` Npgsql`'s repository.

The error code is defined following:

https://github.com/npgsql/npgsql/blob/master/src/Npgsql/PostgresErrorCodes.cs#L320

**Comment by mrgchr** [comment]
Are you using `Dapper.Contrib` by chance?

Your class does not have `TableAttribute`, plural "s" could be added. I guess.

https://github.com/StackExchange/Dapper/blob/master/Dapper.Contrib/SqlMapperExtensions.cs#L299
