### ISSUE TITLE
AsTableValuedParameter does not work after version 1.60.6

### ISSUE THREAD

**Issue by Magnus12** [StackExchange/Dapper#1352]
using `AsTableValuedParameter` on a data-table after version 1.60.6 does not work. Throws exception: `InvalidCastException` "Failed to convert parameter value from a DataTable to a IEnumerable`1" with inner exception "Object must implement IConvertible."

Downgrading to 1.60.6 solves the problem.

**Comment by mgravell** [comment]
Do you have a repro example that illustrates it failing **in a runnable state**, i.e. something I can literally run here? I've re-run the integration tests I have that use `DataTable` and `AsTableValuedParameter`, and they passed. So: a repro would be really useful.

**Comment by Magnus12** [comment]
After more investigation it seem to happen only with System.Data.SqlClient 4.3.1
I guess since dapper no longer references SqlClient directly anymore we got an older version from elsewhere.

**Comment by mgravell** [comment]
so if you use

``` xml
<PackageReference Include="System.Data.SqlClient" Version="4.7.0" />
```

for example - does it work properly again?

**Comment by Magnus12** [comment]
Yes it does.

**Comment by fadamsen** [comment]
@Magnus12 Thanks a bunch, this just helped me a ton!
