### ISSUE TITLE
Strong-name sign Dapper.* and deprecate Dapper*.StrongName package

### ISSUE THREAD

**Issue by caioproiete** [StackExchange/Dapper#1356]
Given improvements in .NET Core (re: binding redirects) and recent updates to Microsoft's guidance on strong-naming, I'd suggest we strong-name all Dapper assemblies, and retire the `Dapper*.StrongName` packages.

Any objections before I put together a PR?

---

Related links: 

- [Strong Name Signing, dotnet/corefx](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md)
- [Strong naming guidance, docs.microsoft.com](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming)
- [Build great libraries using .NET Standard](https://www.youtube.com/watch?v=hLFyycJVo0I&feature=youtu.be&t=1470)

**Comment by mgravell** [comment]
This is already item number 0 on the 2.0 plan.

It is fundamentally identity breaking, so we want to combine as many breaks into one "round".

**Comment by caioproiete** [comment]
Great! Thanks @mgravell. Just to be clear, when you say `2.0` plan, you mean a `2.x` release (minor bump) considering we're on `2.0.30` as of this writing? Or do you actually mean `3.0`?

PR to `master`, or is there a more suited branch where these breaking changes are being merged to?

**Comment by NickCraver** [comment]
3.0 is correct - No need for a PR, when we get a chance to spike on 3.x work, we'll be taking care of this as it's at the start of it. Normally we love PRs for helping along, but in this case it's destroying the other project, changing builds, etc. which is quire disruptive to _other_ PRs and is a maintenance burden until we're ready (or not merge-able when we are)...rest assured this will be done :) We did the same with StackExchange.Redis when it crossed the 2.0 release.

**Comment by caioproiete** [comment]
Thanks @NickCraver

**Comment by mgravell** [comment]
My bad: 2.* was a small break, meaning *technically* it was a breaking
change, but it was unlikely to impact many folks - but worthy of a semver
bump anyways. 3.* Is the big (and pending) bump.

**Comment by rogerreynolds** [comment]
Is this ever going to happen?

Dapper.StrongName is fine, but there are a multitude of extension type packages out there that reference Dapper (not Dapper.StrongName) and if trying to use one of those we get conflicts about classes existing in multiple assemblies.

Please, just make Dapper strong named as was indicated intended for 2.0
