### ISSUE TITLE
0 null values in Query<T>using the built-in function

### ISSUE THREAD

**Issue by aplib** [StackExchange/Dapper#1359]
``` c#
var dbrs = conn.Query<IMDBR>("SELECT IncomingMessage(@chat_id, @user_id, @msg_id)");
```

result: all values is '0'

``` c#
var dbrs = conn.Query("SELECT IncomingMessage(@chat_id, @user_id, @msg_id)");
```

dinamic result: all values, Ok

in Query Tool resul of function normal table all values are valid.

Why does the mapping not work with `Query<T>`? All column names match. types `BIGINT` \<-\> `long`

(edited by mgravell for markdown clarity)

**Comment by mgravell** [comment]
can you give me more context here? what would I need to repro this? What does `IMDBR` look like? what does `IncomingMessage` return? A repro would *really help*.

**Comment by mgravell** [comment]
To show what I mean, here is a working example using SQL Server with an inline table UDF:

``` c#
using Dapper;
using System;
using System.Data.SqlClient;
using System.Linq;

static class P
{
    static void Main()
    {
        using var conn = new SqlConnection("Server=.;Database=testdb;Integrated Security=SSPI;");
        try { conn.Execute(@"drop function dbo.SomeUdf"); } catch { } // for re-run purposes
        conn.Execute(@"create function dbo.SomeUDF(@x bigint)
returns table as
return (select @x + 1 as Foo, @x - 1 as Bar)");

        // use it
        var row = conn.Query<IMDBR>("select * from dbo.SomeUdf(@val)", new { val = 42 }).Single();
        Console.WriteLine(row.Foo); // 43
        Console.WriteLine(row.Bar); // 41
    }
    class IMDBR
    {
        public long Foo { get; set; }
        public long Bar { get; set; }
    }
}
```

which works as anticipated. So: what do I need in order to see what you're seeing?

(note: I don't know whether `IncomingMessage` is an inbuilt feature of your specific RDBMS; I don't even know what RDBMS you are using, let alone what shape it returns)

**Comment by aplib** [comment]
Sorry, I was wrong. This was the wrong syntax for SQL queries.
