### ISSUE TITLE
dapper-tutorial wording clarification

### ISSUE THREAD

**Issue by yetanotherlogonfail** [StackExchange/Dapper#1364]
https://dapper-tutorial.net/async#executeasync

"We only added non-asynchronous version in this tutorial to make it easier to read."

yet below follows all Async methods is this correct ?

ExecuteAsync
QueryAsync
QueryFirstAsync
QueryFirstOrDefaultAsync
QuerySingleAsync
QuerySingleOrDefaultAsync
QueryMultipleAsync

**Comment by mgravell** [comment]
That website is nothing to do with us in any way, and we cannot offer
support on it.

If you can clarify the underlying question here in a self-contained way,
then we can probably help.
