### ISSUE TITLE
Error: data value could not be converted

### ISSUE THREAD

**Issue by kidmar** [StackExchange/Dapper#1365]
Hi
I'm trying to retrieve data from a DB using Dapper.
I'm connecting to the Sybase Sql Anywhere 16 database using OLEDB.
I'm trying to run a simple "SELECT *" query from a table, but Dapper throws an exception:

`using (var conn = new OleDbConnection(_connectionString))
{
    ret = conn.Query(sql);
}`

`{"ClassName":"System.InvalidCastException","Message":"The data value could not be converted for reasons other than sign mismatch or data overflow. For example, the data was corrupted in the data store but the row was still retrievable.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Data.OleDb.ColumnBinding.Value()\r\n   at System.Data.OleDb.OleDbDataReader.GetValue(Int32 ordinal)\r\n   at Dapper.SqlMapper.<>c__DisplayClass169_0.<GetDapperRowDeserializer>b__0(IDataReader r) in C:\\projects\\dapper\\Dapper\\SqlMapper.cs:line 1853\r\n   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in C:\\projects\\dapper\\Dapper\\SqlMapper.cs:line 1098\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\\projects\\dapper\\Dapper\\SqlMapper.cs:line 721\r\n   at Dapper.SqlMapper.Query(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\\projects\\dapper\\Dapper\\SqlMapper.cs:line 648\r\n   at OLEDB.DBManager.DBManager.Retrieve() in C:\\Repo\\Gulliver\\OLEDB\\DBManager\\DBManager.cs:line 77\r\n   at PopulateLogs.Program.Main(String[] args) in C:\\Repo\\Gulliver\\PopulateLogs\\Program.cs:line 21","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2147467262,"Source":"System.Data.OleDb","WatsonBuckets":null}`

The column is of Time data type.
Probably SQL Anywhere database has defined Time datatype in a way that Dapper does not recognize it.

**Comment by mgravell** [comment]
Question: if you were using Sybase directly (via ADO.NET): how would you
have accessed the values (for comparison). What I mean is: Dapper is using
GetValue(int ordinal) here. What does Sybase want you to use instead?

**Comment by kidmar** [comment]
I made some more tests and I found that it was a bug in the OLEDB Sybase driver. Using ODBC for connection works well.
So this has nothing to do with Dapper.
Thank you for the help!
