### ISSUE TITLE
Dapper.Contrib inconsistent id field quoting with PostgreSQL

### ISSUE THREAD

**Issue by ryan-todd** [StackExchange/Dapper#1395]
With PostgreSQL, the manner in which a key property name is quoted is inconsistent between the `Update`/`Delete` and `Get`/`Insert` methods, causing either `Update` and `Delete`, or `Get` and `Insert` to potentially fail depending on database configuration.

`Update` and `Delete` use `PostgresAdapter.AppendColumnNameEqualsValue` when appending the key field to sql, which puts `"` around the field as expected:
https://github.com/StackExchange/Dapper/blob/981cfe4ddfde421b9d572d8f5c2cda259be20a65/Dapper.Contrib/SqlMapperExtensions.cs#L1039

However, `Get` and `Insert` fail to put quotes around the key field:
- `Get` inserts the key field into the sql string directly ([link](https://github.com/StackExchange/Dapper/blob/master/Dapper.Contrib/SqlMapperExtensions.cs#L179))
- `Insert` calls `PostgresAdapter.Insert` which fails to include quotes as part of the `RETURNING` sql ([link](https://github.com/StackExchange/Dapper/blob/master/Dapper.Contrib/SqlMapperExtensions.cs#L1004))

The result of this is if the id property is not all lower-case (both in the .NET class and in Postgres), then either `Get` and `Insert`, or `Update` and `Delete` will fail, because Postgres is case sensitive and will automatically transform any column identifier to lower-case unless it is wrapped in double quotes. E.g.:
- if the key field is `ID` in .NET and `ID` in Postgres, `Get` and `Insert` will fail because Postgres will automatically transform `ID` to `id`, as it is not enclosed in double quotes
- if the key field is `ID` in .NET and `id` in Postgres, `Update` and `Delete` will fail because Postgres won't automatically transform `"ID"` to lower-case because it is enclosed in double quotes

A solution for this would be:
- `Get` should append the ID field with an adapter-specific call much like `Update` and `Delete` call `ISqlAdapter.AppendColumnNameEqualsValue`
- `PostgresAdapter.Insert` should use double quotes when appending the key field to the sql StringBuilder

**Comment by icambron** [comment]
I got hit by this too. I think the right fix for `Insert` is to use `AppendColumnName()`, though

https://github.com/StackExchange/Dapper/blob/981cfe4ddfde421b9d572d8f5c2cda259be20a65/Dapper.Contrib/SqlMapperExtensions.cs#L1027

Also important to get `InsertAsync`, which also has this problem.

**Comment by ryan-todd** [comment]
I agree - switched to use `AppendColumnName()` instead and also applied the same changes to `SqlMapperExtensions.Async`.

**Comment by NickCraver** [comment]
This is something we'll be changing in #722 to allow more configuration in v3 - we can't change it before then because it'll break existing users. The only real option here is _to offer an option_. Please watch #722! I'm going to try and brain dump the current v3 planning thoughts soon so that we can get discussion and get a good design going to support these and other gaps :)
