### ISSUE TITLE
ExecuteScalar return OUTPUT INSERTED.Id ，Is it possible to？

### ISSUE THREAD

**Issue by tkggusraqk** [StackExchange/Dapper#1398]
--Id Type Guid 

``` c#
var sql="inster into table (xxx,xxx) OUTPUT INSERTED.Id value(xxx,xxx)";

var rowId=SqlMapper.ExecuteScalar<Guid>(sql);
```

The test results are correct, are there any potential problems with this?

**Comment by mgravell** [comment]
Execute scalar should be fine here; scalar mode in ADO.NET is basically "take the first row, first column, of the first select, and give me that"

**Comment by mgravell** [comment]
Just make sure you're using parameters for the insert, not string concatenation - bit that's for unrelated reasons (injection and plan-cache reuse)

**Comment by tkggusraqk** [comment]
@mgravell Thank you！
