### ISSUE TITLE
Implementing Dapper with OData

### ISSUE THREAD

**Issue by TehWardy** [StackExchange/Dapper#1420]
I've been using EF but since every new version breaks more and more functionality i'm getting frustrated and thus i'm looking in to the idea of using dapper instead.

I know this is going to require some serious work which i'm happy to take on and if need be share with the community but i'd like some advice on some "complex scenarios" that could make or break the possibility of this coming together.

The first is filters ...

In EF I have a context with multiple properties DbSet<T> and I can "OnModelBuilding" add to the model builder something like ...
```cs
builder.EntityType<T>().HasQueryFilter(t => some condition);
```
... the net result is that "anywhere" in a query where a T would be returned EF will inject this filter logic in to the LINQ expression tree so that when the SQL executes you can apply things like multi-tenancy rules to every table in your db individually and then "stack them" when you build complex queries later.

So my question is ...

Is this sort of thing possible with Dapper, some means to define / apply filters to T's prior to any question about them anywhere in a LINQ expression tree?

...

If not, another I've had round this is to take advantage of the fact that for historical reasons all the relationship based entities are marked as "virtual" so when I map from the dapper query results back to entities if I can intercept the construction of the entity "after it happened, but before it reaches the result set" I can inject a dapper based sub query in to the relationships as the property values for relationship crawls "when they are accessed".

Any thoughts or advice on this would be much appreciated, although I do accept that this is very much a complex as all hell edge case for a Dapper usage.

In theory though, it could be a great win for the framework if I can make it work.

**Comment by mgravell** [comment]
Dapper doesn't offer any form of expression tree parsing and processing.
So: you'd have to implement this part from first principles.

**Comment by TehWardy** [comment]
That explains the claims of Dappers performance at least, not doing that aspect of the "query lifecycle" so to speak must save a ton of execution time.

**Comment by NickCraver** [comment]
Going to close this out as it’s not in the goals of Dapper, but if you pursue this: good luck! And please share with the world :)
