### ISSUE TITLE
Issue with QueryFirstOrDefaultAsync when getting a null from the database into a not nullable field

### ISSUE THREAD

**Issue by Colegreen** [StackExchange/Dapper#1421]
So we recently went through and converted a bunch of our queries form db.Query(...).FirstOrDefault() to db.QueryFirstOrDefaultAsync()

We are running into issues in a few places and tracked it down to QueryFirstOrDefault not working correctly if the response is a null, but the Type expected is not T. Below is a simplified example

`
var result = await connection.QueryFirstOrDefaultAsync<bool>("SELECT null FROM table")
`

Looking at the code I believe the issue is around line 503 in here https://github.com/StackExchange/Dapper/blob/master/Dapper/SqlMapper.Async.cs but I haven't verified. 

More than anything I would like confirmation whether this is working as intended or not. We can work around it by either wrapping it with an isnull or making the type nullable and then getting the default value.

**Comment by NickCraver** [comment]
Trying to solve the confusion here for a few users. In short: yes, it's intentional this goes kaboom. However, we could give better errors here when that unexpected result happens and that's being worked on in #1453.

For your case, you'd want to do the nullable path (that's my usual approach):
```cs
var result = await connection.QueryFirstOrDefaultAsync<bool?>("SELECT null FROM table")
```
