### ISSUE TITLE
Install-Package : NU1108: Cycle detected. 

### ISSUE THREAD

**Issue by starkemc** [StackExchange/Dapper#1423]
I am getting this issue in VS 2019 trying to get Dapper for a new .Net Core 3.1 project on both of my pc's using the package manager and console.   

Install-Package : NU1108: Cycle detected. 
  Dapper -> Dapper (>= 2.0.30).
At line:1 char:1
+ Install-Package Dapper -Version 2.0.30
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'Dapper'.
At line:1 char:1
+ Install-Package Dapper -Version 2.0.30
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by mgravell** [comment]
I can't repro, and Dapper doesn't depend on anything interesting that could
cause a cycle.

Exactly what VS version are you using, and exactly what platform / TFM are
you targeting?

**Comment by starkemc** [comment]
I am using VS19 Community on Windows 10 targeting .Net core 3.1

**Comment by NickCraver** [comment]
This seems like an issue with your environment, possible a commandlet override. What is the output of this?
```ps
(Get-Command Install-Package).dll
```

**Comment by LACanuck** [comment]
Is it possible that your project is named Dapper? I ran into the same issue installing GraphQL into a project called GraphQL. Found in a different forum that this error occurs when package name == project name (case-insensitively)

**Comment by NickCraver** [comment]
Without more info, impossible to diagnose here - closing out to tidy up.

**Comment by Garccosta** [comment]
> Is it possible that your project is named Dapper? I ran into the same issue installing GraphQL into a project called GraphQL. Found in a different forum that this error occurs when package name == project name (case-insensitively)

I was having the same issue, that worked! Thanks a lot mate!
