### ISSUE TITLE
Dapper oracle output parameter from stored procedure

### ISSUE THREAD

**Issue by psiservices-syerneni** [StackExchange/Dapper#1428]
OracleDynamicParameters doesn't return output value?

  var result1 = conn.Query("storedprocedure", param: dyParam, commandType: CommandType.StoredProcedure);

**Comment by mgravell** [comment]
how are you adding and accessing the parameter? `ParameterDirection.Output` and `ParameterDirection.InputOutput` need to specified explicitly; to borrow an example from the test project (where the stored procedure is named `#Issue261`):

``` c#
        [Fact]
        public void Issue261_Decimals()
        {
            var parameters = new DynamicParameters();
            parameters.Add("c", dbType: DbType.Decimal, direction: ParameterDirection.Output, precision: 10, scale: 5);
            connection.Execute("#Issue261", parameters, commandType: CommandType.StoredProcedure);
            var c = parameters.Get<Decimal>("c");
            Assert.Equal(11.884M, c);
        }
```

Any use? or does it still not work?

**Comment by psiservices-syerneni** [comment]
var dyParam = new OracleDynamicParameters();
dyParam.Add("pReturnStatus", OracleDbType.Int32, ParameterDirection.Output, returncode);
 conn.Query(query, dyParam, commandType: CommandType.StoredProcedure);
                       var r = dyParam.Get<int>("pReturnStatus");

Returns 0 most of the time. what am I missing?

**Comment by mgravell** [comment]
Can we see the stored procedure? is it actually a `return` value rather than an `output`? or is it perhaps a `select`? It is much easier to comment with full context

**Comment by psiservices-syerneni** [comment]
Here is the stored procedure

Create ABC.ProcedureName(ss varchar2, ss1 varchar2, pReturnStatus OUT NUMBER) IS
Begin
 
pReturnStatus := 1;

End

**Comment by psiservices-syerneni** [comment]
var r = dyParam.Get<dynamic>("pReturnStatus");      

with the above code I could get rid of error with the conversion of types it doesn't update the database with required information.

![image](https://user-images.githubusercontent.com/46765028/77681307-2287ec00-6f63-11ea-9ee9-a39442010d72.png)

**Comment by psiservices-syerneni** [comment]
This is now resolved. Looks like there is some problem with the storeprocedure that's causing the problem.
