### ISSUE TITLE
When using the multi-mapping APIs ensure you set the splitOn param if you have keys other than Id

### ISSUE THREAD

**Issue by yuzifu** [StackExchange/Dapper#1432]
Hey, everyone!

I used dapper in the project, and one of the queries is as follows:
```
    public class T_Base
    {
        public int ID { get; set; }
        public string Remark { get; set; }
    }

    public class T_ToolType : T_Base
    {
        public string NO { get; set; }
        public string Name { get; set; }
    }

    public class T_Tools : T_Base
    {
        public string NO { get; set; }
        public T_ToolType Type { get; set; }
        public string Name { get; set; }
        public string Spec { get; set; }
        public string Photo { get; set; }
        public int MaxHour { get; set; }
    }

    public class T_ToolBarcode : T_Base
    {
        public string NO { get; set; }
        public string Barcode { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            string connectionString = "Data Source=.\\ToolBox.db";
            using (IDbConnection cnn = new SqliteConnection(connectionString))
            {
                cnn.Open();

                string _sql =
                    @"select *
                         from T_Tools t
                         left join T_ToolType tt on tt.NO = t.TypeNO";

                try
                {
                    var _rtn = cnn.Query<T_Tools, T_ToolType, T_Tools >(
                        _sql, (_tool, _type) =>
                        {
                            _tool.Type = _type;
                            return _tool;
                        });
                }
                catch(Exception err)
                {
                    Console.WriteLine(err.Message);
                }
            }
        }
    }
```

Now I need to add a column 'ExtraCode. This column data is obtained by the table T_ToolBarcode  query, so I changed the query statement to this:
```
...
    public class T_Tools : T_Base
    {
        public string NO { get; set; }
        public T_ToolType Type { get; set; }
        public string Name { get; set; }
        public string Spec { get; set; }
        public string Photo { get; set; }
        public int MaxHour { get; set; }
        public int ExtraCode { get; set; } // this column does not exist in the db, it gets from the table T_ToolBarcode
    }
...
         select t.*,
                   (select count(Barcode) from T_ToolBarcode tb where tb.NO = t.NO) as ExtraCode
         from T_Tools t
         left join T_ToolType tt on tt.NO = t.TypeNO
...
```
this query statement can be execute in db admin tool, But when I running application, dapper throw an exception:
```
When using the multi-mapping APIs ensure you set the splitOn param if you have keys other than Id
```

I tried to add the **SplitOn: "ExtraCode"** to cnn.Query(), but it still reported the same error.

What's wrong with this?

**Comment by mgravell** [comment]
Well, you haven't shown any Dapper usage so it is hard to.say for sure, but if you're using a multi-typed version of Query, it needs to know where you want to stop processing one type and start processing the next. By default it does this by deducing that you want to split at each `Id` column, since that is a common pattern. If that isn't your intent: it needs help. So: where does the second type begin?

**Comment by yuzifu** [comment]
> Well, you haven't shown any Dapper usage so it is hard to.say for sure, but if you're using a multi-typed version of Query, it needs to know where you want to stop processing one type and start processing the next. By default it does this by deducing that you want to split at each `Id` column, since that is a common pattern. If that isn't your intent: it needs help. So: where does the second type begin? If it is all one type: use a single-type query API. Again, if you show your .NET calling code, it will.be easier to comment.

Thanks, I updated the code.

**Comment by yuzifu** [comment]
Problem has been solved.
Because the fields of all tables are not listed in the sql statement, so the sql statement can be changed as follows:
```
select t.*,
           (select count(Barcode) from T_ToolBarcode tb where tb.NO = t.NO) as ExtraCode,
           tt.*
from T_Tools t
left join T_ToolType tt on tt.NO = t.TypeNO
```
