### ISSUE TITLE
Dapper.Contrib fluent column configuration

### ISSUE THREAD

**Issue by arnoldsimha** [StackExchange/Dapper#1434]
I must say I really love Dapper and Dapper.Contrib. I started to develop a new system and suggested Dapper to my organization. 
There is one issue that I'm facing tho, We trying to separate between our models and attribute configuration. There is SqlMapperExtensions.TableNameMapper that allowing custom table name mapping, but there is no column configuration that will allow setting "Computed" attribute for example.
Is there a way to do this with Dapper?

**Comment by dallasbeek** [comment]
I ran into some of these things as well with Dapper.Contrib. Check out Dapper.Database https://github.com/dallasbeek/Dapper.Database

**Comment by arnoldsimha** [comment]
Great work. Your library has a lot of options. In my case, I need a lean and simple ORM and Dapper.Contrib gives everything I need except the mapping

**Comment by NickCraver** [comment]
In the big picture, you can heave lean and simple or lots of features, but unfortunately that's a spectrum. In this case, you'll want to look at third-parties - a mapper is not something we want to maintain in the core Dapper package :)
