### ISSUE TITLE
Chrome extension for Rinkeby not working

### ISSUE THREAD

**Issue by nicosampler** [StackExchange/Dapper#1456]
I'm trying to make work Dapper extension for Rinkeby, I downloaded the extension from here https://www.meetdapper.com/docs/start. After installing it, fails when I try to sing up or log in (with mainnet credentials)

**Comment by mgravell** [comment]
Oof. That's some fun project naming by those folks (pretty sure we pre-date them). I can see no way that this ends well for anyone.
