### ISSUE TITLE
How to use Dapper in .NET Core with Geospatial?

### ISSUE THREAD

**Issue by srudin** [StackExchange/Dapper#1466]
I found this very old post (and others) saying that geospatial functionality was added to the Dapper core: https://stackoverflow.com/questions/25538154/how-to-use-dapper-with-ms-sql-server-2012-geospatial-sqlgeography-column

However it is unclear to me what types I have to use for the properties on my entities. In the post it seems they were using SqlGeography from Microsoft.SqlServer.Types but unfortunately this package has no implementation for .NET Core. There is a package called System.Spatial which looks like a good choice in 2020 but this is not working.

Is there a simple example / tutorial showing how to do CRUD operations on geography columns using Dapper in .NET Core?

**Comment by srudin** [comment]
The solution was to use https://github.com/dotMorten/Microsoft.SqlServer.Types

This runs under .NET Core and then Dapper works out of the box.

**Comment by srudin** [comment]
...worked out of the box in the unit test project, but not after I started to use deserialization from the web project... :-(
I have no idea why this is behaving differently but I also had to add the assembly resolve hack to make it work: https://github.com/dotMorten/Microsoft.SqlServer.Types/issues/22

**Comment by NickCraver** [comment]
Unfortunately, this is a wider issue and yeah...it sucks. I wrote up a post on exactly this topic because of all the issues users hit, hope it helps with some context and solutions: https://nickcraver.com/blog/2020/02/11/binding-redirects/

**Comment by mgroves** [comment]
FYI, creating a custom assembly resolver seems to work - see https://stackoverflow.com/questions/57012534/cant-cast-sqlgeography-when-withdrawing-data-from-db/57373622#57373622 for instance:

```
using System;
using Dapper;
using System.Data.SqlClient;
using System.Runtime.Loader;
using Microsoft.SqlServer.Types;

namespace SqlTest
{
    class Program
    {
        static void Main(string[] args)
        {
            AssemblyLoadContext.Default.Resolving += Default_Resolving;

            var conn = new SqlConnection("Server=localhost;Database=AdventureWorks;Trusted_Connection=True;");

            var addresses = conn.Query("SELECT TOP 10 * FROM Person.Address");

            foreach (var address in addresses)
            {
                Console.WriteLine(address);
            }

            conn.Dispose();
        }

        private static System.Reflection.Assembly Default_Resolving(AssemblyLoadContext assemblyLoadContext, System.Reflection.AssemblyName assemblyName)
        {
            try
            {
                AssemblyLoadContext.Default.Resolving -= Default_Resolving;
                return assemblyLoadContext.LoadFromAssemblyName(assemblyName);
            }
            catch
            {
                if (assemblyName.Name == "Microsoft.SqlServer.Types")
                    return typeof(SqlGeography).Assembly;
                throw;
            }
            finally
            {
                AssemblyLoadContext.Default.Resolving += Default_Resolving;
            }
        }
    }
}

```

**Comment by Zero-Xiong** [comment]
@mgroves  Thanks for your solution!

May I ask one more: do you know how should I use this custom assembly resolve in ASP.NET Core? I have no idea where should use your example codes. Thanks again!

**Comment by mgroves** [comment]
I guess you might try putting that in `Main`, like I did for the console app, which is in Startup.cs in typical ASP.NET Core applications.

**Comment by Zero-Xiong** [comment]
Actually I did it inside my BaseRepository.cs

`
public class BaseRepository<T>: IRepository<T> where T: class, new()
{
      public BaseRepository()
      {
            AssemblyLoadContext.Default.Resolving += MicrosoftSqlServerTypesResolver.Default_Resolving;
      }
}
`

This also working. 

Thanks All!
