### ISSUE TITLE
Incorrect syntax near the keyword 'User'

### ISSUE THREAD

**Issue by apostrophesoftware** [StackExchange/Dapper#1472]
I am using version 2.0.35 of Dapper and Dapper.Contrib and I am seeing this error when attempting to read data from a Table SQL Server called User.

I am using C# Visual Studio 2019 and the project is a ASP .Net Framework 4.6.1 project

My class is defined as below:

`
[Table("User")]
    public class User : NameBaseRecord
    {
        public class definition here
    }

    public abstract class IdentityBaseRecord
    {
        [Key]
        public long Id { get; set; }
    }

    public abstract class NameBaseRecord : IdentityBaseRecord
    {
        public NameBaseRecord()
        {
            Id = 0;
            Name = String.Empty;
        }

        public string Name { get; set; }
    }
`

The call I am using that generates the exception is:

`_dbConnection.GetAll<T>().Where(u => u.Name == name).FirstOrDefault();`

According to the documentation decorating the classes as shown should prevent this problem from occurring.  What is the problem?

Regards

**Comment by apostrophesoftware** [comment]
Doh! User, should have been [User] :-(

**Comment by spaghetti-m0nster** [comment]
Just to expand on this, User is a reserved keyword so for regular table operations to work you need to wrap it in square brackets for Sql Server and double quotes for Postgres/Redshift.
