### ISSUE TITLE
For stored procedures, how do you know that you have to prefix the parameter name with `@`?

### ISSUE THREAD

**Issue by StasD** [StackExchange/Dapper#1473]
I'm very curious:
```sql
var user = cnn.Query<User>("spGetUser", new {Id = 1},
        commandType: CommandType.StoredProcedure).SingleOrDefault();
```
If `spGetUser` is, say, in MS SQL Server, and its parameter is defined as `@Id`, how do you know that you have to prefix the parameter name with `@`?..
Thanks.

**Comment by mgravell** [comment]
Simple, you don't (have to) and we don't (do it).

**Comment by StasD** [comment]
You mean, for stored procedures I have to always specify parameter names as they are defined in the database (`new {@Id = 1}` in the above example), or they won't work?
(Right now, I'm on Mac and working with MySQL database, but had experience with MS SQL before, that's why the question...)

**Comment by StasD** [comment]
Or the database driver figures that out?

**Comment by mgravell** [comment]
In most ADO.NET providers, including the symbol (whether that is @, : or $ or something else) in the *parameter name* (in the `.Parameters` sense), is optional. I still haven't found a reliable API that tells me what symbol to use in the general sense, so Dapper just *doesn't include it*. It works fine.

**Comment by StasD** [comment]
OK, Thanks!
