### ISSUE TITLE
When should one consider avoiding use of `QueryMultiple` and instead use `ExecuteReader`?

### ISSUE THREAD

**Issue by SpiritBob** [StackExchange/Dapper#1476]
When using `ExecuteReader` you're basically working with one of the lowest objects in the food-chain, and do all the hard work yourself - mappings and whatnot.

When is the above preferable, to instead letting methods like `QueryMultiple`, `Query`, do all that work for us? I began reading the source code for those methods, but it's a bit hard to understand what exactly's going on.

It's true that in mere 5-9 lines of code you can achieve some of the most complex mappings by using `QueryMultiple`  utilizing multiple sets of data, but when is taking the extra-mile worth it? Writing `reader["something"] is DBNull ? null : (Nullable<long>)reader["something"]` will get old pretty fast.

**Comment by mgravell** [comment]
Simply: when you want to use Dapper to handle all the parameter packing, but you want to do something atypical with the data-reader - for example, you might want to use it to fill a `DataSet` (which not a lot of people do these days, but: it does happen), or you might want to use the *result* of one operation as the *source* for a `SqlBulkCopy` operation - which requires the raw data reader.

**Comment by SpiritBob** [comment]
@mgravell Thank you for the swift response!

Does the Reader approach yield non-negligible performance to the alternatives?

**Comment by mgravell** [comment]
Not really, no. This API isn't about a different performance range - it is simply about exposing an API that people sometimes need, in a way that is convenient.

If you don't need that API: don't use it - simple as.
