### ISSUE TITLE
any work around to avoid using attributes?

### ISSUE THREAD

**Issue by yekanchi** [StackExchange/Dapper#1487]
I'm using Dapper and have base class `Entity` in my domain project, which is separated from my repository layer. because of using dapper in my repository layer i have to use `[key]` and `[ExplicitKey]`  with bunch of other attributes like `[table]` and `[write(false)]` in my Domain Project.

Is there any work around to specify those attributes in my repository layer so i don't have to reference Dapper and Dapper.Contrlib in my domain layer.

**Comment by NickCraver** [comment]
There isn't yet, but will be in v3 - see #722 on this front. You'll be able to do this programmatically not just with attributes in the current plan - please add any ideas to #722!
