### ISSUE TITLE
Contrib `Get` method doesn't escape column names

### ISSUE THREAD

**Issue by zaus** [StackExchange/Dapper#1489]
https://github.com/StackExchange/Dapper/blob/4fb1ea29d490d13251b0135658ecc337aeb60cdb/Dapper.Contrib/SqlMapperExtensions.cs#L179

And I stupidly have a column named `Key` which causes the following:

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Key = 'XXXX'' at line 1

**Comment by NickCraver** [comment]
@zaus You can escape names via `"[Key]"` in the attribute itself :)

**Comment by NickCraver** [comment]
Closing out to tidy!
