### ISSUE TITLE
error message not helpful when type mismatch

### ISSUE THREAD

**Issue by la-yumba** [StackExchange/Dapper#149]
public class Person { public string Id { get; set; } /\* etc... */ }
var result = cnn.Query<Person>(@"select top 1 \* from Persons").ToList().First();

if Id is defined in the DB as uniqueidentifier, then the error message reads:
Error parsing column 0 (Owner=Invalid attempt to read from column ordinal '0'.  With CommandBehavior.SequentialAccess, you may only read from column ordinal '1' or greater.)

IMO this should just work and populate the string Id (this would be consistent with how it works when saving - you can write a string into an uniqueidentifier column)

**Comment by pranavmehta** [comment]
I am seeing error this in Dapper 1.4, ExecuteReaderAsync, while executing a stored procedure.

Reading the column values in correct order, works fine, and does not generate this exception..
