### ISSUE TITLE
MySQL exception when using CONCAT

### ISSUE THREAD

**Issue by AndreFNBarros** [StackExchange/Dapper#1497]
I'm using a the query

`SELECT number AS 'Value', CONCAT(number, ' - ', description) AS 'Display' FROM cfop`

to populate a combobox with

`public class ComboBoxItem
    {
        public object Value { get; set; }
        public string Display { get; set; }
    }`

, but I was getting a error of Cast Exception.
but I was using the similar queries in other tables and it is working so when I check I realized that my "number" column is INT and is the only difference between the ones that work and this one that didn't so when I tryied

`SELECT number AS 'Value', CONCAT(CAST(number AS CHAR), ' - ', description) AS 'Display' FROM cfop`

it worked.
Is this an expected behavior? I'm new to Dapper so I just wanted to check since I didn't find any mention on google.

Thanks!

**Comment by joncloud** [comment]
I tried to reproduce this behavior, and I wasn't able to. Some things that would help out:
* Information about the library used to connect, i.e., the NuGet reference.
* Information about the schema for the `number` and `description` columns for the `cfop` table.

I spun up the following test, used `Dapper@2.0.35`, `MySql.Data@8.0.21` and both queries test successfully.
```csharp
public class ComboBoxItem
{
    public object Value { get; set; }
    public string Display { get; set; }

    public static bool Test(DbConnection connection)
    {
        var first = First(connection);
        var second = Second(connection);

        return first.Display == second.Display &&
            Equals(first.Value, second.Value);
    }

    public static ComboBoxItem First(DbConnection connection) =>
        connection.QuerySingle<ComboBoxItem>(@"
            SELECT
                number AS 'Value'
            ,   CONCAT(number, ' - ', description) AS 'Display'
            FROM cfop
        ");

    public static ComboBoxItem Second(DbConnection connection) =>
        connection.QuerySingle<ComboBoxItem>(@"
            SELECT
                number AS 'Value'
            ,   CONCAT(CAST(number as CHAR), ' - ', description) AS 'Display'
            FROM cfop
        ");
}
```

For reference I used the following to create my schema:
```mysql
CREATE TABLE cfop (
  number INT
, description VARCHAR(24)
);
```

**Comment by NickCraver** [comment]
I think the confusion here was the source of the exception. The cast exception would happen (correctly) down at the server level. Dapper is just bubbling that up - I've done the same thing many times when writing a query :)

Closing this out to tidy up - @joncloud thanks for the example and more help to anyone finding this!
