### ISSUE TITLE
[A severe error occurred on the current command.  The results, if any, should be discarded.] Error while query dymatic

### ISSUE THREAD

**Issue by wu-wenzhi** [StackExchange/Dapper#1499]
Hi There,

My scenario is dramatically build query string and return a formatted object.

The DB schema example is as follows:
```SQL
CREATE TABLE [dbo].[StockDailyInfo]
(
	[FDate] [date] NOT NULL,
	[SecCode] [varchar](10),
	[BetaHS300Index] [decimal](18, 4) NULL,
	[BetaCompositeIndex] [decimal](18, 4) NULL,
	[BetaSYWGIndustryIndex] [decimal](18, 4) NULL,
	[PE] [decimal](18, 4) NULL,
        ....Other Indicators
)
```
The following C# code is building query script and getting the query results.
```C#
string sql = $"select {codeDefine.WildcardColumName}, {codeDefine.FDateColumName},{queryColumnsStr} from {codeDefine.TableName} where {codeDefine.FDateColumName} between @startDate and @endDate and {codeDefine.WildcardColumName} in @secCodes";

//Actually the sql which I build is
//select SecCode,FDate,PE from StockDailyInfo where FDate between @startDate and @endDate and SecCode in (@secCodes)

using (IDbConnection conn = new SqlConnection(dbConnStr))
{
    DynamicParameters dp = new DynamicParameters();
    dp.Add("@startDate", startDate);
    dp.Add("@endDate", endDate);
    dp.Add("@secCodes", secCodes);

    var queryResults = conn.Query<dynamic>(sql, dp).ToList();

    //do something...
}
``` 
When code goes to **conn.Query<dynamic>(sql, dp).ToList()**, there is an exception thrown:
**A severe error occurred on the current command.  The results, if any, should be discarded.**

I use SQL Server Profile to trace sql script which dapper send to SQL Server is
```SQL
exec sp_executesql N'select SecCode, FDate,[PE] from StockDailyInfo where FDate between @startDate and @endDate and SecCode in (@secCodes1)',N'@startDate datetime,@endDate datetime,@secCodes1 nvarchar(4000)',@startDate='1800-01-01 00:00:00',@endDate='1993-06-01 00:00:00',@secCodes1=N'000001'
```
I copy this script to SSMS and try to run this script, the same error return.

And I try to change from **@secCodes1 nvarchar(4000)**  to **@secCodes1 nvarchar(max)**, it works.

Now my temp solution is not using DynamicParameters, building sql query script in one line
```SQL
select SecCode,FDate,PE from StockDailyInfo where FDate between '1800-01-01' and '1993-06-01' and SecCode in ('000001')
```
But it is not a good practice.

Any idea to resolve this issue？

Thanks,
Vincent

**Comment by wu-wenzhi** [comment]
After a few investigations,I find:
the StockDailyInfo table is memory table(**MEMORY_OPTIMIZED = ON**)
the SecCode is varchar(10) but @secCodes1 nvarchar
I guess some strict policy with memory table in SQL Sever could effect this issue.

**Comment by mgravell** [comment]
Ultimately it isn't Dapper generating that error so I'm not sure what to
advise. We just send parameterized SQL. What the RDBMS does with it is up
to the RDBMS

**Comment by wu-wenzhi** [comment]
Is it possible to change **nvarchar(4000)** to **nvarchar(max)** by default when dapper generate sql script with parameters declaration?
At least, this solution would be work correctly in my scenario.

**Comment by mgravell** [comment]
You can use parameters of type DbString to configure various features of
the value, including the size.
