### ISSUE TITLE
Be able to downcast long to smaller integers to support Sqllite

### ISSUE THREAD

**Issue by agjini** [StackExchange/Dapper#1500]
### Description of the issue

Sqlite use only one column datatype for different size of integers (boolean, short, int...) : the `long` data type (encoded on 8 bytes).

When using Dapper with Sqlite, Dapper receive a column with the datatype `long` from the database and it can only fill a C# property of type `long`.

So we are forced to define a class with int64 types to map with the table in this case.

For example :

```
public sealed class Poco {
    
    public Poco(long id, long boolValue) {
        Id = id;
        BoolValue = boolValue;
    }

    public long Id { get; }
    public long BoolValue { get; }
}
```

Even if the table has been created with smaller data types :

```
CREATE TABLE POCO (
    id INTEGER,
    boolValue BOOLEAN
)
```

This will cause the following error if we try to use more precises types in our class. 
Dapper is looking for a constructor with Int64 properties :

```
System.InvalidOperationException : A parameterless default constructor or one matching signature (System.Int64 id, System.Int64 boolValue) is required for Poco materialization
   at Dapper.SqlMapper.GenerateDeserializerFromMap(Type type, IDataReader reader, Int32 startBound, Int32 length, Boolean returnNullIfFirstMissing, ILGenerator il) in /_/Dapper/SqlMapper.cs:line 3230
   [...]
```

We understand it is a limitation of Sqlite. But in an application where only Sqlite is used, its annoying but not very critical.
But in our case we are using both PostgresSQL (which is using more precise data types) for production and Sqlite for in memory tests.
This prevent us to test our application code in our tests (with Sqlite). Our mapping classes are not compatible.

### Expected behavior

Allow dapper to downcast incoming Int64 values from database into C# properties when looking for a constructor to materialize an object.

**Comment by bgrainger** [comment]
The System.Data.SQLite library will map `BOOLEAN` to `System.Bool`, `INT` to `System.Int32`, `INTEGER` to `System.Int64`, etc. That is, even though SQLite only has one integer type, it uses the SQL definition of the table to choose the corresponding .NET type. (I don't know if/where this is documented, but you can see the full SQL->.NET type map by searching for `GetSQLiteDbTypeMap` in http://system.data.sqlite.org/index.html/file?name=System.Data.SQLite/SQLiteConvert.cs&ci=trunk.)

I assume you're using Microsoft.Data.Sqlite, which doesn't do this? You could open an issue on Microsoft.Data.Sqlite, or switch to System.Data.SQLite, which provides the type-mapping behaviour you're looking for.

**Comment by agjini** [comment]
Indeed !
It works after switching to System.Data.SQLite (I was using Microsoft.Data.SQLite).
I also had to use INT instead of INTEGER in my columns definitions and and it works well.
I was not aware of the existence of two different drivers for SQLite.

However, due to the AUTOINCREMENT constraint of SQLite that can apply only on 64 bit column (ROWID),
I have to use INTEGER for AUTOINCREMENT column and must keep `long` datatype for these properties in my classes.

Maybe a solution is to use long instead of int for the AUTOINCREMENT columns in our application code.
But it is a little annoying to modify our application code to make test works.

I'm closing the issue since its not related with dapper.

Thank you for your relevant response.

**Comment by bgrainger** [comment]
Just discovered that this appears to be "by design" in Microsoft.Data.Sqlite: https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/dapper-limitations#data-types

**Comment by jbambhaniya** [comment]
@

**Comment by jbambhaniya** [comment]
@agjini I've used System.Data.Sqlite, but it is also giving me same error
