### ISSUE TITLE
Error while trying to insert records with Always Encrypted Columns

### ISSUE THREAD

**Issue by toklive** [StackExchange/Dapper#1510]
**Nuget Version:**
    <PackageReference Include="Dapper" Version="2.0.35" />

**Error:**
Microsoft.Data.SqlClient.SqlException: 'Operand type clash: nvarchar(4000) encrypted with (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'CEK_Auto1', column_encryption_key_database_name = 'crlf') is incompatible with nvarchar(50) encrypted with (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'CEK_Auto1', column_encryption_key_database_name = 'crlf')Statement(s) could not be prepared.'

**Code:**
   public Task<List<Assessment>> InsertAssessment(Assessment assessment)
        {
            var parameters = new DynamicParameters();
          
            parameters.Add("@ManagerId", assessment.ManagerId, System.Data.DbType.String);
            parameters.Add("@MetaId", assessment.MetaId, System.Data.DbType.Int32);
            parameters.Add("@StartDate", assessment.StartDate, System.Data.DbType.Date);
            parameters.Add("@IsActive", assessment.isActive, System.Data.DbType.Boolean);
            parameters.Add("@Title", assessment.Title, System.Data.DbType.String);

            string sql = "INSERT INTO dbo.Assessment (ManagerId,MetaId, StartDate,isActive, Title) " +
               "VALUES (@ManagerId,@MetaId,@StartDate,@IsActive, @Title)";
            return _db.LoadData<Assessment, dynamic>(sql, parameters);
        }

       public async Task<List<T>> LoadData<T, U>(string sql, U parameters)
        {
            try
            {
                string connectionString = _config.GetConnectionString(ConnectionStringName);

                using (IDbConnection connection = new SqlConnection(connectionString))
                {
                    var data = await connection.QueryAsync<T>(sql, parameters);

                    return data.ToList();
                }
            }
            catch(Exception ex)
            {
                throw ex;
            }
            
        }

**Comment by mgravell** [comment]
DbString can be used to configure more specific string parameter types.
This might be what you need here.

**Comment by toklive** [comment]
Thank you. Yes, it was related to column string size. Thanks again!
