### ISSUE TITLE
Creating nuget package does not include dapper

### ISSUE THREAD

**Issue by botrot** [StackExchange/Dapper#1521]
We are building dot net standard backend and we are facing a problem when trying to do nuget packaging.
All the 3rd party libraries are listed under dependencies except Dapper and therefore versions remain hidden, is it something with the actual Dapper implementation, thanks ?

![image](https://user-images.githubusercontent.com/53857661/90483268-c487bb00-e134-11ea-9c43-fce18ef29a3e.png)

**Comment by mgravell** [comment]
Dapper doesn't do anything unusual or "clever" re dependencies; this is *probably* something that is best answered by looking at your csproj, but I can't do that from here. Are you using a regular thing like

``` xml
<PackageReference Include="Dapper" Version="2.0.35" />
```

?

**Comment by botrot** [comment]
Yeah same, oh we have Dapper installed in our Persistence layer but the layer which creates the nuget does not have it installed, found it, sorry for the inconvenience
