### ISSUE TITLE
Dapper for .NET Core 3.1 - Sybase connection - Linux docker

### ISSUE THREAD

**Issue by prashant-upadhyay** [StackExchange/Dapper#1525]
Hi,

Would like to know which is the recommended Dapper version to use with .NET Core 3.1 API to access Sybase database running on a Linux docker?

Thanks!

**Comment by mgravell** [comment]
By default, I'd say "the latest one". The core maintainers don't use
Sybase, so if there are problems: you'd need to provide info.

**Comment by NickCraver** [comment]
Yep! Closing out to cleanup.

**Comment by prashant-upadhyay** [comment]
Thank you!
