### ISSUE TITLE
Add GetTypeHandler(Type type) method to SqlMapper

### ISSUE THREAD

**Issue by IanLedzion** [StackExchange/Dapper#153]
To elegantly handle Oracle SYS_REFCURSOR out parameters, I am implementing a custom SqlMapper.IDynamicParameters class. In the AddParameters(IDbCommand command, SqlMapper.Identity identity) method I would like to use any registered ITypeHandler instances. The easiest way to acquire a reference to a registered instance would be via a GetTypeHandler(Type type) method on SqlMapper.

**Comment by saitolabs** [comment]
@IanLedzion do you have any update in this issue?

**Comment by thomasvdb** [comment]
@IanLedzion Is this still an issue or is this eligible for closing?

**Comment by NickCraver** [comment]
Closing this out to cleanup. For the original use case, I recommend taking a look at Dapper.Oracle: https://github.com/DIPSAS/Dapper.Oracle/ (it has handling for these)
