### ISSUE TITLE
MultiMapping weridness

### ISSUE THREAD

**Issue by TrendyTim** [StackExchange/Dapper#1539]
I cannot for the life of me figure out why the parent object (Job)  is not being populated correctly, the JPID (primary key) gets populated, and the Organization (OID and Name) gets populated, but the title doesn't but the title does get filled in (but not the org info) with the same query if I don't try to do multi mapping 

(please excuse the VB and the slightly contrived example, I'm just trying to understand how it works with a simple test, adding the org as a nested object in the Job).

As some quick background the Job table has an OID column pointing the org table (whose PK is OID) so i join on that and the query works just fine.

Am i doing something wrong, or is there a bug ?

```VB
    Public Class Job
        Property Title As String
        Property JPID As Integer
        Property Organization As Org
    End Class
    Public Class Org
        Property OID As Integer
        Property Name As String
    End Class

Dim p = new with {.JPID = 4}
Dim query = "SELECT JPID, Jobs.OID, Jobs.Title, Org.Name from Jobs inner join Org on Jobs.OID = O.OID where JPID = @JPID"
Dim res = db.Query(Of Job, Org, Job)(query, 
                       Function(job, org)
                             job.Organization = org 
                             Return job 
                       End Function, 
p, splitOn:="OID")
```

**Comment by mgravell** [comment]
You told it to split on OID, which means when it finds OID it is thinking about the next type. So: move the `Jobs.OID` column to the right, so it is *after* the jobs columns. Or perhaps even clearer: don't select Jobs.OID at all, but instead select Org.OID at the appropriate time. Same value, but a clearer left/right split.

``` sql
SELECT JPID, Jobs.Title, Org.OID, Org.Name
```

**Comment by TrendyTim** [comment]
@mgravell Thank you, i guess i didn't realise it literally split on those field names, I thought it was more that was more a data grouping thing, seems a little weird instead of just doing a straight column to property assignment, i guess ill have to be more careful in my query organization,
