### ISSUE TITLE
Performance Question about ToList()

### ISSUE THREAD

**Issue by dogac00** [StackExchange/Dapper#1542]
After calling `QueryAsync<T>`, in terms of performance in queries that are selecting a lot of data, should we call `ToList()` and iterate the list or should we iterate the `IEnumerable<T>` itself?

**Comment by mgravell** [comment]
Right now, IIRC it won't matter - to avoid sync-over-async, it builds the
list fully before returning either way.

Note that IAsyncEnumerable-T did not exist even conceptually when this API
was written.

When we next revise the API (which is planned, just: time!), we will
probably move to:

IAsyncEnumerable<T> QueryUnbufferedAsync<T>

and

Task<List<T>> QueryAsync<T>
