### ISSUE TITLE
QueryAsync<T> The Asynchronous query cannot get any results

### ISSUE THREAD

**Issue by YanceyHo** [StackExchange/Dapper#1555]
Dapper 2.0.35/.NET 4.7.2
No results can be obtained using the QueryAsync<T>, The Async Thread Seems to automatically exit

        public async Task<int> GetByAuthority()
        {
            using (SqlConnection conn = new SqlConnection(SqlHelper.connectionString))
            {
                string sql = $@"SELECT COUNT(*) FROM [user]";
                var res = await conn.QueryAsync<UserDO>(sql);
                return res.Count();
            }
        }

Unless I manually construct an asynchronous query through the Query<T>, I can get the result

        public Task<int> Test()
        {
            return Task.Run(() =>
            {
                using (SqlConnection conn = new SqlConnection(SqlHelper.connectionString))
                {
                    string sql = $@"SELECT COUNT(*) FROM [user]";
                    var res = conn.Query<UserDO>(sql);
                    return res.Count();
                }
            });
        }

**Comment by YanceyHo** [comment]
I have also made a similar attempt in the **Console program**. Asynchronous queries can be executed normally, 
**But** in the **MVC Web** project, the query results cannot be obtained.

**Comment by mgravell** [comment]
Any chance you're using the legacy sync-context implementation? I can't
remember the web-config key for this - something like "use task friendly
sync context" (=false)

**Comment by kevingates** [comment]
I'm getting this error also. In a Blazor Server-Side app,it's actually throwing a Null Reference exception and affecting the render tree. It errors out in a weird way that its avoiding all of my try caches. 

If I switch it to Query<T> instead of QueryAsync<T>, then it works.

**Comment by YanceyHo** [comment]
I found the reason for this error, It's not a problem with the framework
**_I mix blocking and async code_**
[There is an article detailing the use of asynchronous programming in ASP.NET](https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming)

**Comment by brendanalexdr** [comment]
> I found the reason for this error, It's not a problem with dapper **_I mix blocking and async code_** [There is an article detailing the use of asynchronous programming in ASP.NET](https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming)

yup this was the problem.  easy to make this error
