### ISSUE TITLE
Mysql Transaction is no work, it had change the data but i had not commit .

### ISSUE THREAD

**Issue by luoyigit** [StackExchange/Dapper#1582]
using(var db = GetLocalDapperDb())
            {
                var tran = db.BeginTransaction();
                try
                {
                   
                    db.Execute("update equipmentcategory set freedays =8 where id=@id", new { id = "5fabb2818c7c5c0ce0b8272a" }, tran);
                    db.Execute("2qeqeq ",null, tran);
                }
                catch
                {
                    tran.Rollback();
                }

**Comment by mgravell** [comment]
Are you missing a `Commit()` here? (also: it is a very bad idea to swallow exceptions). Example:

``` c#
using(var db = GetLocalDapperDb())
{
    var tran = db.BeginTransaction();
    try
    {               
        db.Execute("update equipmentcategory set freedays =8 where id=@id", new { id = "5fabb2818c7c5c0ce0b8272a" }, tran);
        db.Execute("2qeqeq ",null, tran);
        tran.Commit();
    }
    catch
    {
        tran.Rollback();
        throw;
    }
}
```

**Comment by luoyigit** [comment]
> Are you missing a `Commit()` here? (also: it is a very bad idea to swallow exceptions). Example:
> 
> ```cs
> using(var db = GetLocalDapperDb())
> {
>     var tran = db.BeginTransaction();
>     try
>     {               
>         db.Execute("update equipmentcategory set freedays =8 where id=@id", new { id = "5fabb2818c7c5c0ce0b8272a" }, tran);
>         db.Execute("2qeqeq ",null, tran);
>         tran.Commit(); // <=== added
>     }
>     catch
>     {
>         tran.Rollback();
>         throw; // <=== added
>     }
> }
> ```



I mean, My database Has changed。Even, I missing a Commit() and Rollback

**Comment by mgravell** [comment]
OK; what is the fundamental connection you're using here? meaning: what are you connecting to? does it support transactions?

**Comment by luoyigit** [comment]
> OK; what is the fundamental connection you're using here? meaning: what are you connecting to? does it support transactions?

Oh, I see，My Local Mysql DataBase's Engine Is MyISAM ，Thank you for your reply ！！

**Comment by mgravell** [comment]
so: "no" :) MyISAM does not support transactions, and rollbacks do nothing: http://ronaldbradford.com/blog/using-rollback-with-myisam-2010-03-31/

Dapper can't help you with that if the backend doesn't support it.

**Comment by mgravell** [comment]
Better source: https://dev.mysql.com/doc/refman/5.6/en/myisam-storage-engine.html

which states:

Transactions | No

Closing as  not a Dapper issue, but very useful to know - thanks!
