### ISSUE TITLE
Licensing when depending on Dapper in another open souce package

### ISSUE THREAD

**Issue by carl-berg** [StackExchange/Dapper#1585]
This might be a stupid question so feel free to close it or point me in a direction of some information.

I develop a few open source packages. One of them has a nuget dependency (not bundled) on dapper. My knowledge of open source licenses are somewhat lacking so my questions are:
- Should i also use an Apache2 license since dapper does or can i keep MIT, that i selected based on very little knowledge 😁
- Should i in my license include information about dapper and its license
- Should i in my readme include information about dapper and/or its licens

Also, thanks for your open source work! 😀

**Comment by mgravell** [comment]
Dapper's license is very permissive. Quite honestly, as long as you don't
attempt to be Dapper or represent the Dapper team, we're fine. I don't
think there is anything imposed on your choice of license, as Dapper is
licensed independently to yours; we don't demand you have the same license
as us - or any. And our license *should* be fine to just about anyone
consuming your library.

Mentioning is is nice, bit only if you want to: we don't demand anything.

**Comment by carl-berg** [comment]
Thanks for the quick response!
