### ISSUE TITLE
ExecuteAsync throws Exception when value in insert query contains "  :  "

### ISSUE THREAD

**Issue by timurash** [StackExchange/Dapper#1605]
This code:

`await connection.ExecuteAsync("insert into testtable (building_address_house) values ('13 sum : A')", transaction)`

Or this code:

`await connection.ExecuteAsync("insert into testtable (building_address_house) values (' : ')", transaction)`

Throws this exception:

`System.NotSupportedException: The member Connection of type Npgsql.NpgsqlConnection cannot be used as a parameter value`

![image](https://user-images.githubusercontent.com/63206211/104122926-dbd87680-5369-11eb-8e70-30c81f41cdc0.png)

How can I fix this problem?

**Comment by mgravell** [comment]
You're passing "transaction" as the parameters - it is presumably the
DbTransaction? If so:

Change "transaction" to "transaction: transaction" (to use named parameters
rather than ordinal)

**Comment by mgravell** [comment]
Btw: the values to be inserted probably *should* be parameters.

**Comment by timurash** [comment]
Thank you so much, your advice completely solved my problem
