### ISSUE TITLE
License Question: Porting SqlBuilder to Typescript

### ISSUE THREAD

**Issue by Calidus** [StackExchange/Dapper#1619]
I am interesting in porting the SqlBuilder class to Typescript. I would like permission to do so. I believe I would need to include the original Copyright, License and Notice files.

**Comment by mgravell** [comment]
Honestly, by the time you're in typescript land, I think there's so much change necessary that I doubt anyone here will want to claim ownership; in my mind: have fun with that - at best, I'd say (as an admin here): an "inspired by SqlBuilder from Dapper" would be *nice*, but even that is not really *necessary*.

**Comment by Calidus** [comment]
Ok thanks for quick response, I definitely put a note in source code. I like the clauses logic in SqlBuilder and just wanted to be safe.
