### ISSUE TITLE
Default Dapper command timeout value?

### ISSUE THREAD

**Issue by SpiritBob** [StackExchange/Dapper#1627]
This is probably a stupid question, but I know the default for [SqlCommand.CommandTimeout](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.commandtimeout?redirectedfrom=MSDN&view=dotnet-plat-ext-5.0#System_Data_SqlClient_SqlCommand_CommandTimeout) is 30 seconds, but I'm not sure if `Dapper` falls back on that if the value provided is null?

The timeout is in effect both for async and synchronous API calls?

**Comment by bgrainger** [comment]
Dapper will use the database library's default value if none is explicitly specified.

In Microsoft.DataSqlClient 2.1 you can customise the default in the connection string: https://github.com/dotnet/SqlClient/blob/master/release-notes/2.1/2.1.0.md#command-timeout-connection-string-property

See also https://github.com/StackExchange/Dapper/issues/1579#issuecomment-731710521.
