### ISSUE TITLE
 AsArray() Extension method ?

### ISSUE THREAD

**Issue by Sharaf-Mansour** [StackExchange/Dapper#1629]
Same functionality as 'AsList()' but returns T[ ]
```CSharp
   public static T[] AsArray<T>(this IEnumerable<T> source) =>
            (source == null || source is T[]) ? (T[])source : source.ToArray();
 ```
Arrays are way faster than Lists and using this might help improving the performance even further.
I personally use this now and I have no issues with it so far.

**Comment by mgravell** [comment]
That would serve no real purpose in the current code, as AsList() is mostly useful to coerce something that *is already a list*. That won't be the case for arrays. Apart from other things, reasons we don't use arrays directly:

- we don't know the number of records in advance
- we'd have to do an *additional* allocation / copy at the end, to right-size it

I suspect when we redesign the API next,  we'll have separate APIs for lists vs sequences.

Side note: IIRC you can now fetch a span from a list. Spans are as fast - or sometimes faster - than arrays.

**Comment by mgravell** [comment]
For the "list to span" bit: CollectionsMarshal.AsSpan()
