### ISSUE TITLE
Milliseconds not returned?

### ISSUE THREAD

**Issue by mvodep** [StackExchange/Dapper#1630]
Dapper: 2.0.78
Npgsql: 5.0.1.1
Databaseytpe: timestamp without tz

PgAdmin show msecs - but when I do
```
var result = connection.Query("SELECT * FROM table");
var resultAsList = result.Cast<IDictionary<string, object>>();
```
msecs are gone

Any hints? Thanks

**Comment by mgravell** [comment]
Dapper just takes the value it is given. It doesn't do any munging or
rounding, so I'm not sure what we could do here. I suspect that if you do
the same query with raw ADO.NET, you'll see the same values.

**Comment by mvodep** [comment]
Wow - sorry!!! I tried it on a different server - and it worked ...
https://github.com/mvodep/Test/blob/master/Test/Program.cs

So i have to find out what is different between my server on the cloud pgsql
