### ISSUE TITLE
The type initializer for 'Dapper.SqlMapper' threw an exception

### ISSUE THREAD

**Issue by WoodyJ007** [StackExchange/Dapper#1641]
The error "The type initializer for 'Dapper.SqlMapper' threw an exception" is being thrown only on certain PCs when using 2.0.78.  Rolling back to 2.0.35 and rebuilding and it works on these PCs as expected.  Other PCs work fine on 2.0.78. Same code, built from same Build PC etc..  only difference is I have to downgrade to 2.0.35 and release to work on certain PCs.

Is there anything on the PCs that could be causing 2.0.35 to work but 2.0.78 not to?  I'm out of ideas...

**Comment by mgravell** [comment]
First step would be: catch the exception, and look at the inner
exception(s) - what do they say?

**Comment by WoodyJ007** [comment]
Hi, thanks for getting back to me.

The inner exception message is the following

Method not found: '!!0[] System.Array.Empty()'.

Again, rolling back to the previous version works fine and again only on some PCs so quite hard to debug.

I've simplified the code and can recreate it using a very basic class.

`public class Class1
    {
        public int LogDataID { get; set; }
    }`
    

Passing in an instance of this class into the below.

`
private void SetupMapping(Type ObjectType)
        {
            // It fails on this line with inner exception saying Method not found: '!!0[] System.Array.Empty()'.
            var oldMap = SqlMapper.GetTypeMap(ObjectType);
        }
`

Hope this helps

**Comment by WoodyJ007** [comment]
I'm starting to think this is a .net issue. The server I can recreate this on is due for a restart after I've reinstalled .net 4.8, this will happen tonight hopefully and this issue may disappear.

**Comment by mgravell** [comment]
Aye, this sounds like a mismatch in netstandard targeting in netfx, caused
by the reality that netstandard in netfx is a huge hack built on lies and
duck tape.

If it doesn't go away: let me know.

**Comment by WoodyJ007** [comment]
Yep, .net reinstall and server restart sorted it. Thanks for taking the time to respond. Loving Dapper!
