### ISSUE TITLE
what difference between standard parameter query and Literal replacement ?

### ISSUE THREAD

**Issue by rustbomber** [StackExchange/Dapper#175]
what difference between standard parameter query and Literal replacement ?

```
    string sql = "select count(1) from user where lgtd={=lgtd}";
    string sql = "select count(1) from user where lgtd=@lgtd";
```

**Comment by rjrudman** [comment]
@mgravell  I realise this is an old post, but I noticed the syntax from [this tweet](https://pbs.twimg.com/media/CkQtv94WgAIjkpf.jpg:large).

Does Dapper take into account SQL Injection? That is, is this feature safe to use with strings? For non-strings, does it simply invoke `.ToString()`?

**Comment by NickCraver** [comment]
@rjrudman The literal parameter feature explicitly doesn't allow strings, specifically for injection reasons. It only works on safe value types. You can view the typecode switch [here](https://github.com/StackExchange/dapper-dot-net/blob/5f27a4bfc49e6b2be4533a85a3de32deecaeeee8/Dapper/SqlMapper.cs#L2561).
