### ISSUE TITLE
Execute() not finding public fields on the input "param" object

### ISSUE THREAD

**Issue by scottbrenneman** [StackExchange/Dapper#195]
I'm emitting a class at runtime whose purpose is to represent a data object out of a database.

For simplicity, it's emitted as a class with a bunch of public fields.

If I pass an instance of this class to Execute() as the "param" argument, it does not recognize the public fields and map them to my sql variables.

I am having to re-emit them as public properties as a workaround.

**Comment by NickCraver** [comment]
This one was resolved - tidying up.
