### ISSUE TITLE
Seems to be a bug with ExecuteScalar sending Table Valued Parameters

### ISSUE THREAD

**Issue by rpipkin** [StackExchange/Dapper#209]
When using .AsTableValuedParameter within an ExecuteScalar, the dynamic sql that gets generated is creating the param but not generating the insert statements.  Hence, no error is created but no values are sent down to SQL server.

As a workaround, using Query seems to work fine.

**Comment by NickCraver** [comment]
@rpipkin is this happening on the current version of Dapper? There have been quite a few changes in several areas touched here since this was filed.
