### ISSUE TITLE
Dapper appears to make Oracle bind variables case-sensitive

### ISSUE THREAD

**Issue by burnchar** [StackExchange/Dapper#216]
I'm not sure whether this is intentional or not; if not. whether this is a Dapper gotcha or an Oracle one. Probably the latter because, you know, Oracle.
Oracle normally doesn't care about the case of bind variables and, if you quote them (e.g. `:"mybind"`) to try to force case, it doesn't recognize them as bind variables at all. 

---

```
DELETE
FROM "TESTTABLE"
WHERE ID = :id
```

Fails: `connection.Execute(deleteSql, new { ID = request.Id });`
Succeeds: `connection.Execute(deleteSql, new { id = request.Id });`

---

```
DELETE
FROM "TESTTABLE"
WHERE ID = :ID
```

Fails: `connection.Execute(deleteSql, new { id = request.Id });`
Succeeds: `connection.Execute(deleteSql, new { ID = request.Id });`

---

The same applies when I use DynamicParameters from a Dictionary<string, object>. The key's case is significant.

Failure is:
System.ArgumentException
`Invalid parameter binding: id`
 from Oracle.ManagedDataAccess

Using the latest: Dapper 1.38 and oracle odp.net.managed (NuGet) 121.1.2.

**Comment by NickCraver** [comment]
The above advice is correct: if the code matches, you're all good - the same is true for a case sensitive master database on SQL Server for example. Since this is working as designed, finally closing out.
