### ISSUE TITLE
Parameters not filtered when passed in as Dictionary<string, object>

### ISSUE THREAD

**Issue by cbrianball** [StackExchange/Dapper#234]
Looking at SQL Profiler, it looks like Dapper is filtering out parameters that aren't used by the SQL query when the `param` parameter is a dynamic type, anonymous type or a standard POCO. But, if a dictionary is passed in, it looks like all parameters are being included in the query sent to SQL Server, even if some of the parameters are not used in the query itself.

Is this by design (e.g. is there a scenario I'm not thinking of where this would be desired)?

**Comment by NickCraver** [comment]
For anyone else hitting this, the recommendation is as in #680 - to create a `DynamicParameters()` collection instead (which also allows the correct type data). Going through old issues to tidy up here and hopefully point to the correct solution spots.
