### ISSUE TITLE
Broken parameters caching for same SP called first wtih QueryMutliple then Query

### ISSUE THREAD

**Issue by lskrajny** [StackExchange/Dapper#243]
We recently upgraded from 1.13 and encountered a problem where we execute stored procedure which can return either one or two recordsets based on the bit parameter it accepts.

Problem has something to do with caching, seems like Dapper is doing internally some caching based on connection string/stored procedure name.

Issue occurs when first QueryMultiple is executed with bit param set to true (@ReturnMultiple) all is fine, but next almost identicial call using Query and @ReturnMultiple = false, NONE of the parameters are passed to the SP.

Not sure whether it makes a difference but there are also some TVP parameters being passed to SP implementing SqlMapper.IdynamicParameter interface.

**Comment by IainWoodUK** [comment]
I am having the exact problem - did you ever resolve this?

**Comment by IainWoodUK** [comment]
The resolution is to change all the Querys to QueryMultiples on that proc

**Comment by mgravell** [comment]
Is there a concrete repro I can look at?

**Comment by IainWoodUK** [comment]
Sorry no repro. I'm using SQL Server 2012, Windows Server 2012 and MVC5. I'm using the same proc for a list view that returns 1 recordset, but if an id is passed it returns 2 recordsets. If the detail view with "query multiple" runs, then the list view with "query" the error occurs. I changed both call to use "query multiple" and now the error is gone.

Definitely a bug / feature of Dapper.

**Comment by NickCraver** [comment]
Haven't heard this reported since - going to close out as it *should* no longer be an issue in latest.
