### ISSUE TITLE
Update benchmarks to include EF7

### ISSUE THREAD

**Issue by zam6ak** [StackExchange/Dapper#246]
Would it be too early to request benchmarks be updated to include [Entity Framework 7](https://github.com/aspnet/EntityFramework).
It is supposed to perform better and be more 'lightweight'..
Also I am not sure if this would depend on #241 .

Thoughts?

**Comment by mgravell** [comment]
That's probably very worthwhile and overdue; it will require me to figure
out how to use EF 7, though - a direct upgrade might not be the most
appropriate comparison.

On 27 February 2015 at 03:20, zam6ak <notifications@github.com> wrote:

> Would it be too early to request benchmarks be updated to include Entity
> Framework 7 <https://github.com/aspnet/EntityFramework>.
> It is supposed to perform better and be more 'lightweight'..
> Also I am not sure if this would depend on #241
> <https://github.com/StackExchange/dapper-dot-net/issues/241> .
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/246>.
>



-- 
Regards,

Marc

**Comment by zam6ak** [comment]
I'd love to see the comparison once benchmarks are updated.
Thanks for considering it!

**Comment by NickStrupat** [comment]
The EF6 performance results are already much better than indicated in the performance chart. Can we get an updated performance chart?

**Comment by NickStrupat** [comment]
README.md is still showing significantly inaccurate performance results for Entity Framework.

**Comment by NickCraver** [comment]
@NickStrupat it's not, but we need to label the versions and do tests with many. Is there an outstanding PR to update the benchmarks project? After MiniProfiler I can try and find time to re-run this on a controlled system.

**Comment by NickCraver** [comment]
EF Core (latest!) is now in the benchmark suite and the README is updated with results :)
