### ISSUE TITLE
advice about Colmap

### ISSUE THREAD

**Issue by uliian** [StackExchange/Dapper#251]
When coding in Oracle，we usually use the underscore"_" as the coloumn name segmentation. Then the value inquired cannot be well mapped on the corresponding object through the Dapper. "Simlpe.Data"is support for this kind of Map. 
I wonder if Dapper can do the same support as the"Simple.Data"

**Comment by henkmollema** [comment]
You could take a look at a library I wrote for Dapper: [Dapper.FluentMap](https://github.com/henkmollema/Dapper-FluentMap). It allows custom mapping between column names and POCO properties.

The [Transformations](https://github.com/henkmollema/Dapper-FluentMap#transformations) section might help you out.

**Comment by NickCraver** [comment]
Closing this out, but to finally move towards supporting it - please help us design the feature in #722!
