### ISSUE TITLE
Intermittent "System.InvalidCastException: Specified cast is not valid" with MySQL

### ISSUE THREAD

**Issue by mannybellas** [StackExchange/Dapper#264]
Every now and then we get this error:

![image](https://cloud.githubusercontent.com/assets/1657903/6914354/d5069f54-d7cc-11e4-85d5-0013eba953fe.png)

The query in question is this:

![image](https://cloud.githubusercontent.com/assets/1657903/6914186/70aeb614-d7cb-11e4-9782-55705a8c97fa.png)

The 2 columns in the coalesce are both UNSIGNED INT(10).

Some remarks:
- unfortunately haven't figured out how to replicate the error
- the error goes away when we restart the web app (touching the web.config)
- have updated mysql.data.dll to latest version - no success
- the property it is mapping to is `uint`

**Comment by mgravell** [comment]
Can you indicate how `Content` is typed in your model?

**Comment by ebellas** [comment]
Hi Marc, that is correct - FEP.Entities.Navigation.Content is typed `uint` (sorry, I didn't use adequate terminology).

**Comment by mgravell** [comment]
Actually you did; I just posted before I engaged my eyes properly. I will
investigate.

On 31 March 2015 at 10:08, Emmanuel Bellas <notifications@github.com> wrote:

> Hi Marc, that is correct - FEP.Entities.Navigation.Content is typed uint
> (sorry, I didn't use adequate terminology).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/264#issuecomment-88006767>
> .
>



-- 
Regards,

Marc

**Comment by NickCraver** [comment]
This was resolved in another issue, TL;DR: MySQL is being a bit evil here changing the return type on the fly. If seeing this, I'd recommend using one of the alternative drivers like https://github.com/mysql-net/MySqlConnector, which also handle `async` correctly.
