### ISSUE TITLE
Cancellation support with async queries?

### ISSUE THREAD

**Issue by osudude** [StackExchange/Dapper#313]
When I cancel an async dapper query (due to my own timeout needs), will dapper invoke the Cancel command on the underlying SqlCommand?

thanks

scott

**Comment by NickCraver** [comment]
This was mostly addressed in #119 but we missed a few - need to put them in all methods. Note: slightly breaking change (though they are optional, but still).

**Comment by NickCraver** [comment]
This is part of the v2 plan - closing out tracking here :)
