### ISSUE TITLE
The comprehensive list of examples link in the readme is broken.

### ISSUE THREAD

**Issue by eptiliom** [StackExchange/Dapper#397]
https://github.com/StackExchange/dapper-dot-net/blob/master/Tests/Tests.cs

No longer exists.

**Comment by mgravell** [comment]
I suspect that file is now here:
https://github.com/StackExchange/dapper-dot-net/blob/master/Dapper.DNX.Tests/Tests.cs

(Because: reasons)

I will update the readme tomorrow. Note that I also plan to move a lot of
documentation go a new docs portal - watch this space!
