### ISSUE TITLE
clarification on "Limitations and caveats"

### ISSUE THREAD

**Issue by justinmk** [StackExchange/Dapper#451]
Is the [Limitations and caveats](https://github.com/StackExchange/dapper-dot-net#limitations-and-caveats) section of the readme outdated?

> The current implementation caches this information in a ConcurrentDictionary object. The objects it stores are never flushed.

8ed5f615ee9589419cac5765eebeb08c03cd007c added automatic GC.

> If you are generating SQL strings on the fly without using parameters it is possible you will hit memory issues.

Does https://github.com/StackExchange/dapper-dot-net/commit/874731600e01a9dbf271c09f93a238bf7979ac6c have implications for that statement?

**Comment by NickCraver** [comment]
Yes, https://github.com/StackExchange/dapper-dot-net/commit/874731600e01a9dbf271c09f93a238bf7979ac6c added back unbounded implications, but since we don't track a hit count there cleanup isn't so easy. @mgravell think this is an issue?
