### ISSUE TITLE
Insert into child class

### ISSUE THREAD

**Issue by ArthNRick** [StackExchange/Dapper#493]
insert should take place in AlteraContraPartidaPorCnpj ' not in 'AlteraContraPartida'

   public class AlteraContraPartidaPorCnpj : AlteraContraPartida
    {
        private string cnpj;
        public string Cnpj
        {
            get { return cnpj; }
            set { cnpj = value; }
        }
    }

**Comment by NickCraver** [comment]
I'm not sure what's being asked here - do you have some .Net code that's failing? Are you talking about the Dapper.Contrib insert method using the wrong class name when inheritance is involved...or something else?
