### ISSUE TITLE
Encrypt & decrypt when mapping

### ISSUE THREAD

**Issue by rmnblm** [StackExchange/Dapper#503]
I haven't found quite the right solution and wasn't sure if there is one.

Is it possible to encrypt a value before saving to database and decrypt a value when loading from database? 

I don't know if `ITypeMap` or `IMemberMap` is the right solution for this problem.
I just want to manipulate an entity property when Dapper is mapping it from (decrypt row value) or to (encrypt property) SQL database.

Any help is appreciated :smiley:

**Comment by NickCraver** [comment]
What version of SQL Server are you on? On the server side, there are some bits in current versions to support this and many more bits being added in SQL 2016.

**Comment by rmnblm** [comment]
Hi Nick

I don't want to solve this on server side, I have my reasons to make this inside the application. :relaxed:
Do you know another solution?

Thanks!

**Comment by NickCraver** [comment]
@rmnblm There are client differences paired with the server here, mainly so when using an off-site SQL store (say: Azure) the data is encrypted the entire way there and back. It is on the client. There's also at-rest encryption in the database as well, but that's a different thing. There are several options in play...but I can't point you any direction without knowing which you have access to :)

**Comment by rmnblm** [comment]
Well does it matter which SQL database I use? :relaxed: I use MSSQL btw.

Right now, I have two methods: 
`BeforeSave(entity)` which encrypts sensitive properties before saving it to database and `AfterLoad(entity)` which decrypts sensitive properties for usage in the application after loading from database.

I just thought there might be a better solution where I can transform values with Dapper when it maps the properties to entity classes...

**Comment by jimmywyatt** [comment]
I have the same question, the encryption is done in the app

**Comment by mgravell** [comment]
Ultimately, the way I'd approach this app-side is : to do the encryption /
decryption separately to the DAL. Either explicitly, or *at worst* in a
shim property, for example:

    byte[] Foo { // or string, or whatever
       get { return Encrypt(Bar); }
       set { Bar = Decrypt(value); }
    }

**Comment by rmnblm** [comment]
@jimmywyatt In the repository I've created two methods, one for `BeforeStore()` and one for `AfterLoad()` which does the encryption/decryption. I couldn't find a better solution 😞

**Comment by NickCraver** [comment]
As Marc says above - the best way to do this is in a layer above Dapper. I don't foresee this being something we add support for in the library.
