### ISSUE TITLE
Support for renaming and combining DynamicParameters

### ISSUE THREAD

**Issue by default-kramer** [StackExchange/Dapper#511]
I have built a thin layer over Dapper that allows me to define queries individually, yet still execute multiple queries in one round trip to the DB. I do this by combining the SQL into a single string, and combining the parameters into a single collection. To avoid name collisions, I assign a prefix to each parameter.

I have got this working using IDictionary&lt;string, object&gt; as my parameter collection. However, I would prefer to use DynamicParameters. (In case I need to set the ParameterDirection, DbType, etc, it would be nice to have direct access to the Dapper API.) But the public interface of DynamicParameters does not seem to allow what I want to do.

I want to be able to do something like this. (This would probably be a unusually specific method to build into Dapper, but you get the point.)

`DynamicParameters p1 = getP1();`
`DynamicParameters p2 = getP2();`
`var combined = new DynamicParameters();`
`combined.AddAll(p1, prefix: "p1_");`
`combined.AddAll(p2, prefix: "p2_");`

For reference, here is how I have implemented the query combiner: https://gist.github.com/default-kramer/1635235ed670e2282ddd93f15b2530a9

**Comment by mgravell** [comment]
Have you considered simply writing a separate class that implements
`IDynamicParameters`? Would that give you the flexibility you need?

**Comment by default-kramer** [comment]
Yes, I could get it to work by implementing IDynamicParameters. I could also (probably more easily) create a custom data type to represent a parameter and pass that through my application until it's time to use Dapper and then use DynamicParameters unchanged. For example

`dynamicParameters.Add(myparam.Name, myparam.Value, myparam.DbType, myparam.Direction, ...)`

Which will work. But either way feels like I'm re-implementing existing Dapper functionality. DynamicParameters is already the best way to collect parameters to hand to Dapper; there is just this one little thing it doesn't support. So yeah, it's definitely not a showstopper; just a minor annoyance at worst.

**Comment by NickCraver** [comment]
In this case, I think we'll stick with "you are free to implement this" (already supported) over adding weight for the rare case.

**Comment by ltvan** [comment]
I'd also love this feature. Adding prefix helps a lots of cases, not just rare cases. I can flatten nested parameters with it, combining parameters from multiple objects,...
