### ISSUE TITLE
Microsoft.Data.SQLite support for framework net451

### ISSUE THREAD

**Issue by bravecobra** [StackExchange/Dapper#513]
Is there a way to get Microsoft.Data.Sqlite support when running on net451? The new cross-platform Microsoft.Data.Sqlite package clearly supports net451 when running on linux (using mono), but Dapper seems to revert to System.Data.SQLite which isn't cross-platform.

**Comment by mgravell** [comment]
How do you mean, "dapper seems to revert to ..."? Dapper doesn't reference
sqlite or use sqlite in any way, except for the tests. It just takes a db
connection and does what it needs to. It *should* be the case that if you
hand dapper a Microsoft.data.sqlite connection: it uses that.

If you are seeing any specific problem or behaviour, please let us know
what **exactly** you are seeing.

**Comment by bravecobra** [comment]
I do indeed hand Dapper a SqliteConnection from Microsoft.Data.Sqlite and then call its generic Query method, with parameters. However the parameters never seem to get set. In the example below the connection is an open SqliteConnection and the table does exist. I'm not even making assertions yet.

```
        [Fact]
        public void ShouldExecuteAQueryWithParameters()
        {
            _storage = new SQLiteStorage("Data Source=aspnet5.db;");
            _storage.UseConnection(connection =>
            {
                string tableName = $"[{_storage.GetSchemaName()}.Server]";
                var builder = new SqlBuilder();
                var template = builder.AddTemplate($"select * from {tableName} where Id = @id", new { id = "test" });                
                // select by serverId
                var serverResult = connection.Query<Entities.Server>(
                    template.RawSql, template.Parameters).SingleOrDefault();                
            }, true);
        }
```

```
Test Name:	ConnectionQueryTests.ShouldExecuteAQueryWithParameters
Test FullName:	Hangfire.SQLite.Tests.ConnectionQueryTests.ShouldExecuteAQueryWithParameters
Test Source:	C:\Users\***\Documents\Development\hangfiretest\HangFireTest\src\Hangfire.SQLite.Tests\ConnectionQueryTests.cs : line 13
Test Outcome:	Failed
Test Duration:	0:00:00.463

Result StackTrace:	
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior)
   at Dapper.SqlMapper.<QueryImpl>d__125`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.SQLite.Tests.ConnectionQueryTests.<ShouldExecuteAQueryWithParameters>b__1_0(SqliteConnection connection) in C:\Users\***\Documents\Development\hangfiretest\HangFireTest\src\Hangfire.SQLite.Tests\ConnectionQueryTests.cs:line 21
   at Hangfire.SQLite.SQLiteStorage.<>c__DisplayClass16_0.<UseConnection>b__0(SqliteConnection connection) in C:\Users\***\Documents\Development\hangfiretest\HangFireTest\src\Hangfire.SQLite\SQLiteStorage.cs:line 165
   at Hangfire.SQLite.SQLiteStorage.UseConnection[T](Func`2 func, Boolean isWriteLock) in C:\Users\***\Documents\Development\hangfiretest\HangFireTest\src\Hangfire.SQLite\SQLiteStorage.cs:line 177
   at Hangfire.SQLite.SQLiteStorage.UseConnection(Action`1 action, Boolean isWriteLock) in C:\Users\***\Documents\Development\hangfiretest\HangFireTest\src\Hangfire.SQLite\SQLiteStorage.cs:line 163
   at Hangfire.SQLite.Tests.ConnectionQueryTests.ShouldExecuteAQueryWithParameters() in C:\Users\***\Documents\Development\hangfiretest\HangFireTest\src\Hangfire.SQLite.Tests\ConnectionQueryTests.cs:line 15
Result Message:	Must add values for the following parameters: @id
```
However when I hand it over a SQLiteConnection connection of System.Data.SQLite, parameters are being set and the query succeeds, but I need an SQLite connection that is cross-platform running on net451.

**Comment by bravecobra** [comment]
Could this be a similar problem but for another database driver? http://stackoverflow.com/questions/7823668/how-can-i-use-dappers-strongly-typed-query-parameters-with-sybase-ase

**Comment by bravecobra** [comment]
I added the following class to my project
```
    public class SqliteParameters : List<SqliteParameter>, SqlMapper.IDynamicParameters
    {
        public void AddParameters(IDbCommand command, SqlMapper.Identity identity)
        {
            foreach (var parameter in this)
                command.Parameters.Add(parameter);
        }
    }
```
And then used it in the following manner which seems to be working. Apparently Dapper doesn't handle the adding of parameters the way Microsoft.Data.Sqlite expects it.
```
        [Fact]
        public void ShouldExecuteAQueryWithParameters()
        {
            _storage = new SQLiteStorage("Data Source=aspnet5.db;");
            _storage.UseConnection(connection =>
            {
                string tableName = $"[{_storage.GetSchemaName()}.Server]";
                var parameters = new SqliteParameters() {new SqliteParameter("@id", "test")};
                var serverResult = connection.Query<Entities.Server>(
                    $"select * from {tableName} where Id = @id", parameters).FirstOrDefault();                
            }, true);
        }
```
That seems to fix it for Query<>, but applying the same for Execute, that is still failing

**Comment by bravecobra** [comment]
Upgrading to 1.50.0-beta 9 seems to fix the execute issue

**Comment by bravecobra** [comment]
And just to be complete: it runs on Linux as well under net451. 
Should this issue remain open (maybe under another title?) for the unsupported SqlMapper.IDynamicParameters of Microsoft.Data.Sqlite? I'd love to see parameters supported as a regular object instead having to specify them from a custom SqliteParameters().

**Comment by mgravell** [comment]
I will definitely examine the parameters issue; I'm not aware of an
existing issue there.

On 3 May 2016 at 02:25, bravecobra <notifications@github.com> wrote:

> And just to be complete: it runs on Linux as well under net451.
> Should this issue remain open (maybe under another title?) for the
> unsupported SqlMapper.IDynamicParameters of Microsoft.Data.Sqlite? I'd love
> to see parameters supported as a regular object instead having to specify
> them from a custom SqliteParameters().
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/513#issuecomment-216411282>
>



-- 
Regards,

Marc

**Comment by sebastienros** [comment]
A quick note on this: `where Id = @id`

From my tests the driver is case sensitive. which means it needs to be `where Id = @Id`

**Comment by NickCraver** [comment]
Going to close this out since there are other issues on the Sqlite side of things - the core issue here is resolved.
