### ISSUE TITLE
Dynamic object, returned as a query result have strange behavior.

### ISSUE THREAD

**Issue by ogorodov** [StackExchange/Dapper#516]
Greeting.

Firstly i want to say thank you, for such an amazing library. It help us a lot.

But we have problems with using dynamic object as a result of query execution. When we try to access some not existed property from dynamic object, it return "null" value. Suppose, that there is must be an exception.

**Comment by NickCraver** [comment]
Apologies this fell through. This is a result of how `DapperRow` (intentionally) implements `dynamic`, since you could select a column from your database that is `null`. Or you could select or not select with conditional SQL, etc.
