### ISSUE TITLE
Single Quote in nText field causes exception SQLCE

### ISSUE THREAD

**Issue by loginitin** [StackExchange/Dapper#523]
```vb.net
Dim r As Integer = 0
  Using con As IDbConnection = New SqlCeConnection(thcon.ConnectionString)
    r = con.Execute("Update Articles Set Body = @Body Where ID =  @ID", New DataModel.Articles With {.Body = A.Body, .ID = A.ID})
End Using`
```
## Whenever the Body field has a singlequote in it, an exception is received.

> Specified argument was out of the range of valid values.
> Parameter name: Invalid parameter Size value '-1'. The value must be greater than or equal to 0

Using SQLCE 4.
I'm able to update the table using DataAdapter otherwise.

.

**Comment by NickCraver** [comment]
This was a bug at one point before parameter data sizing in a few scenarios - cleaning out to cleanup since that's changed!
