### ISSUE TITLE
How could I pass a object of custom class as a parameter value?

### ISSUE THREAD

**Issue by wrjcs** [StackExchange/Dapper#540]
Hello,
When I passe an object of custom class as a parameter value,
I got this exception  The member Operator of type WeShop.DataBase.User cannot be used as a parameter value.
Has any solution?

Thanks.

**Comment by mgravell** [comment]
You can use your custom class as the parameters object, but not as the
individual parameters inside that. For example this is fine:

    connection.Execute(sql, user);

(The individual members will be made available as parameters; dapper will
try to apply some sanity as to which members to include)

But this is not:

    connection.Execute(sql, new { id, user});

The difference is that it won't know how to pass a user object **as an
individual parameter** unless you add a type-handler. Which technically can
be done, but: what is it that you are trying to to? What do you expect it
to do?

**Comment by NickCraver** [comment]
@wrjcs does this answer your question?

**Comment by markjerz** [comment]
Hi! 

Take a look at the  stuff I've got from  my  friend, do you  like something  like  that? Check it out <http://favor.politicslatest.co.uk/e4kmb>

Warmly, mark

**Comment by Ci3l0phi** [comment]
@mgravell Would it be possible to insert the primary key for that object if existent?

**Comment by regisbsb** [comment]
To people that land here from google:

Use `DynamicParameters.AddDynamicParams` to add multiple instances of templates

**Comment by mgravell** [comment]
@regisbsb  I'm not sure that's sage advice; `DynamicParameters` is *massively* over-used, way beyond when it is intended.
