### ISSUE TITLE
Missing assemblies for Xamarin on NuGet

### ISSUE THREAD

**Issue by Tylerian** [StackExchange/Dapper#556]
Hello,
Altough version 1.50 of Dapper has built-in support for Core CLR, looks like it's missing the target assemblies for Xamarin-iOS (dunno if also misses assemblies for Xamarin-Droid), thus giving me an error whenever I want to add Dapper's NuGet package to my Xamarin iOS Project.

`Adding Dapper...
Downloading Dapper 1.50.0...
Installing 'Dapper 1.50.0'.
Added file 'Dapper.dll' to folder 'Dapper.1.50.0/lib/net40'.
Added file 'Dapper.xml' to folder 'Dapper.1.50.0/lib/net40'.
Added file 'Dapper.dll' to folder 'Dapper.1.50.0/lib/net45'.
Added file 'Dapper.xml' to folder 'Dapper.1.50.0/lib/net45'.
Added file 'Dapper.dll' to folder 'Dapper.1.50.0/lib/net451'.
Added file 'Dapper.xml' to folder 'Dapper.1.50.0/lib/net451'.
Added file 'Dapper.dll' to folder 'Dapper.1.50.0/lib/netstandard1.3'.
Added file 'Dapper.xml' to folder 'Dapper.1.50.0/lib/netstandard1.3'.
Added file 'Dapper.1.50.0.nupkg' to folder 'Dapper.1.50.0'.
Successfully installed 'Dapper 1.50.0'.
Adding 'Dapper 1.50.0' to iOS.
Could not install package 'Dapper 1.50.0'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
`

Any plans on also compiling Dapper for Xamarin frameworks?

**Comment by Tylerian** [comment]
@mgravell @NickCraver

**Comment by mgravell** [comment]
The main reason I/we haven't added this is that we aren't Xamarin users and
don't tend to have the required setup or experience to validate. A PR would
be most welcome. Otherwise we can add it to the backlog.

**Comment by NickCraver** [comment]
For anyone else finding this: it's not a platform we can support without generators (one of our main use cases for them). They lack the ability to emit IL in general, which is at the core of how Dapper runs.
