### ISSUE TITLE
Map nested objects without joins (value objects)

### ISSUE THREAD

**Issue by mihaimarin83** [StackExchange/Dapper#561]
Hello Sirs,
I have an application built using CQRS pattern. On writing, I'm using EF which has the ability to use value objects (http://martinfowler.com/eaaCatalog/valueObject.html). Using them, my database columns are generated as CLASS_PROPERTY. Ex:
[
Company
->Id
->Address_Street
->Address_.....
->Bank_Name
->Bank....
->Contact_Name
->Contact_.....
....
]
On reading, I took the decision to use dapper for performance reasons. I tried to find an easy and clean solution to return my entity with similar nested objects.
I liked the FluentApi wrapper to map properties from the data reader and tried to use it but without luck. What I tried is:

``` c#
public class NestedMapper : EntityMap<NestedEntity>
    {
        public NestedMapper()
        {
            Map(p => p.Id).ToColumn("Id");
            Map(p => p.Address.Street).ToColumn("Address_Street");
            Map(p => p.Bank.Name).ToColumn("Bank_Name");
            Map(p => p.Contact.Name).ToColumn("Contact_Name");
        }
    }
```

Is there any solution to use something like that? Is there any posibility to make a NestedCompanyTypeMap:SqlMapper.ITypeMap that can handle this kind of scenario?

Thank you for trying to understand my problem.

Best regards,
Mihai M

**Comment by NickCraver** [comment]
The way you do this in Dapper is with a MultiMap, like this:
```c#
conn.Query<Company, Address, Bank, Contact, Company>(@"
Select Id, Address_Street as Street, Bank_Name as Name, Contact_Name as Name
From ... ", (company, address, bank, contact) => {
  company.Address = address;
  company.Bank = bank;
  company.Contact = contact;
  return company;
}, splitOn: "Id,Street,Name,Name");
```
The way it works is Dapper deserializes the child objects from what are typically joins to the relational tables but in this case the same table. Then you map the objects however they relate before returning the parent, the return type is an `IEnumerable<Company>` here (the last generic argument is the return type). Does that help?

**Comment by mihaimarin83** [comment]
Thank you for your help. I can't say I like this ideea but maybe is because I worked a lot with EF and this is first time when trying dapper (I'm not used to it yet). In my opinion it was very clean if I could had a mapper that could do this thing. Something like I wrote before:
Map(p => p.Bank.Name).ToColumn("Bank_Name");

It will be nice to have both posibilities implemented.

Is there any way we could implement something like this? I looked in the code (but i was first time seeing dapper code) I didn't saw a posibility to do that - maybe exists.
Do you see any reason to add this feature or is not what you want?

Thank you.

Best regards,
Mihai M

**Comment by NickCraver** [comment]
Apologies this was never follow-up on. The goals for Dapper are fast and lightweight - what's proposed here really involved query generation which is outside what Dapper aims to provide. I'd recommend checking out an ORM built on top of Dapper or EF Core for such a use case. It needs to issue multiple queries to not have repetitive, wasteful, discarded data in the tabular (which does ^n on *n expansions).

Hope that answers the intent for anyone finding this later :)
