### ISSUE TITLE
QueryAync<T> doesn't work with ReliableSqlConnection

### ISSUE THREAD

**Issue by yahor-stalnik** [StackExchange/Dapper#574]
### Steps to reproduce

code:

namespace AsyncDapperIssueReproducing
{
    using System.Data.SqlClient;
    using System.Threading.Tasks;
    using Dapper;
    using Microsoft.Practices.EnterpriseLibrary.TransientFaultHandling;

```
class Program
{
    static void Main(string[] args)
    {
        Test().Wait();
    }

    private static async Task Test()
    {
        const string connectionString = "Data Source=localhost;Initial Catalog=whateverDb;Integrated Security=True;";
        const string sqlQuery = "select top 1 [StringFieldForExample] from [VeryImportantTable]";

        using (var sc = new SqlConnection(connectionString))
        {
            var resultRc = sc.Query<string>(sqlQuery); // works fine
            var resultRcAsync = await sc.QueryAsync<string>(sqlQuery); // works fine
        }

        using (var rsc =
            new ReliableSqlConnection(connectionString, RetryPolicy.NoRetry, RetryPolicy.NoRetry))
        {
            var resultRsc = rsc.Query<string>(sqlQuery); // fine so far
            var resultRscAsync = await rsc.QueryAsync<string>(sqlQuery); // fail
        }
    }
}
```

}

dependecies:
`
  <package id="Dapper" version="1.50.2" targetFramework="net452" />
  <package id="EnterpriseLibrary.TransientFaultHandling" version="6.0.1304.0" targetFramework="net452" />
  <package id="EnterpriseLibrary.TransientFaultHandling.Data" version="6.0.1304.1" targetFramework="net452" />
`
### The issue

Can't read data async .

As I can see, Dapper (SqlMapper.Async.cs) get interface IDbConnection cnn and trying to cast it to (DbConnection)cnn. And, obviously, fails, because ReliableSqlConnection implements IDbConnection but not inherits from DbConnection.

```
Exception message: Unable to cast object of type 'Microsoft.Practices.EnterpriseLibrary.TransientFaultHandling.ReliableSqlConnection' to type 'System.Data.Common.DbConnection'.
Stack trace:    at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AsyncDapperIssueReproducing.Program.<Test>d__1.MoveNext() in c:\users\jr\documents\visual studio 2015\Projects\AsyncDapperIssueReproducing\AsyncDapperIssueReproducing\Program.cs:line 32
```

**Comment by mgravell** [comment]
Ultimately, though, this class doesn't provide the async API. There is no
point spoofing it - that would not help you: it would be "async over sync".

What would you have dapper do here? I could perhaps make the error message
more meaningful...

**Comment by yahor-stalnik** [comment]
Yes, I mean, it's not very obvious that method, which get interface rely on one of the implementations inside.

**Comment by trevorreeves** [comment]
I have recently come across the same issue.  It wasn't until we deployed to a QA environment and simulated an auto-failover scenario that we came across this issue.  Really, the compiler should be telling me this incompatibility right?  **Should these async extension methods actually be based on DbConnection rather than IDbConnection?** - that is the true dependency.

I am now considering the realisation that I must change all my connection references to `DbConnection` - my code base _only_ communicates via async methods - so whilst I am still using Dapper, pretending that I only depend on `IDbConnection `is in fact quite dangerous.

One option I am considering is wrapping `ReliableSqlConnection` in a class that inherits from `DbConnection`.  The implementation of the overriden methods (`OpenAsync `etc), can then just be rooted through to the `SqlConnection `object which is available via the `Current `property on `ReliableSqlConnection`.

**Comment by trevorreeves** [comment]
I won't pollute this thread anymore with my problems, but after a short investigation, my idea of wrapping ReliableSqlConnection with a wrapper that inherits from DbConnection is not possible; DbConnection has protected abstract methods (BeginDbTransaction, CreateDbCommand) which of course are not accessible from outside the SqlConnection class.  SqlConnection itself is sealed :-( 

I'm not seeing a way of using ReliableSqlConnection with Dapper Async methods.

**Comment by chilversc** [comment]
What if dapper added a custom `IAsyncConnection` interface that had the async methods? Then dapper could support async on `DbConnection` and `IAsyncConnection`. At least that way people could write their own adapters.

**Comment by AndyCJ** [comment]
As of .Net 4.6.1 SqlCOnnection includes retry logic itself: https://docs.microsoft.com/en-us/azure/sql-database/sql-database-connectivity-issues

So no need for ReliableSqlConnection any more.

**Comment by NickCraver** [comment]
A better error is thrown for this as of 1.50.5, closing out to cleanup!
