### ISSUE TITLE
Problem with Dapper + Simple WEB API service (ASP.NET Core)

### ISSUE THREAD

**Issue by aprilix** [StackExchange/Dapper#578]
Hi, we encountered a problem with the Dapper library. Our WEB API service works great without a link to the Dapper library. As you can see in the source code in the attachement, we added a breakpoint to the 17th line in "Values Controller", so we can check the value that is translated to the method. 

We call the method, as shown on the Pic below, and get a "value=null" (dapper link is ON).

But if we remove the link to Dapper in "project.json", the method gets the value as usual.

Can you please suggest, what can be the reason? Can this be due to Dapper changing the serialization somehow? 

P.S. Yes, we really DO need Dapper in out project.

Code Attach there: https://drive.google.com/open?id=0B_rh4dm2rzrOUlZ3UnJtRjJqam8
Test Parameters on picture
![image 08-02-17-0 08-02-18-12-34](https://cloud.githubusercontent.com/assets/6569034/17335084/6540afba-58e1-11e6-85d5-09000938eab3.png)

**Comment by mgravell** [comment]
Well that is odd. If dapper isn't involved in that code, then it can't
directly influence things. However, it is possible that the dependency tree
is causing an error internally. Is there a log of the actual exception
somewhere? And the inner-exception, etc? Also: exactly what version of
dapper are you using?

**Comment by liamsymonds** [comment]
@aprilix Would you be able to paste your controller file into a Gist (https://gist.github.com); I'm not too comfortable downloading a .rar file to take a quick peak.

**Comment by aprilix** [comment]
full project: https://github.com/aprilix/dapper-dot-net-issue-578
controller : https://github.com/aprilix/dapper-dot-net-issue-578/blob/master/testPostParameter/src/testPostParameter/Controllers/ValuesController.cs
project json: https://github.com/aprilix/dapper-dot-net-issue-578/blob/master/testPostParameter/src/testPostParameter/project.json

**Comment by aprilix** [comment]
Works ok with version 1.50.0-rc2b  :(

**Comment by NickCraver** [comment]
Look like a dependency issue long since resolved during the move to .NET Core. Closing out to cleanup.
