### ISSUE TITLE
SingleResult optimization breaks OleDb provider

### ISSUE THREAD

**Issue by StevenLiekens** [StackExchange/Dapper#583]
The following commit added an optimization for queries that return a single result set: ec3a1953a434f5bc91200c3380116994778633f4

Unfortunately, this optimization broke some of my code that uses `OleDbConnection`.

The problem seems to be that `OleDbDataReader` doesn't support `CommandBehavior.SingleResult`. A call to  `OleDbCommand.ExecuteReader(CommandBehavior.SingleResult)` does not throw any exceptions, but the resulting data reader has no data.

**Comment by benpittoors** [comment]
Maybe a bit more background information. We introduced dapper.net into a legacy application that we inherited from our ex-supplier (don't ask). Their way of making a database abstraction was to use an OleDbProvider instead of a db-specific one. They also had a code generated data layer to put on top of this that they called 'the {insertcompanynamehere} framework'. Anyways, since 'the framework' actually imposes very bad data access strategies we decided to gradually replace it by dapper. Or at the least introduce new features using dapper.

I don't know how you could go about fixing this erratic OleDbReader behavior in a elegant way.  In the mean time we (actually, Steven) replaced this specific case with plain old ADO.NET boiler plate code.

**Comment by mgravell** [comment]
Can you confirm which version you are using? I seem to recall having code
specifically to recover from this scenario. Also, the exact error message /
type would really help.

**Comment by StevenLiekens** [comment]
This affects all releases since 1.50-beta5, including the latest stable version (1.50.2). There is no error message, but the data reader reports that it has no data: `OleDbDataReader.Read()` returns `false`.

I looked at it a little closer and found that `CommandBehavior.SingleResult` breaks queries that perform a `DELETE`, `INSERT` or `UPDATE` before the `SELECT`. I also found that `SET NOCOUNT ON` fixes the problem for these queries.

I hope that helps.

**Comment by StevenLiekens** [comment]
# Example 
Here's a code example that works 100% of the time.

**SQL**
```sql
SELECT 1 foo, 2 bar, 3 baz;
```

**C#**
```c#
class Program
{
    static void Main(string[] args)
    {
        var sql = @"SELECT 1 foo, 2 bar, 3 baz;";
        using (var connection = new OleDbConnection(@"Data Source=.;Integrated Security=SSPI;Provider=SQLOLEDB"))
        {
            connection.Open();
            var cmd = new OleDbCommand(sql, connection);
            using (var reader = cmd.ExecuteReader(CommandBehavior.SingleResult))
            {
                Debug.Assert(reader.HasRows, "reader.HasRows == false");
                while (reader.Read())
                {
                    // Print the current row, tab delimited
                    Console.WriteLine(string.Join("\t", Enumerable.Range(0, reader.FieldCount).Select(ordinal => reader[ordinal])));
                }
            }
        }
    }
}
```

# Steps to reproduce
Now change the SQL to manipulate some data before doing a select.


**SQL**
```sql
DECLARE @values TABLE (foo int, bar int, baz int);
INSERT @values VALUES (1, 2, 3);
SELECT * FROM @values;
```

**C#**
```c#
class Program
{
    static void Main(string[] args)
    {
        var sql = @"DECLARE @values TABLE (foo int, bar int, baz int);INSERT @values VALUES (1, 2, 3);SELECT * FROM @values;";

        // Everything below this line is unchanged
        using (var connection = new OleDbConnection(@"Data Source=.;Integrated Security=SSPI;Provider=SQLOLEDB"))
        {
            connection.Open();
            var cmd = new OleDbCommand(sql, connection);
            using (var reader = cmd.ExecuteReader(CommandBehavior.SingleResult))
            {
                Debug.Assert(reader.HasRows, "reader.HasRows == false");
                while (reader.Read())
                {
                    // Print the current row, tab delimited
                    Console.WriteLine(string.Join("\t", Enumerable.Range(0, reader.FieldCount).Select(ordinal => reader[ordinal])));
                }
            }
        }
    }
}
```

# NOCOUNT
Enabling `NOCOUNT` magically fixes the problem.

**SQL**
```sql
SET NOCOUNT ON;
DECLARE @values TABLE (foo int, bar int, baz int);
INSERT @values VALUES (1, 2, 3);
SELECT * FROM @values;
```

**C#**
```c#
class Program
{
    static void Main(string[] args)
    {
        var sql = @"SET NOCOUNT ON;DECLARE @values TABLE (foo int, bar int, baz int);INSERT @values VALUES (1, 2, 3);SELECT * FROM @values;";

        // Everything below this line is unchanged
        using (var connection = new OleDbConnection(@"Data Source=.;Integrated Security=SSPI;Provider=SQLOLEDB"))
        {
            connection.Open();
            var cmd = new OleDbCommand(sql, connection);
            using (var reader = cmd.ExecuteReader(CommandBehavior.SingleResult))
            {
                Debug.Assert(reader.HasRows, "reader.HasRows == false");
                while (reader.Read())
                {
                    // Print the current row, tab delimited
                    Console.WriteLine(string.Join("\t", Enumerable.Range(0, reader.FieldCount).Select(ordinal => reader[ordinal])));
                }
            }
        }
    }
}
```

**Comment by mgravell** [comment]
Thanks, I really appreciate the repro. Will look.

**Comment by NickCraver** [comment]
@mgravell I think this is fixed, no? We back off on error detection now...I think this is a dupe that just needs closing, but wanted to confirm.
