### ISSUE TITLE
Use the type of the given object in Contrib DML methods

### ISSUE THREAD

**Issue by cremor** [StackExchange/Dapper#629]
Right now the Contrib methods `Insert`, `Update` and `Delete` (and their async versions) use the type of the given generic type paramter to get the table and properties. I suggest to change that so that the type of the given object (e.g. `entityToInsert.GetType()`) is used. That way the methods could be used when just an interface or base type of the type to save is known.

**Comment by NickCraver** [comment]
This would be a very large breaking change. What's the benefit over using the actual generic? You know the type because you're passing it in, can you give some examples where this would be beneficial?

**Comment by cremor** [comment]
I would have needed this when I implemented an interface method that looked something like `void SaveUpdates(SomeBaseClass obj)`. Changing the interface is no option since it is defined in a 3rd party library.

**Comment by NickCraver** [comment]
We can revisit this in v3 timeframe here - collapsing into #824 since it's just put another way and easier for me to understand the ask :)
