### ISSUE TITLE
MySQL: how to insert data into a JSON column?

### ISSUE THREAD

**Issue by kenhahn85** [StackExchange/Dapper#644]
Newbie question. I'm trying to insert JSON text into a MySQL JSON column.

I've tried `Dapper.SqlMapper.AddTypeMap(typeof(JsonObject<ChampionImage>), DbType.String)`, and other kinds of `DbType`, only to get the following exception:

```
System.NotSupportedException : Parameter type JsonObject`1 (DbType: String) not currently supported. Value: {"W":48,"Full":"Corki.png","Sprite":"champion0.png","Group":"champion","H":48,"Y":48,"X":336}
```

**Comment by NickCraver** [comment]
For anyone needing to do this, there's an example type handler addition here: https://stackoverflow.com/a/47065208/13249 - that's how you'd approach it for JSON columns :)
