### ISSUE TITLE
State of AppVeyor testing?

### ISSUE THREAD

**Issue by danzel** [StackExchange/Dapper#645]
Looking through the Pull Requests list it looks like AppVeyor hasn't been running since may, around the same time the `appveyor.yml` file was added.

Is it meant to still be running or has it been turned off on purpose?
Looks like the `appveyor.yml` file was added by @NickCraver in b3013525a4c0fcb8c706e8e9cf7b485a071f49da

also ref https://ci.appveyor.com/project/StackExchange/dapper-dot-net

**Comment by NickCraver** [comment]
Sorry I missed this - Appveyor is up, running, and testing every build now :)
