### ISSUE TITLE
Would like to see a Performance Test added for Webmatrix.Data

### ISSUE THREAD

**Issue by javis2** [StackExchange/Dapper#660]
It would be interesting to see how Webmatrix.Data database methods compare.

I would like to see a Performance Test added for it.

I appreciate that it's quite a different system of database access but a performance comparison would be useful to see how in/efficient it is.

**Comment by NickCraver** [comment]
My plan is to convert the benchmarks repo to use [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet), which should make adding additional comparisons as PRs much easier in the future. It's one of the many things that needs love and we have to find the time for. 

If anyone wants to take a crack at porting that I'd more than appreciate the effort. In fact, I'll create an issue and label up-for-grabs in a moment. I'm not sure about Webmatrix, I haven't looked at it at all. It may make no sense to compare, will have to dig in.

**Comment by NickCraver** [comment]
Benchmarks are now ported making this a lot easier. If someone wants to submit a PR that's apples:apples, I'll gladly pull it in :)
