### ISSUE TITLE
Is it possible to set [ExplicitKey] globally instead of using data annotations ?

### ISSUE THREAD

**Issue by SamMurray381** [StackExchange/Dapper#661]
My domain models are located in a separate project to my data access layer, all models have an Id property of type Guid. For Dapper.Contrib to work in my scenario I have to apply [ExplicitKey] to the Id property in each model - but this means that I have to add references to Dapper and Contrib in my domain layer, which I do not want to do ideally.

So, is there anyway of configuring this on a global level, so that I do not have to annotate my models with [ExplicitKey] ? 

I had a similar issue with table pluralisation, which I tackled by creating a base class that my repositories inherit from, like so: 

```c#
public class DapperBase
{
        public DapperBase()
        {
            // Set Dapper.Contrib to NOT pluralize table names
            SqlMapperExtensions.TableNameMapper = (type) =>
            {
                return type.Name;
            };
        }
}
```
```c#
 public class CompanyRepository : DapperBase, ICompanyRepository
 {
        protected IDbConnectionFactory _dbConnectionFactory;

        public CompanyRepository(IDbConnectionFactory dbConnectionFactory)
            :base()
        {
            _dbConnectionFactory = dbConnectionFactory;
        }
        
        // ... left out rest of class for brevity.
 }
```

**Comment by NickCraver** [comment]
This doesn't exist today, no. But it's not a bad idea for those that have a global convention. Dapper.Contrib needs *so much* love and cleanup - we just don't have the cycles yet.

Labelling this as a feature request, it's certainly useful. Dapper assumes`Id` for `splitOn` and such for example, so having this be configurable in `.Contrib` totally makes sense to me.

**Comment by NickCraver** [comment]
See #722, that's how we plan on handling this - closing this out since we're consolidating the planning there :)
