### ISSUE TITLE
Query with nested types in table

### ISSUE THREAD

**Issue by skendrot** [StackExchange/Dapper#663]
I have a table that was created with EF code first. My object looks something like:
```c#
public class User
{
    public int Id { get; set; }
    public string Name { get; set; }
    public Settings Settings { get; set; }
}

public class Settings
{
    public bool Option { get; set; }
    public string Value { get; set; }
}
```

The table looks like
User
`Id    |    Name    |    Settings_Option    |    Settings_Value`

So, the user and the settings are all in one table. When using Dapper, how can I get the query to return the user with the settings populated also? 

Thank you

**Comment by philn5d** [comment]
I've found the same. Worked around by adding properties to the User and set up the Settings prop based on that. You'll prob need to init the Settings prop in the ctor too. Maybe there's a better way, but I didn't find one in a reasonable time-frame. In the end I may have just ended up doing a flat data-bag anyways. I know you're prob thinking about reuse for kvp though. There was something I looked at - a typemap, wasn't quite patient enough to figure out if it fits this use case though.

**Comment by skendrot** [comment]
I should note that I know it can be accomplished by getting a dynamic object back and creating the settings myself with the known properties. I was wondering if there was a built in way to do this like there is in EF

**Comment by NickCraver** [comment]
I'm having trouble picturing the exact map here - can you show me the DDL for such a setup?

**Comment by skendrot** [comment]
Nothing special. It looks just like you think it would
```
Create table User (
    Id int PRIMARY KEY, 
    Name nvarchar(100) NOT NULL, 
    Settings_Option bit, 
    Settings_Value nvarchar(100))
```

I should also note that in my implementation the nested type is not at the end of the table. There are a few nested types in varying locations

**Comment by NickCraver** [comment]
@skendrot so there's 1 settings object per user? If it's 1:1 to rows, what you want is a Multimap query, like this:

```C#
var users = conn.Query<User, Settings, User>(@"
Select Id, Name, Settings_Option Option, Setting_Value Value 
  From User", 
  (u, s) => { u.Settings = s; return u; }, 
  splitOn: "Id,Option");
```

I'm not sure of your *exact* setup and how strange this looks, but it seems like a 1:many mutated in a 1:1, so without the exact setup I'm not sure what to *best* recommend here.

**Comment by NickCraver** [comment]
Closing this out to cleanup, proper approach noted above.

**Comment by skendrot** [comment]
Thanks @NickCraver. Forgot to close it out
