### ISSUE TITLE
Dapper Contrib Field Alias Attribute

### ISSUE THREAD

**Issue by gwestwater** [StackExchange/Dapper#670]
I would like to request there be a new field attribute called "Alias" or something similar to allow me to have the field name in the POCO object different than in the database. We do this with a simple alias when writing most queries but for updating this would be really helpful.

In our case we are doing this to fix a spelling error while upgrading software from one version to another. Once the transition to the new version is 100% complete we will change the field name in the database

**Comment by NickCraver** [comment]
Please see #722, this is indeed planned via either attributes or a mapping function (that the user has complete control of).

Closing this out just to consolidate, thanks for the suggestion and feedback - we'll indeed be implementing this functionality!
