### ISSUE TITLE
Isn't is possible to unify the project/package/etc. names? 

### ISSUE THREAD

**Issue by fuszenecker** [StackExchange/Dapper#683]
GitHub repo: dapper-dot-net
NuGet: dapper
NuGet title: Dapper dot net

**Comment by NickCraver** [comment]
I'm all for renaming the repo and NuGet Title personally. On GitHub though, will all the `/dapper-dot-net` refs alias correctly, or break? That's why we've been hesitant to change these...

**Comment by NickCraver** [comment]
Update: they *do* forward, @mgravell thoughts?

Redirect details: https://help.github.com/articles/renaming-a-repository/

**Comment by fuszenecker** [comment]
Thanks for the info, Nick, sounds great.

**Comment by NickCraver** [comment]
This is done for the next build - the repo has been renamed as well. Thanks for the action item!
