### ISSUE TITLE
Dapper.Contrib strong name nuget package

### ISSUE THREAD

**Issue by maggarwal** [StackExchange/Dapper#685]
Hi, 

There is no strongly named nuget package for Dapper.Contrib. Right now only solution is to actually copy the code from repo into my own code, which is hard to maintain.

**Comment by NickCraver** [comment]
We'll make sure Dapper and Dapper.Contrib are both strong named (without different packages for this) in v2. For now, you can use https://www.nuget.org/packages/Brutal.Dev.StrongNameSigner/ to do this during a build.

**Comment by damiangonzalez** [comment]
Nick, 
Thanks for the info. For now I've decided to compile the code into ours, but we will adjust as soon as signed assemblies are available from your team.

**Comment by mgravell** [comment]
We should just get this done. Very tempting to say "April 1st" simply for
the jollies, but no real reason we can't do sooner.

**Comment by NickCraver** [comment]
See #889 for an update here - collapsing so we're on the same issue.
