### ISSUE TITLE
About Query<T> Method Problem

### ISSUE THREAD

**Issue by cotide** [StackExchange/Dapper#692]
Daper is very flexible and convenient Minute ORM  ^_^ !
I like it !

I am using dapper  a problem 
------------------------------------------------------------------------
I use dapper [Query<T>]  Method 

```c#
public static IEnumerable<T> Query<T>(this IDbConnection cnn, string sql, object param = null, IDbTransaction transaction = null, bool buffered = true, int? commandTimeout = default(int?), CommandType? commandType = default(CommandType?));
```
![Image](http://ww1.sinaimg.cn/large/7c2c6ab7gy1fcedov7ebdj20m00azaae)

Error Info: 
------------------------------------------------------------------------
“System.InvalidOperationException”类型的异常在 Dapper.dll 中发生，但未在用户代码中进行处理
其他信息: An enumerable sequence of parameters (arrays, lists, etc) is not allowed in this context

**Comment by mgravell** [comment]
dapper normally uses named parameters; the typical usage would be:

    string name = ...
    ...conn.Query<T>("  ... where name=@name", new { name })...

I have no specific plans to support @0 etc.

**Comment by Cotide** [comment]
OK，Thanks~  I still hope to support uses @0,@1,@2... parameters ,I would like to integrate petapoco  [SQL Class](https://github.com/CollaboratingPlatypus/PetaPoco/blob/23a34d49b0c0ab74d04286174d8da9a1e1dc26b1/PetaPoco/Core/Sql.cs)

I used other methods to solve it!


![img1](http://ww1.sinaimg.cn/large/7c2c6ab7gy1fcj7irx4ymj20ia06v3ye)



![img3](http://ww1.sinaimg.cn/large/7c2c6ab7gy1fcj7keu786j20ge074jra)

![img5](http://ww1.sinaimg.cn/large/7c2c6ab7gy1fcj7qz8h9mj20hf089mx3)

![img2](http://ww1.sinaimg.cn/large/7c2c6ab7gy1fcj7l1qwobj20db07qdfp)


Thank you for your help~ ^_^

**Comment by NickCraver** [comment]
@Cotide What are you trying to do? It seems like you're doing a high-allocation way of doing `IN @Names`, where for example `Names` is an `IEnumerable<string>` and Dapper already makes it into `n` parameters.

**Comment by Cotide** [comment]
YES~ @NickCraver  Because,I want to use petapoco [SQL Class](https://github.com/CollaboratingPlatypus/PetaPoco/blob/23a34d49b0c0ab74d04286174d8da9a1e1dc26b1/PetaPoco/Core/Sql.cs)  As a parameter used for Dapper 。


![img](http://ww1.sinaimg.cn/large/7c2c6ab7gy1fconsqf3mtj20ea06yjrc)

I like its [LINQ syntax](https://zh.wikipedia.org/wiki/%E8%AF%AD%E8%A8%80%E9%9B%86%E6%88%90%E6%9F%A5%E8%AF%A2) very much !  


So in order for it to work, I made a parameter fit ~ ^_^

**Comment by NickCraver** [comment]
Looks like an adapter is in play for this custom scenario (which is what we'd recommend) - closing out to tidy up!
