### ISSUE TITLE
SqlMapperExtensions PostgresAdapter does not escape column names for primary key

### ISSUE THREAD

**Issue by colinbreame** [StackExchange/Dapper#698]
A table is created in Postgres like this:

```
CREATE TABLE Metric (
	"MetricId"		SERIAL,
	"Name"			VARCHAR(255),
	"CategoryId"	INT,
	"Type"			VARCHAR(255),
	"Text"			TEXT,

	PRIMARY KEY (MetricId)
)
```
When inserting the following SQL is created:

```
insert into Metric ("Name", "CategoryId", "Type", "Text") values ($1, $2, $3, $4) RETURNING MetricId
```

However in Postgres the columns names that are not escaped are lower cased.  So the column name MetricId does not equal "MetricId".  As my property name is "MetricId" this is causing an issue, as it is referred to inconsistently.

The suggestion solutions (as applied to PostgresAdapter) would be to escape the primary key column name.

**Comment by NickCraver** [comment]
This really depends on the user, but we want to make it much easier to configure and work in many scenarios in v2. Collapsing this into #722 fo discussion.
