### ISSUE TITLE
Does Dapper "publish" events and/or errors?

### ISSUE THREAD

**Issue by dahlsailrunner** [StackExchange/Dapper#710]
I am considering using Dapper and was wondering about exception handling.  I'd like to do something more globally that would include any parameters in the exception if, say, a stored proc threw a SqlException.  Is there any kind of event or global type of class that would enable me to do this without having to individually catch the exceptions at each Dapper method invocation?

Thanks in advance.

**Comment by NickCraver** [comment]
There isn't a place in the library, but you could for example make your own extension method for `.Execute()`/`.ExecuteAsync()`and wrap Dapper's there in a try/catch there - and you'll have access to all the parameters passed in.

**Comment by dahlsailrunner** [comment]
Thanks for the response -- I'll give it a shot and see how it works.  If I have good success and like the result, I'll post as a follow up comment in case others want to see this.

**Comment by dahlsailrunner** [comment]
So here's what I ended up with and it seems to work nicely.  Thanks for the input.

```csharp
public static class DapperExtensions
{
    public static int DapperProcNonQuery(this IDbConnection db, string procName, object paramList= null, IDbTransaction trans = null, int? timeoutSeconds = null)
    {
        try
        {
            return db.Execute(procName, paramList, trans, timeoutSeconds, CommandType.StoredProcedure);
        }
        catch (Exception orig)
        {
            var ex = new Exception("Dapper proc execution failed!", orig);                
            ex.Data.Add("ProcName", procName);
            AddParametersToException(ex, paramList);                
            throw ex;
        }
    }

    private static void AddParametersToException(Exception ex, object paramList)
    {
        if (paramList is DynamicParameters dynParams)  //C# 7 syntax
        {
            foreach (var p in dynParams.ParameterNames)
            {
                ex.Data.Add(p, dynParams.Get<object>(p).ToString());
            }
        }
        else
        {
            var props = paramList.GetType().GetProperties();
            foreach (var prop in props)
            {
                ex.Data.Add(prop.Name, prop.GetValue(paramList).ToString());
            }
        }
    }
}
```
