### ISSUE TITLE
Transaction not working on query

### ISSUE THREAD

**Issue by diogonc** [StackExchange/Dapper#713]
I can't use transaction on query as I use in execute method.

This code works fine:
```
using (var connection = new SqlConnection("<conectionString>"))
{
    connection.Open();
    var newTest = new Test("Text");
    using (var transaction = connection.BeginTransaction())
    {
        const string sql = "INSERT INTO Test (Text) VALUES (@Text)";

        connection.Execute(sql, newTest, transaction);

        transaction.Commit();
    }
}
```

but this doesn't work:

```
using (var connection = new SqlConnection("<conectionString>"))
{
    connection.Open();

    using (var transaction = connection.BeginTransaction())
    {
        var result =  connection.Query<Test>("select * from Test", transaction).AsList();

        transaction.Commit();

        return result;
    }
}
```

When I try to execute the query method with transaction I got this error: 

> System.InvalidOperationException: ExecuteReader requires the command to have a transaction when the connection assigned to the command is in a pending local transaction.  The Transaction property of the command has not been initialized.

I know I don't need a transaction for query in the second example, but how can I get the data inserted on the Execute method while the transaction is not commited yet?

**Comment by NickCraver** [comment]
I think you're just using the wrong overload there - try this: 
```c#
connection.Query<Test>("select * from Test", transaction: transaction).AsList();
```

**Comment by diogonc** [comment]
Sorry, my bad, its working now. Thanks

**Comment by SonOfSardaar** [comment]
In that case why is that even allowing user to use Query method without transaction when it cannot work without it ?

**Comment by mgravell** [comment]
@SonOfSardaar it *can* work just fine if there isn't a transaction.... in fact, I'd wager most queries are done outside of a transaction. Not sure what you're asking, to be honest...

**Comment by SonOfSardaar** [comment]
@mgravell i was asking because I am having issues using in a test, I am using connection.Execute to write data and in next I am using connection.query to fetch that data to verify. This is where i get the error that the Reader needs transaction

**Comment by mgravell** [comment]
if there is a transaction active *on the connection*, then yes: it needs to be supplied - but most of the time there just isn't. Have you opened a transaction? if so: you'll need to include that

**Comment by SonOfSardaar** [comment]
No i did not open any transaction. did both operations without transaction parameter

**Comment by SonOfSardaar** [comment]
ok @mgravell  i may have found an open transaction which was not supplied to anything. Thanks for your comments
