### ISSUE TITLE
Dapper Query Postgresql Jsonb Column To String

### ISSUE THREAD

**Issue by ange1ann** [StackExchange/Dapper#719]
Table Strucle Like This:
CREATE TABLE demo_json_data
(
     dataid serial NOT NULL PRIMARY KEY,
     datavalue jsonb NOT NULL DEFAULT '{}'
)

When Read From DataBase And Serialize to Json
It would like this:
 "msgparam": "{\"custInfo\": \"ABC\", \"entityId\": \"72de4051-a110-491a-bf12-1d69186b037c\", \"recordId\": \"ae468d9b-b8e7-4de9-aac2-80ab912176a4\", \"custEvent\": \"ADD\"}",

The Code Below
When I Use Dapper To Query The Data From Postgresql DataBase.

using (var conn = GetDbConnect(connectString))
{
   conn.Open();
   var tran = conn.BeginTransaction();
   result =conn.Query(commandText, parameters, commandType: commandType)
                            .Cast<IDictionary<string, object>>()
                            .ToList();
    tran.Commit();
 }

The Jsonb DataType is change to string In DapperRow
How Can I Change the Type To JObject When Meet the jsonb data.

**Comment by mgravell** [comment]
in the non-generic Query case, dapper just gives you whatever the
underlying provider hands back. if the underlying provider is giving a
string to thr library, then : it will appear as a string.

Options:

- see if there's a provider option to give the typed object rather than
string
- convert manually to WhateverType (insert your type name here)
- use the generic API, define a class with a WhateverType member, and add a
type handler for the WhateverType (I can give examples of this if needed)

**Comment by ange1ann** [comment]
Solution 1:define a class with a WhateverType member, and add a
type handler,

**Comment by ange1ann** [comment]
Solution 1:define a class with a WhateverType member, and add a
type handler
Solution 2: convert manually to WhateverType (JObject)  JObject is in Newton Lib.

Could you give me some examples to help me solved the problem?

**Comment by ange1ann** [comment]
Could there any possible solution?

**Comment by mgravell** [comment]
here's a full example of 2 (I'm using SQL-Server here, but it should work the same everywhere):

```
using Dapper;
using Newtonsoft.Json.Linq;
using System;
using System.Data;
using System.Data.SqlClient;
using static Dapper.SqlMapper;

// example runner
class Program
{
    static void Main()
    {
        SqlMapper.AddTypeHandler(JObjectHandler.Instance);
        using (var conn = new SqlConnection("Data Source = .; Database=tempdb;Trusted_Connection=True"))
        {
            conn.Open();
            var a = conn.QuerySingle<A>("select 123 as Id, '{foo:456}' as Json");
            dynamic d = a.Json;
            Console.WriteLine(d.foo); // writes 456
        }
    }
}
// dapper extension to implement JObject support
class JObjectHandler : TypeHandler<JObject>
{
    private JObjectHandler() { }
    public static JObjectHandler Instance { get; } = new JObjectHandler();
    public override JObject Parse(object value)
    {
        var json = (string)value;
        return json == null ? null : JObject.Parse(json);
    }
    public override void SetValue(IDbDataParameter parameter, JObject value)
    {
        parameter.Value = value?.ToString(Newtonsoft.Json.Formatting.None);
    }
}
// your DTO type that has a JObject member
class A
{
    public int Id { get; set; }
    public JObject Json { get; set; }
}

```

Note that 1 is simply a case of using `string` in your data-access code and then using `JObject.Parse` afterwards.

**Comment by ange1ann** [comment]
Thanks for your help!

The sql command text is dynamic combine by different logical.

Such as 
"SELECT id(uuid type),viewconfig(json type),fieldconfig(json type) FROM TableA"
"SELECT dataid(int type),deptrule(json type),powercontrol(json type) FROM TableB"

The columns could be change always,
so I use this code to return Dictionary Type Data List,Not Extract The Class A Type Define.

conn.Query(commandText, parameters, commandType: commandType)
.Cast<IDictionary<string, object>>();

The difficulty is how to change the string type to JObject.
If I get the result and foreach the datalist to use JObject.Parse and set value back,
It would not be common,and it must deal with all the Sql which has json type column.

So I want to deal this in query method, reading data and have a handler to change the string to JObject when the column is json db type.

**Comment by mgravell** [comment]
right; and in pure ado.net terms: how does it know that it is meant to be
json? i suspect that the provider just says it is a string. Is there
alanything in ado.net that you could use to identify the json columns,
given just the reader?
