### ISSUE TITLE
consider add TableName in Dapper.Contrib's operations

### ISSUE THREAD

**Issue by egmkang** [StackExchange/Dapper#721]
i have one table splited into many tables.
for example: `player_0`, `player_1` .... `player_N`, which are all `Player` Table.

in this case, how can i use Dapper in my project?

**Comment by Adondriel** [comment]
Dapper.Contrib already supports the key [Table("TableName")] above the class definition, can you describe your situation more? Why would you split multiple data items of the same type, into multiple tables, if they don't have varying data? This sounds more like a DB Design issue, than a Dapper support issue.

**Comment by NickCraver** [comment]
No information to go off here, and agree with @Adondriel's assessment above. Closing out to cleanup.
