### ISSUE TITLE
Dapper (or extension) is support sql statement template engine?

### ISSUE THREAD

**Issue by chinaniit** [StackExchange/Dapper#729]
I have requirement, like this:
`select * from tableA
where 1=1
@@if(@A != null){
     and A = @A
}`
Thanks.

**Comment by NickCraver** [comment]
Can you explain a little more about what you're after? I'm not sure what to make of the example...isn't that just assembling the string? There is `Dapper.SqlBuilder` (on NuGet) which *seems* to be closer to what you're after.

**Comment by chinaniit** [comment]
As a sql template engine:
select * from tableA where 1=1 @@if(@A != null){ and A = @A }
if @A as false, generate sql
select * from tableA where 1=1

**Comment by NickCraver** [comment]
The functionality Dapper provides here is *similar* but not in a template language style (as this would be ripe for accidental SQL injection attacks in general). See `Dapper.SqlBuilder` for a safer way of going about this :)
