### ISSUE TITLE
Trouble setting values

### ISSUE THREAD

**Issue by dbol55** [StackExchange/Dapper#736]
```
var orders = dapper.Query("SELECT * FROM dbo.Orders");

foreach (var item in orders)
{
        item.MyBool = false; // exception
        item.MyBool = false as object; // ok
}
```

It would be nice to be able to set values as first line.

**Comment by mgravell** [comment]
what is the exception?

**Comment by dbol55** [comment]
An unhandled exception of type 'System.ArgumentException' occurred in System.Core.dll

Additional information: You cannot use expression of type System.Boolean for parameters 
of type System.Object in method System.Object SetValue(System.String, System.Object)

**Comment by NickCraver** [comment]
@dbol55 Which version of .NET are you hitting this on?

**Comment by NickCraver** [comment]
Closing to fold into #749 - same issue and we've for a discussion with cause going there.

**Comment by dbol55** [comment]
4.5.2
