### ISSUE TITLE
to export directly JSON?

### ISSUE THREAD

**Issue by stefan2410** [StackExchange/Dapper#738]
We have many queries that we don't need to process their responses in the controllers, before we send them out. If it was possible to convert in Json the DapperTable  and send it out as string, it would be more flexible and  much faster also, I think.
If you had a Dapper type  for example : 

                                        public class  DapperJson
                                         {
                                             public string Json { get;}
                                             //and maybe  metadata, e.g. rows count, field names, etc
                                             public Dictionary<string,object> metadata {get;}
                                          }
we could call    DapperJson result = await Connection.QueryAsync< DapperJson >(sql, request);
without  a fear of mistake  and very easily we would be able to change it for typed responses, according to use case.
As for the Json serializer, maybe with dependency injection, we could declare what we are using?

**Comment by mgravell** [comment]
I'm not convinced that we'd save anything here - if we're allowing the
external caller to supply a library, then we need to prepare *pretty much*
the same thing as we already have. What I'd rather focus on is looking at
making sure that DapperRow is compatible with one or more JSON libraries (
JSON.NET, Jil, etc). That shouldn't be much more than implementing
`IDictionary<string,object>`, which I *think* we already do. I will have a
look, though.

**Comment by stefan2410** [comment]
DapperRow is compatible (at least with JSON.NET) as I convert them, extensively,  with extension methods.
One thing is possible gains in performance, if  result is json (overall, including the cost of external serialization). 
You know better than me, what you could succeed or not.
