### ISSUE TITLE
Handle table names for entities that end in letter 's'

### ISSUE THREAD

**Issue by Caltor** [StackExchange/Dapper#744]
If an Entity doesn't have a [Table] attribute then GetTableName() (Dapper.Contrib/SqlMapperExtensions.cs line 272) tries to work it out by adding the letter 's' to the end of the Entity name. So 'Item' becomes 'Items' and 'Product' becomes 'Products' etc. This works great until we come to words that end with the letter 's', 'Status' for example becomes 'Statuss' rather than Statuses'. Could you tweak the GetTableName method please so it can handle this better. I can't think of any other words that end in 's' off the top of my head but I think they would all add 'es' to the end of the singular to make the plural.

I know there is some debate (https://english.stackexchange.com/q/877/11005) over whether the plural of Status is Status or Statuses.

**Comment by NickCraver** [comment]
Check out https://github.com/StackExchange/Dapper/issues/722 - we aim to solve this issue once and for all that way, by eliminating the guessing.

**Comment by Caltor** [comment]
Hi Nick
Thanks for the reply and nice work. If I understand that Issue correctly it would still fallback to the default tablemapper so I think there is still merit in resolving this Issue. Or are you saying [Table] attribute would then become mandatory on all entities? Out of interest I think EF has a pluraliser built in. Could we plagiarise that for Dapper to solve this Issue?

**Comment by Caltor** [comment]
Looks like someone has already extracted the pluralizer from EF https://github.com/eduaquiles/PluralizationService

**Comment by NickCraver** [comment]
We could for example default to how EF works, or provide it as one of the built-in functions. Things like underscore naming, pluralizers, title or camel case....all would be fair game as readily available defaults to use with 1 line of code.

Thoughts?

**Comment by Caltor** [comment]
Sounds interesting. Can you expand on what you mean or how this would work please. Would this have to wait until Dapper 2? I think it would be good to at least improve the pluralization in the current version.

**Comment by NickCraver** [comment]
@Caltor yes it'd have to wait until v2 (Marc and I are wrapping up several other large projects atm) - how do you propose we improve it for the current version? The problem there is any change I can imagine (correct me!) is a breaking one - so that's a major version change we have to make as responsible maintainers. That's the main impetus for all of the table/column planning in v2.

**Comment by Caltor** [comment]
I was just thinking a simple `if (last char == 's') add 'es'` but I guess that **could** be a breaking change, although I imagine anyone who has encountered it previously would have used a [Table] attribute rather then munging their tablenames with a double 's' at the end....

**Comment by NickCraver** [comment]
It's by definition a breaking change :) Never make assumptions, especially with so many users in play...you'll always be surprised, and let down with reality.

**Comment by Caltor** [comment]
Haha the voice of experience! I'm looking forward to seeing what comes out of v2 then :)

**Comment by NickCraver** [comment]
Closing this out to consolidate everything on the mappings into #722!

**Comment by NickCraver** [comment]
@Caltor it's just not a good user experience to add a flag we immediately intend to break in #722 with an overall solution. It makes for a poor upgrade experience, where as `[Table("name")]` will continue to work.
