### ISSUE TITLE
String gets wrongly converted into GUID

### ISSUE THREAD

**Issue by AndyBehr** [StackExchange/Dapper#755]
The field in the table is defined as a fixed length char(36) and now I have the problem that dapper converts them into GUIDs. But they are not GUIDs...

How can I tell Dapper not to do this? 

Table:
> **'parentLink' char(36) DEFAULT NULL**,
> **'customerLink' char(36) DEFAULT NULL**

This does work but is wrong:
```
        public Guid parentLink {get;set;}
        public Guid customerLink {get;set;}
```

This does not work:
```
        public string parentLink {get;set;}
        public string customerLink {get;set;}
```

Why is this a big problem? Because this is an example of the content in the db:
`parentLink: 8a99e69f5552c5a90155536d6b7c0032`
But the string representation of the GUID is: 8a99e69f-5552-c5a9-0155-536d6b7c0032

Plus the data sometime is just a short string like 'kjo8hlkuhsdf'

**Comment by mgravell** [comment]
a: what package version are you using

b: is it just "dapper" in the mix? Or are you using addition tools like
dapper contrib?

c: are you very sure it is dapper doing this and not something else in your
processing?

d: any chance we can see an illustration of how you use dapper at this
point?

**Comment by AndyBehr** [comment]
> a: what package version are you using

```
<PackageReference Include="Dapper" Version="1.50.2" />
<PackageReference Include="Dapper.Contrib" Version="1.50.0" />
```

> b: is it just "dapper" in the mix? Or are you using addition tools like
dapper contrib?

While the project does include Dapper.contrib my actual source code does not as of right now.

> c: are you very sure it is dapper doing this and not something else in your
processing?

It is a brand new project, nothing else has been programmed yet. So I am very sure it is Dapper.

> d: any chance we can see an illustration of how you use dapper at this
point?

An illustration? Here is the code.
HeartbeatData as seen in my first post. Also tried it with dynamic bindings. 

```csharp 
using (MySqlConnection conn = new MySqlConnection(connectionString)) {

    try {

        string query = @"
            SELECT  
                parentLink,
                cutomerLink
            FROM containers;";
        //var rows = conn.Query(query);
        var rows = conn.Query<HeartbeatData>(query);

        foreach (var row in rows) {
            Console.WriteLine(row.parentLink); // << This is now a GUID, it should be a string
        }

    } catch (Exception e) {
        ...
    }
}
```

**Comment by manigandham** [comment]
To be clear: You're using `char(36)` in MySQL to store actual strings, not GUIDs, but when using Dapper it's acting like they're GUIDs automatically?

This is because the mysql.data adaptor is programmed to automatically do this, see this for more info:
http://stackoverflow.com/questions/12976303/what-column-type-of-mysql-will-return-as-system-guid-in-c-sharp

This isn't anything to do with Dapper which is really just a light wrapper around the base ADO.NET client drivers. In this case, it's a series of bad planning and implementation by the mysql.data driver. You can check that page to see what options work for you, although switching to `varchar` might be the easiest if the data is really just strings.

**Comment by AndyBehr** [comment]
Yes, char(36) in MySQL, they are ID strings but not GUIDs. (Don't ask, long story)

What a silly assumption of the database driver.... 
I got around it by forcing the driver into old guid mode as explained in the link you mention.

I have no option right now to change the char(36) to varchar, let's hope this fix will work long term.

Thanks, for pointing me in the right direction.
