### ISSUE TITLE
SqlException on INSERT when IDENTITY property is of type LONG

### ISSUE THREAD

**Issue by blackf0rk** [StackExchange/Dapper#759]
When executing an `Insert<T>(T obj)` the following exception is thrown...

`Cannot insert explicit value for identity column in table 'Mindfulness' when IDENTITY_INSERT is set to OFF.`

My model looks like this...

```
public partial class Mindfulness
{
    [Key]
    public long MindfulnessId { get; set; }
    public string Content { get; set; }
    public System.DateTime Posted { get; set; }
}
```

`Get` and `Update` both work, but the `Insert` fails. When I change the `MindfulnessId` type to `int`, then the `Insert` will work.

**Comment by manigandham** [comment]
What is the table schema?

That error means you're trying to insert an actual number for that column but it's set to be an autoincrementing identity column which is generated by the database on insert.

**Comment by RezaAb** [comment]
Hi.
You're inserting values for MindfulnessId that is an identity column.
You can turn on identity insert on the table like this so that you can specify your own identity values.

```
SET IDENTITY_INSERT Table1 ON
INSERT INTO Table1
/*Note the column list is REQUIRED here, not optional*/
            (OperationID,
             OpDescription,
             FilterID)
VALUES      (20,
             'Hierachy Update',
             1)
SET IDENTITY_INSERT Table1 OFF 
```

or you can use this:

```
SET IDENTITY_INSERT [yourTableName] ON

--go back and run your C# code>

SET IDENTITY_INSERT [yourTableName] OFF
```
