### ISSUE TITLE
QueryAsync only has 7 type parameters

### ISSUE THREAD

**Issue by arrkaye** [StackExchange/Dapper#761]
I need 9 for a large query with multiple joins. Is there a way?

**Comment by NickCraver** [comment]
Until 2.0 (where we'll use tuples - see #745), you can use the `n` types overload to get as many as needed:
```c#
public static Task<IEnumerable<TReturn>> QueryAsync<TReturn>(this IDbConnection cnn, string sql, Type[] types, Func<object[], TReturn> map, object param = null, IDbTransaction transaction = null, bool buffered = true, string splitOn = "Id", int? commandTimeout = null, CommandType? commandType = null)
```
See #745 for how we're making this unbounded and cleaner thanks to Tuples in C# 7.

**Comment by NickCraver** [comment]
Closing this out since the workaround is posted above :)

**Comment by jacob-winkler** [comment]
Any examples of this overloads usage? Seems to be exactly what I need but I'm struggling to use it correctly

**Comment by mohit-torani** [comment]
The read has 7 parameters limit can it be bypassed?

**Comment by frs-LinkLog** [comment]
An example of usage. Working. 

            var types = new Type[] { 
                typeof(CaseRecordEntity),
                typeof(CaseRecordTypeEntity),
                typeof(CaseRecordStatusEntity), 
                typeof(CaseRecordPriorityEntity),
                typeof(CaseRecordServiceDetailsEntity),
                typeof(CaseRecordInfoEntity), 
                typeof(CaseRecordClaimAddressEntity),   
                typeof(CaseRecordClaimDetailsEntity) 
            };
            Func<object[], CaseRecordEntity> map = objects =>
            {
                var caseRecord = (CaseRecordEntity)objects[0];
                caseRecord.case_record_type = (CaseRecordTypeEntity)objects[1];
                caseRecord.case_record_status = (CaseRecordStatusEntity)objects[2];
                caseRecord.case_record_priority = (CaseRecordPriorityEntity)objects[3];
                caseRecord.case_record_service_details = (CaseRecordServiceDetailsEntity)objects[4];
                caseRecord.case_record_info = (CaseRecordInfoEntity)objects[5];
                caseRecord.case_record_claim_address = (CaseRecordClaimAddressEntity)objects[6];
                caseRecord.case_record_claim_details = (CaseRecordClaimDetailsEntity)objects[7];
            
                return caseRecord;
            };
            
            var caseRecords = await _connection.QueryAsync(CaseRecordQueries.GetAllCaseRecords, types, map, _transaction, 
                splitOn: "id, case_record_type_id, case_record_status_id, case_record_priority_id, service_details_id, case_record_id, claim_address_id, claim_details_id");

**Comment by ronnow1000** [comment]
Example of using more than 7 type parameters

            var types = new Type[] { 
                typeof(CaseRecordEntity),
                typeof(CaseRecordTypeEntity),
                typeof(CaseRecordStatusEntity), 
                typeof(CaseRecordPriorityEntity),
                typeof(CaseRecordServiceDetailsEntity),
                typeof(CaseRecordInfoEntity), 
                typeof(CaseRecordClaimAddressEntity),   
                typeof(CaseRecordClaimDetailsEntity) 
            };
            Func<object[], CaseRecordEntity> map = objects =>
            {
                var caseRecord = (CaseRecordEntity)objects[0];
                caseRecord.case_record_type = (CaseRecordTypeEntity)objects[1];
                caseRecord.case_record_status = (CaseRecordStatusEntity)objects[2];
                caseRecord.case_record_priority = (CaseRecordPriorityEntity)objects[3];
                caseRecord.case_record_service_details = (CaseRecordServiceDetailsEntity)objects[4];
                caseRecord.case_record_info = (CaseRecordInfoEntity)objects[5];
                caseRecord.case_record_claim_address = (CaseRecordClaimAddressEntity)objects[6];
                caseRecord.case_record_claim_details = (CaseRecordClaimDetailsEntity)objects[7];
            
                return caseRecord;
            };
            
            var caseRecords = await _connection.QueryAsync(CaseRecordQueries.GetAllCaseRecords, types, map, _transaction, 
                splitOn: "id, case_record_type_id, case_record_status_id, case_record_priority_id, service_details_id, case_record_id, claim_address_id, claim_details_id");
