### ISSUE TITLE
NullReferenceException when quoted colon in SELECT clause

### ISSUE THREAD

**Issue by atkulp** [StackExchange/Dapper#765]
I get a NullReferenceException when I execute a SELECT that includes a quoted colon (':').  This is in ServiceStack, via OrmLite.  The exception occurs at:
 	`ServiceStack.OrmLite.dll!ServiceStack.OrmLite.Dapper.CommandDefinition.SetupCommand(System.Data.IDbConnection cnn, System.Action<System.Data.IDbCommand, object> paramReader)`

The query can be as simple as:
`"SELECT ':'"`

The actual exception appears to be within a dynamic method so I can't debug any further:
`paramReader?.Invoke(cmd, Parameters)`

The other part is that the params has a null TVP property.  I see another issue related to TVP exceptions, but this doesn't not cause an issue unless there is also the colon in the query.

I can resolve the issue by either 1) replacing the colon with a different character, or 2) replace the null TVP with an empty TVP (correct schema but no data).

**Comment by atkulp** [comment]
Has anyone had a chance to check into this bug?

**Comment by NickCraver** [comment]
@atkulp Do you have an example here? The eor isn't in Dappe directly, and I have no idea which version of Dapper appears to be embedded there...

**Comment by NickCraver** [comment]
Closing out, as not enough info to go on here.
