### ISSUE TITLE
What would be the recommended replacement in dapper for entlib's UpdateDataset()?

### ISSUE THREAD

**Issue by StingyJack** [StackExchange/Dapper#768]
Enterprise library has a set of [functions](https://msdn.microsoft.com/en-us/library/bb748738.aspx) to "batch" statements to stored procedures/commands. 

Is there a suitable replacement in dapper for this that _should_ perform as well? I'm only seeing examples of "one at a time" processing and not batched inserts or updates, and would like to know what I should use for performance comparisons.

**Comment by NickCraver** [comment]
You can pass enumerables to methods in Dapper to execute a command multiple times, which works for inserts and such. But if you're after the highest performance for mass inserting, you're talking BulkInsert territory, which is available, but not a feature of Dapper.

**Comment by StingyJack** [comment]
Fast, yes. but I'm not looking for the classic "Bulk Copy Program" style of bulk inserts. Just something that does this... 
```
{open conn)
INSERT INTO Table (ColA, ColB, ...) VALUES ('ABC', 'DEF', ...)
INSERT INTO Table (ColA, ColB, ...) VALUES ('AAD, 'DES', ...)
INSERT INTO Table (ColA, ColB, ...) VALUES ('QSR', 'DDF', ...)
INSERT INTO Table (ColA, ColB, ...) VALUES ('BBC, 'AEF', ...)
{close conn)
```
...instead of this...
```
{open conn)
INSERT INTO Table (ColA, ColB, ...) VALUES ('ABC', 'DEF', ...)
{close conn)
{open conn)
INSERT INTO Table (ColA, ColB, ...) VALUES ('AAC', 'DASF', ...)
{close conn)
```
...where that simple batching is the difference of a few thousand inserts a minute. 

I think I found the answer in the [Database.cs](https://github.com/StackExchange/Dapper/blob/master/Dapper.Rainbow/Database.cs), where statements appear to be one-at-a-timed at the connection. If you could confirm that's the right place, i would appreciate it. 

I know EntLib.Data is more or less dead, but I haven't found anything that can top that without a ton of tuning.

**Comment by NickCraver** [comment]
Off I missed the reply here - yep that is the answer. Or, consider using a table valued parameter (TVPs) for SQL Server if that's your target :)

**Comment by StingyJack** [comment]
Yeah, TVP's and a proper SQL MERGE statement are the fastest way to go outside of BCP, and Dapper + a little codegen i have for Entity collection -> Datatable makes this an ez-pz option
