### ISSUE TITLE
Re: Microsoft Security Advisory 4021279

### ISSUE THREAD

**Issue by johnkors** [StackExchange/Dapper#771]
Hi,

re https://github.com/dotnet/corefx/issues/19535. 

The latest available Dapper nuget (1.50.2) has a dep on  `System.Data.SqlClient/4.1.0` , which as a transient dep to  `System.Net.Security/4.0.0` - which is mentioned in the above security annoncement. 

I see master is on `System.Data.SqlClient/4.3.0`, which also looks affected.

Should Dapper be updated..? Want a PR?

**Comment by NickCraver** [comment]
Fixed in d72ae17a22ebb408d947843ad58fce512eff74e8, but it'll return as `4.3.1` in `netstandard2.0` due to needed APIs for UDTs and TVPs. Once I get `netstandard2.0` up, we'll get another alpha on NuGet.
