### ISSUE TITLE
Is there a way to pass a Table-Valued Parameters to dapper on .Net Core right now?

### ISSUE THREAD

**Issue by mbuntic** [StackExchange/Dapper#780]

**Comment by NickCraver** [comment]
Not yet. Hopefully it'll work in `netstandard2.0` (which we have a branch for already). They're working on these bits right now over in https://github.com/dotnet/corefx/issues/17126 and related issues.

**Comment by sergiivolchkov** [comment]
@NickCraver table-valued parameters based on IEnumerable<SqlDataRecord> seem to work just fine on .net core 1.x. I have tried to remove the corresponding conditionals and added a couple of tests: https://github.com/StackExchange/Dapper/pull/801.

@mbuntic in the meantime you can implement SqlMapper.ICustomQueryParameter for your TVPs as shown here: https://github.com/StackExchange/Dapper/blob/61e965eed900355e0dbd27771d6469248d798293/Dapper.Tests/Tests.Parameters.cs#L111 (the test works on .net core 1.x).

**Comment by NickCraver** [comment]
As soon as we get a new preview release on NuGet for SqlClient, we can merge this down into `master` - just waiting on that team to give us an updated lib to `netstandard2.0` tests pass.

**Comment by NickCraver** [comment]
TVPs are now in the latest alpha (both for `netstandard1.3` and `netstandard2.0`, please give it a try and let me know if you hit any issues: https://www.nuget.org/packages/Dapper/1.50.4-alpha1-00070

**Comment by NickCraver** [comment]
Dapper 1.50.4 is now out on NuGet, closing this out to cleanup: https://www.nuget.org/packages/Dapper/1.50.4
