### ISSUE TITLE
Support for SqlXml data type

### ISSUE THREAD

**Issue by Steveiwonder** [StackExchange/Dapper#783]
Hey All,

Do we have any support for SqlXml data type? How do we pass in this type to a SP using Dapper?

Thanks

**Comment by dimzon** [comment]
```
var paramObject = new { xmlParam = new XElement("hello","world"), intParam=1 };

```

**Comment by NickCraver** [comment]
@Steveiwonder It looks like @dimzon has you covered with an example there - does that give you enough info?

**Comment by Steveiwonder** [comment]
Perfect, thanks guys.
