### ISSUE TITLE
dotnet core 2 support

### ISSUE THREAD

**Issue by ipinak** [StackExchange/Dapper#787]
How probable is it that Dapper will compile (and work) for **dotnet core 2 preview 1**?

I need to use the updated version of `SqlClient`?

**Comment by NickCraver** [comment]
Dapper already supports `netstandard` in the current releases - so you can use it today. The `netstandard2.0` build will just add some functionality back (DataTables, TVPs, possibly UDT parameters) when Microsoft gets the APIs in place. I've relayed lots of missing bits the the `System.Data` team and they're working hard on getting a bunch of APIs back in for the 2.0 release.

TL;DR: You can use it today. If you upgrade after the 2.0 release, there will be some additional functionality.

**Comment by chenzuo** [comment]
yes！

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ipinak** [comment]
I can verify that it works fine.
