### ISSUE TITLE
Question - Can Dapper partially populate a class?

### ISSUE THREAD

**Issue by Korporal** [StackExchange/Dapper#788]
Does Dapper provide a means to partially populate a class when it does a SELECT?

I'd like to have a class, say Dissertation that contains many members. Then be able to execute Dapper queries but pass a sequence of property name - these being the only properties that I want it to retrieve.

Is this possible? 

This would enable us to always refer to established standardized classes in our systems, yet not burden every app with the cots of always populating every property.

Thanks

**Comment by NickCraver** [comment]
Yep - that's the default behavior. If you have properties A, B, C, D, E and F but only do a `SELECT A, B, C FROM...`, then you'll get an object with only those 3 populated. The remaining properties will be whatever their defaults are. It's the same behavior as doing  a `new MyClass();` and assigning only the A, B, and C properties.
