### ISSUE TITLE
Is there a way of dapper converting a list (for a IN) to varchars rather than nvarchars?

### ISSUE THREAD

**Issue by tbertenshaw** [StackExchange/Dapper#789]
we have a varchar column which we are doing a  SQL `In` on 
(i.e.  .... `Where mytable.mycolumn IN ('one','two','three')`) 
so we pass in a ExpandoObject, (with one of the values being a string array) to the dapper Query. Dapper nicely generates a list of variables but defines them as nvarchar. is it possible to specify or convert them to varchars?

as per https://github.com/StackExchange/Dapper#ansi-strings-and-varchar

**Comment by huchim** [comment]
You use `DbString.IsAnsiDefault = true;` before you query.

I'm not able to check if it's works but in the code I found this:

```csharp
public sealed class DbString : SqlMapper.ICustomQueryParameter
{
    public static bool IsAnsiDefault { get; set; }

    public DbString()
    {
        Length = -1;
        IsAnsi = IsAnsiDefault;
    }
}
```

**Comment by mgravell** [comment]
Messing with the static property probably isn't a great idea. I wonder if a `List<DbString>` would work? I genuinely can't remember without trying it, but that would be the thing to try, IMO

**Comment by huchim** [comment]
```csharp
var sql = "SELECT * FROM Employees WHERE EmployeeId IN @EIDList";

var m = this.connection.Query(
    sql,
    new
    {
        EIDList = new List<DbString>()
        {
            new DbString { IsAnsi = true, Value = "DA227" },
            new DbString { IsAnsi = true, Value = "DA225" },
        },
    })
```

The code above works ok, but I think it's more code than using the `IsAnsiDefault`.

A `DynamicParameters` instance could be more useful 

```csharp
var p = new DynamicParameters();
// ERROR: Not mapped String[]... :/
p.Add("values", new[] { "DA227", "DA225" }, dbType: DbType.AnsiString);
```

**Comment by mgravell** [comment]
more work, yes; but also less likely to cause a massive thread race problem
with differebt bits of code arguing over what the value should be and theb
failing because another thread changed it nanoseconds later

**Comment by huchim** [comment]
I finally understand what you said about "thread race problem" (`IsAnsiDefault`). 😆 

There're a static property in `DbString` class but it could be more problematic to use it (as @mgravell said). You can write a function to "convert" your string array to `DbString`.

Example:

```csharp
private IEnumerable<DbString> GetAnsiStrings(string[] strings)
{
    strings = strings ?? throw new ArgumentNullException(nameof(strings));

    foreach (var ansiString in strings)
    {
        yield return new DbString { IsAnsi = true, Value = ansiString };
    }
}
```

then 

```csharp
var sql = "SELECT * FROM Employees WHERE EmployeeId IN @EIDList";
var m = this.connection.Query(sql, new { EIDList = GetAnsiStrings(new string[] { "DA227", "DA225" } });
```

Just a suggestion.

**Comment by abhisheksaxena741** [comment]
HI,

Please suggest how to do the same using stored procedure.

**Comment by mgravell** [comment]
If you're using a stored procedure, the logic needs to go *in your stored
procedure*. You have at your disposal (depending on your RDBMS):

- string tools like string_split
- table-valued-parameters
- XML/JSON parsing

Dapper can't do anything except invoke it. That's how stored procedures
work.

**Comment by NickCraver** [comment]
For anyone finding this later, see `List<DbString>` above - that's the route :)
