### ISSUE TITLE
Allow table name to be passed as method parameter

### ISSUE THREAD

**Issue by Caltor** [StackExchange/Dapper#797]
It would be useful to be able to pass the table name into the Dapper.Contrib methods. For example:
```
Connection.GetAll<Person>("Employees");
Connection.GetAll<Person>("Managers");
Connection.GetAll<Person>("Directors");
```

This is a contrived example for illustration so please don't respond by saying the data shouldn't be structured like this etc.

This would allow the reuse of a single model for multiple tables. At the moment it is necessary to create a model just to add the [Table] attribute for models that have identical structure,

**Comment by NickCraver** [comment]
A reasonable optional parameter I think - can you please add comments in #722 on the overall discussion for v2 there?

**Comment by NickCraver** [comment]
Closing this out since discussion has moved to #722 - getting it all in one place.
