### ISSUE TITLE
DapperRow must implement ICustomTypeDescriptor

### ISSUE THREAD

**Issue by dimzon** [StackExchange/Dapper#805]
Otherwize it's impossible to bind `List<dynamic>` to DataGridView

```
            using (var cn=Db.NewSqlConnection())
            {
                var arr = cn.Query<dynamic>("select * from Subj").AsList();
                var obj = arr[0] as ICollection<KeyValuePair<string, object>>;
                foreach (var keyValuePair in obj)
                {
                    dataGridView1.Columns.Add(new DataGridViewTextBoxColumn
                    {
                        DataPropertyName = keyValuePair.Key,
                        HeaderText = keyValuePair.Key

                    });
                }
                dataGridView1.DataSource = arr;
            }
```

**Comment by dimzon** [comment]
PS. Or maybe even better to generate "real" class with pubic properties so they will be accesible via reflection etc... I mean to generate class wich implements dynamic but have same real properties.

**Comment by mgravell** [comment]
Interesting idea. I've done a **lot** of work with custom descriptors in the past, so the idea is very familiar - although it feels somewhat rare these days. However, the beat approach here is actually `ITypedList`, since that will allow empty lists to bind correctly. 

Re generating real classes: for that solution, I strongly suggest that the **caller** should do this and use the generic overload of `Query<T>`. The dynamic version should IMO remain dynamic.

**Comment by dimzon** [comment]
For generating classes **you can inherit generated classes from DynamicObject to keep best of two worlds**

I made some prototyping, it works like a charm:
https://gist.github.com/dimzon/7dd96cb37a1ad491322d4d07d4d1f314 

In those prototype generated objects doesn't inherit from DynamicObject but you still can assign it to dynamic variable and use as dynamic...

**Comment by dimzon** [comment]
I mean you can inherit generated classes from DapperRow, for example 
```
MyGeneratedXXXX:DapperRow
{
     public int? SomeProperty
     {
          get{return (int?)this["SomeProperty"];}
          set{this["SomeProperty"]=value;}
     }
}
```
in this way class will remain fully dynamic but become accessible via reflection

**Comment by mgravell** [comment]
I don't see that this (inheriting from DynamicObject) would solve an actual
problem that needs to be solved. I'm OK with the custom descriptor idea
(and I understand what is involved - have done it before many times), but
the type generation seems overkill, IMO.

**Comment by dimzon** [comment]
Dapper itself generate IL for everything so one more generation is not a problem.
Main idea is to allow introspection via reflection - some controls doesn't know about dynamics or even iCustomTypeDescriptor

Anyway maybe best solution is ability to provide custom object factory (assign to static SqlMapper property) so every dynamic-related method  like Query or QuerySingle will use this factory instead-of hardcoded DapperRow

**Comment by mgravell** [comment]
Frankly, the real solution there is: declare types to represent your data.
Dynamic is fine for ad-hoc usage, but if you choose to work ad-hoc, expect
the limitations of ad-hoc. I'm OK-ish with custom descriptors, but
ultimately my view is: if what you're doing wouldn't work with DataTable,
it isn't reasonable to expect it to work here. Custom descriptors solves
that much even for the ad-hoc case. I do not agree that type emit is a good
option here.

**Comment by NickCraver** [comment]
I'm with Marc here - if you need something that really behaves like a type *then declare a type*. We expose all the bits to cover abstract types, etc. `dynamic` shouldn't be crazy here, it should be a fallback.  Agreed with no emit logic here, it's so narrow I don't think it's a net win.

**Comment by NickCraver** [comment]
Closing out to cleanup, ping if there's more to discuss please! (Trying get on top of a ton of issues)
