### ISSUE TITLE
Missing overloads in Dapper 1.50.2

### ISSUE THREAD

**Issue by nvivo** [StackExchange/Dapper#808]
Using dapper 1.50.2, the following overloads seem to be missing:

```
QueryFirstAsync(string)
QueryFirstOrDefaultAsync(string)
QuerySingleAsync(string)
QuerySingleOrDefaultAsync(string)
```

As something like `cn.QueryFirstAsync("select...")` give the following error:
`CS1503 Argument 2: cannot convert from 'string' to 'Dapper.CommandDefinition'`

Edit: It seems the methods are there, but for some reason the compiler is resolving only these four methods to the wrong overload.

**Comment by nvivo** [comment]
I have been looking into this, still have no clue on why it happens or how to fix it.

How to reproduce:

```
using Dapper;
using System.Data;

class Program
{
    static void Main(string[] args)
    {
        IDbConnection cn = null;
        cn.QueryFirstAsync("foo"); // cannot convert from 'string' to 'Dapper.CommandDefinition'
    }
}
```

Any ideas?

**Comment by NickCraver** [comment]
Fixed for the next release! Merging in and releasing likely this week or next.
