### ISSUE TITLE
PostgreSQL connection statement due user request

### ISSUE THREAD

**Issue by higorcorrea** [StackExchange/Dapper#809]
I'm getting the error 'connection statement due user request' on "Query<T>" and "Execute". Someone can help me please?
If i insist and keep trying to use "execute" he works.
Query is a simple insert.
Database is PostgreSQL 9.3

**Comment by mgravell** [comment]
https://stackoverflow.com/a/14158622/23354 ?

**Comment by higorcorrea** [comment]
I'll try to make timeout longer and in my code or postgresql and get back here to give a feedback.
Thank you @mgravell  !

**Comment by higorcorrea** [comment]
Looks like worked!
Passed some weeks and the error doesn't appears again
