### ISSUE TITLE
Oracle procedure sysrefcursor as input

### ISSUE THREAD

**Issue by danboone** [StackExchange/Dapper#814]
I need to call a oracle stored procedure a that has a sys_refcursor as one of the inputs.  I have implemented a customer OracleDynamicParamaters to handle cursors on the output but I can't find any information on how to send the cursor as an input to a procedure.  I'm hoping you'll be able to help 

Thank you

**Comment by NickCraver** [comment]
This isn't something Dapper supports directly, but for anyone needing this I'd recommend asking on the Dapper.Oracle lib which has handling for `out` ref cursors currently: https://github.com/DIPSAS/Dapper.Oracle/
