### ISSUE TITLE
ExecuteReaderAsync overload for CommandBehavior

### ISSUE THREAD

**Issue by JeffEmery** [StackExchange/Dapper#815]
Pardon the interruption... Is there any reason why ExecuteReaderAsync does not include an overload for CommandBehavior? Is there something I'm missing that makes it not reasonable to do, realizing the Dapper extension method is on a DbConnection and not a DbCommand type? e.g. [SqlCommand.ExecuteReaderAsync](https://msdn.microsoft.com/en-us/library/hh204867(v=vs.110).aspx) 

Otherwise, I'm stuck on how to close the connection directly after the reader is disposed.

**Comment by mgravell** [comment]
That's not an interruption. Excellent question - it looks like an oversight
in the overloads / method signature. We should fix for next build.

**Comment by NickCraver** [comment]
Fixed for the next release, will be merging down and releasing hopefully this week.
