### ISSUE TITLE
cannot convert from 'string' to 'Dapper.CommandDefinition'

### ISSUE THREAD

**Issue by njdonarski** [StackExchange/Dapper#825]
OMG!!!

I am pulling my hair out...

Why am I getting this error?

Here is my code:

        List<ID> ids = new List<ID>();
        public static List<ID> GetID(string lastName)
        {
            using (IDbConnection connection = new System.Data.SqlClient.SqlConnection(Helper.CnnVal("faceid")))
            {
                connection.Open();
                return connection.Query<ID>("Select * from storedIDs").ToList();
            }
        }

I can execute the Execute function without issue, but when I attempt to enter ANY string of sql queries I get the same answer. Doesn't matter if I set the query to a var or not.

**Comment by mgravell** [comment]
excellent question - is there anything unusual about your setup? ehat
framework is this targeting?

**Comment by njdonarski** [comment]
Nothing crazy or weird.

Using .Net 3.5

The following works fine:

`        public void InsertID(string firstName, string lastName, string dobDate, string idNumber, string address, string city, string state, string zipCode, string country, string issueDate, string expDate, string timestamp)
        {
            using (IDbConnection connection = new System.Data.SqlClient.SqlConnection(Helper.CnnVal("faceid")))
            {
                //ID newID = new ID { firstName = firstName, lastName = lastName, dobDate = dobDate, idNumber = idNumber, address = address, state = state, zipCode = zipCode, country = country, issueDate = issueDate, expDate = expDate, timestamp = timestamp };


                List<ID> ids = new List<ID>();

                ids.Add(new ID { firstName = firstName, lastName = lastName, dobDate = dobDate, idNumber = idNumber, address = address, city = city, state = state, zipCode = zipCode, country = country, issueDate = issueDate, expDate = expDate, timestamp = timestamp});

                connection.Execute("dbo.spstoredIDs @firstName, @lastName, @dobDate, @idNumber, @address, @city, @state, @zipCode, @country, @issueDate, @expDate, @timestamp", ids);

            }
        }`

I am able to interact with the DB, I can add information to the DB, but I can not Query the DB.

**Comment by njdonarski** [comment]
I have found that if I add

                var IDS = connection.Query<ID>($"Select * from storedIDs", null).ToList();

a ", and then value" after the string I do not get the error

Can you do a Query to return all values?

**Comment by njdonarski** [comment]
So my goal is to:

Query DB for all values: current query "SELECT * FROM dbo.storedIDs"

Then Return values in form of: firstName lastName (these are stored as such in the DB)

Then the values should be entered into a List.

The List should then save to a Text File.

I can write to the DB without issue, which to me would seem to be a larger function, but this continues to spit out the same error (error is the title of this post) every time.

**Comment by mgravell** [comment]
ah, right; does it work with the null but without the $ interpreted string
literal - just a regular string literal? This is almost certainly missing
support for the optional parameter in down-level frameworks

**Comment by njdonarski** [comment]
so if I step through the process, with the null value set no items are added to the List after execution.

No errors... and the cannot convert string to Dapper... error is removed, but nothing is returned either

**Comment by mgravell** [comment]
silly question perhaps, but: does that query return data in the real
database? And are you sure you're running it against the right database? (a
common error here is when using database files, looking in the wrong file)

**Comment by njdonarski** [comment]
HAHAHAHA,

K, I just had to do a sanity check... yes "select * from storedIDs" responds with all of the table information

**Comment by mgravell** [comment]
sanity checks are good, for all concerned. on the surface your example
looks fine. sorry to be a pain, but I obviously can't run your query myself
to debug it. Are you getting zero rows? Or the right number of rows but
with no data?

If it is zero rows: is there any chance you can test *the exact same query*
with ADO.NET direct to see if it works? Should be something like:

    using(var cmd = conn.CreateCommand()) {
        cmd.CommandType = CommandType.CommandText;
        cmd.CommandText = "your query here";
        int count = 0;
        using(var reader = cmd.ExecuteReader()) {
             while (reader.Read()) count++;
         }
    }

With that: what is count afterwards.

**Comment by njdonarski** [comment]
I FIXED IT!

Sooo, the ", null" object value added after the Query DOES fix it.

I had to refresh the display area by reloading it completely to display.


SOOOOOO TO anyone that gets the issue:

create your Query as such: connection.Query<ID>("select` * from storedIDs"**, null**).ToList();

**Comment by mgravell** [comment]
ah, k; great to hear it is fixed.

Can I ask a related question? Since part of the issue here was exacerbated
by .NET 3.5 restrictions, is there a specific reason (that you can talk
about) for using .NET 3.5? We try to support it, but obviously it is
limited etc.
