### ISSUE TITLE
how about  db connection pool ?

### ISSUE THREAD

**Issue by yangzhenyu123** [StackExchange/Dapper#828]
sir, how about db connection pool? dose dapper can manager it ? or manager pool by others tool?

**Comment by mgravell** [comment]
dapper does not attempt to provide a connection pool; dapper starts from a
connection - so : the ado.net level connection must already exist. If the
connection is not open, dapper will open it for the duration of operations
- and if *that* happens to make use of an underlying native pool (which
SqlClient does), then great

But it doesn't target anything more than that.

**Comment by NickCraver** [comment]
Asked and answered, just closing out to cleanup. It's just outside the realm of Dapper, but something could easily be used *with* Dapper if one chooses.
