### ISSUE TITLE
ExecuteAsync with lots of objects cut off

### ISSUE THREAD

**Issue by thedumbtechguy** [StackExchange/Dapper#831]
I am inserting multiple rows using  `ExecuteAsync` with `Npgsql` as my driver.
It works fine but I just tried inserting over `7000` rows and it truncated at `6634`.

Not sure if this is from Dapper or from Npgsql and I am not sure where to look first.

**Comment by NickCraver** [comment]
Can you give me a minimal repro for this? Sample code may reveal a lot.

**Comment by thedumbtechguy** [comment]
Sure thing. Currently in a crunch, but I'll get on it as soon as I get some
free time.

Thank you.

**Comment by thedumbtechguy** [comment]
I apologize for the premature ticket and thank you for your time.

I had a `ON CONFLICT DO NOTHING` and my sample dataset had duplicates so I was triggering it.
