### ISSUE TITLE
Dapper.Contrib: Incorrect syntax near the keyword 'Table'

### ISSUE THREAD

**Issue by Lillecarl** [StackExchange/Dapper#832]
Hi!

When *genious* devs of closedsource application uses keywords for column names dapper doesn't work well, afaik this can be resolved by putting "" (double quotes) around column names.

Sadly i can't change database structure, so i'll have to live with manual queries for now :)

EDIT: '' around the tablenames work on SQL Server 2016 at least (This is where i've tested)

**Comment by Zopitirik** [comment]
Not only column names, table names as well.

[This Line](https://github.com/StackExchange/Dapper/blob/071a3fd5a0e9a3ebb9b598737b94b49c56446722/Dapper.Contrib/SqlMapperExtensions.cs#L361)

should be 

var cmd = $"insert into **[**{name}**]** ({sbColumnList}) values ({sbParameterList})";

**Comment by Lillecarl** [comment]
@Zopitirik That won't wolve the issue with column names though, but it's a start.

**Comment by Zopitirik** [comment]
@Lillecarl they fixed column name problem on #336 [this line](https://github.com/StackExchange/Dapper/blob/071a3fd5a0e9a3ebb9b598737b94b49c56446722/Dapper.Contrib/SqlMapperExtensions.cs#L335)
function name is "AppendColumnName", i just saw that.

Now we need AppendColumnName like **AppendTableName** at  "interface ISqlAdapter"

**Comment by Zopitirik** [comment]
@Lillecarl i found a workaround here;
I was using tablename => "User"

I tried Table attribute with square bracket.

`[Table("[User]")]
public class User
{
}`

I think you also use it for column names like =>  **[Column("[Table]")]**

**Comment by Lillecarl** [comment]
@Zopitirik Aye smart! That'll do for now! :)

**Comment by NickCraver** [comment]
Closing this as there's a workaround *for this specific issue*, but we'll address this more holistically in #722.

**Comment by AntonU1983** [comment]
You may set `SqlMapperExtensions.TableNameMapper = (type) => {
        return type.Name;
      };` in and use `nameof` keyword in `TableAttribute` like this `[Table(nameof(User))]`
