### ISSUE TITLE
Dapper.Contrib on postgres and ISqlAdapter

### ISSUE THREAD

**Issue by smartcodinghub** [StackExchange/Dapper#834]
Hi all,

I'm having some troubles since dapper contrib escapes column names with the property name. If I have an already created table withoud " in its column names, I must user upper case names in my model class since dapper contrib escapes them with ".

Example:

```
-- Table
CREATE TABLE CARS (
	ID SERIAL,
	MODEL VARCHAR(10),
	REGISTRATION VARCHAR(7),
	COLOR VARCHAR(15)
);

// Model not working:

    [Table("CARS")]
    public class Car
    {
        public int Id { get; set; }
        
        public String Model { get; set; }
        
        public String Registration { get; set; }
        
        public String Color { get; set; }
    }

// Model WORKING:

    [Table("CARS")]
    public class Car
    {
        public int ID { get; set; }
        
        public String MODEL{ get; set; }
        
        public String REGISTRATION{ get; set; }
        
        public String COLOR{ get; set; }
    }
```

The solutions I see are:

1- AdapterDictionary on SqlMapperExtensions must be public to change the adapter to a different one.
2- Having two ISqlAdapter for postgres with and withour " and some way to swap them (maybe some mix with the first solution).
3- A switch via config or method that changes de ISqlAdapter from using " to not using it. This can works for any adapter with something like NoEscape property, etc...

If I use the table like this:

CREATE TABLE CARS (
	"Id" SERIAL,
	"Model" VARCHAR(10),
	"Registration" VARCHAR(7),
	"Color" VARCHAR(15)
);

I have the problem that the RETURNING isn't escaped... We need consistency here.

**Comment by smartcodinghub** [comment]
I can help and contribute on this if any one wants it. But first you need to discuss the solution.

**Comment by mikegottlieb** [comment]
Yeah this is also currently preventing me from using Dapper.Contrib with Postgresql. I would really like it if case sensitivity wasn't an issue at all here and if the `Dapper.DefaultTypeMap.MatchNamesWithUnderscores` setting was respected.

It seems like there is talk of fixing this for v2, but that means it will remain unusable for quite a while.

**Comment by smartcodinghub** [comment]
Any update on this issue? I can make a pull request if someone approves this.

**Comment by NickCraver** [comment]
This is something we'll address via #722, but cannot make a breaking change before a major version here (and either way we want old/new easily to configure depending on your database layout).

**Comment by yecarri** [comment]
I can't understand why this is closed. Dapper.Contrib generated sql should be consistent and work for all the supported databases. It makes no sense that column names are double-quoted and key references are not. For example, in PostgreSQL if I have this entity:

    class MyTable
    {
       [Key]
       int MyTableId {get; set;}
       string MyDescrition {get; set;}
    }

and my table is defined as:

    create table "MyTable" 
    (
        "MyTableId" sequence,
        "MyDestination" varchar(80)
    )

When I try to do a simple insert I get `42703: column «mytableid» dies not exist` while it **SHOULD** honour capitalization.
