### ISSUE TITLE
Adding parameters using string interpolation

### ISSUE THREAD

**Issue by ricsmania** [StackExchange/Dapper#838]
Entity Framework Core 2 has a great feature that allows us to add parameters using string interpolation:

```csharp
var city = "Redmond";

using (var context = CreateContext())
{
    context.Customers.FromSql($@"
        SELECT *
        FROM Customers
        WHERE City = {city}");
}
```
(taken from https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-entity-framework-core-2-0/)

Would you consider adding this to Dapper?

**Comment by mgravell** [comment]
I *would*, but unfortunately overload precedence goes to string before the
parameterized string object, so first we'd need to add new method names for
these. The second problem is picking the right parameter symbol, although i
think thats solvable. the bigger problem, though, is the weight of that -
it isnt exactly lightweight, and has a lot  more overhead than a string and
anonymous object pair. That would need serious consideration

**Comment by NickCraver** [comment]
I wasn't aware this was added to EF Core in 2.0. I strongly object to such a feature. Here's a demo project showing just some of the ways it can be done incorrectly and not actually parameterized: https://github.com/NickCraver/EFCoreInjectionSample/blob/master/Program.cs

I'm raising these issues with the EF team now. I wish I had seen this before the 2.0 release, I sincerely hope it gets deprecated and removed ASAP. If they took *only* a `FormattableString`, it'd have almost none of the worries, but it doesn't. They implement it with [implicit operations on a struct](https://github.com/aspnet/EntityFrameworkCore/blob/44119b3962513adc20b98a53567b968644904360/src/EFCore.Relational/RawSqlString.cs) which adds a lot of danger as developers can pass in strings that aren't being parameterized at all.

In Dapper, I don't think this is a good idea. An ORM that's no direct SQL *expect* a `FormattableString` (like EF could be) I totally see. For Dapper, I think it's firmly a net loss in perceived vs. actual security and the bugs it'd create.

I'm happy to discuss this at length, but as of now: I'm firmly against adding this. SQL injection is a serious issue, and we shouldn't add more ways and examples of how to screw that up.

**Comment by mgravell** [comment]
indeed, it is already perfectly possible to screw up here by using dapper
with interpreted syntax incorrectly - but at least that's entirely in the
hands of the caller. In many ways, offering this feature even in different
named methods starts getting into the territory where the API *actively
leads people* into making an injection mistake, and that is definitely
worth avoiding at all costs.

**Comment by ricsmania** [comment]
Seeing @NickCraver's examples I totally agree with the security implications. I didn't know this implementation was so fragile on EF Core 2.

I suggested this as a way to flatten a complex object and pass it as a parameter to dapper. For example, if I have a class Person with a property of type City and I need to pass the City.Id to Dapper, I need to do something like this:

```csharp
var parameters = new DynamicParameters(person);
parameters.AddDynamicParams(new { City_Id = person.City.Id });
var result = connect.QueryFirst<Result>("select :Id Id, :Name Name, :City_Id City_Id", parameters);
```

I wanted something like this:
```csharp
var result = connect.QueryFirst<Result>("select :Id Id, :Name Name, :City_Id City_Id", person);
```

The interpolation solution would make it easy, but I understand the problems. Now I'll look for another way to do this.

I'll probably create a method that reflects on a type recursively and adds the parameters using my own convention. Just checking to see if I'm not reinventing the wheel.

**Comment by Neme12** [comment]
I agree that this is a problem with the current implementation but if it had a different method name that took only FormattableString, there would be no fallback to string and it wouldn't compile if done incorrectly.

**Comment by NickCraver** [comment]
@Neme12 The problem there is it's not 1 method name, it's *100* method names, and users would have to remember to call the right one. It has all the same likely-to-end-badly scenario problems. If we had done FormattableString only from the start, then it'd have far fewer issues, but can't really do so now.

**Comment by Neme12** [comment]
I'm sorry, I know nothing about this project. I was just talking generally about how they did it in EF Core.

**Comment by Neme12** [comment]
There's other things that could disambiguate the method call.
1) using a named parameter, where the call would look like this: QueryFirst(formattable: $"...") - but this seems really fragile, and I don't think people would realize that a single named parameter can even affect overload resolution
2) using a method that would wrap a formattable string into a struct: QueryFirst(Parametrize($"...")) - here it's more obvious that something special is happening, but still nothing would prevent people from omitting the method call. On the other hand, nothing prevents people from doing that right now anyway, and Parametrize sounds really specific about what it's doing.

**Comment by intergleam** [comment]
this conflicts with Oracle Text that uses {} for escaping. Is there a way to disable this feature? I am actually using EF 6.2 but may be it is similar?

**Comment by Sebazzz** [comment]
It looks like the EF team took the comment @NickCraver seriously. For string interpolation you need to call a different method which only accept interpolated strings.

**Comment by NickCraver** [comment]
I'm going to go ahead and close this out - EF Core tried this and came to the same conclusions ultimately w.r.t. danger (a change I'm very glad they made in the next major release). For Dapper, this remains something we wouldn't add - it's not worth the safety trade-offs :)

**Comment by Drizin** [comment]
[DapperQueryBuilder](https://github.com/Drizin/DapperQueryBuilder/) is based on this idea of passing parameters using Interpolated Strings.
