### ISSUE TITLE
Provide a way to manually specify key properties for a given type

### ISSUE THREAD

**Issue by philchuang** [StackExchange/Dapper#844]
I am working with a data model that I cannot modify to add Dapper attributes, and that I do not wish to extend and override.

I propose a feature to allow external code to specify a key property mapping delegate, similar to how TableNameMapper can be specified in order to map a type to a table.

**Sample Code**

SqlMapperExtensions.cs
```
public interface ITypeKeyMapper
{
    bool IsTypeKey(Type t, PropertyInfo p);
}

public static ITypeKeyMapper TypeKeyMapper { get; set; }
```

SqlMapperExtensions.cs:113
```
var keyProperties = allProperties.Where(p => TypeKeyMapper?.IsTypeKey(type, p) == true || p.GetCustomAttributes(true).Any(a => a is KeyAttribute)).ToList();
```

Calling code
```
public static void SetupDapperMappings() {
    SqlMapperExtensions.TypeKeyMapper = (t, p) => {
        if (type == typeof(MyClass)) {
            return p.Name == "MyKey";
        }
        return false;
    }
}
```

**Comment by NickCraver** [comment]
I'd check out #722 for discussions on how we want to approach this overall. I'm wrapping up other libs now and it'll still be a bit before we get to Dapper enhancements for v2.

**Comment by philchuang** [comment]
Thanks, that's exactly what I was thinking. Closing this issue in favor of [#722](https://github.com/StackExchange/Dapper/issues/722)
