### ISSUE TITLE
Dapper for Java

### ISSUE THREAD

**Issue by mrerhuo** [StackExchange/Dapper#857]
Does java have dapper?

**Comment by mgravell** [comment]
I actually starting writing a clone in Java, but then I remembered that a:
I don't use enough Java to properly test it in common usage in real world
usage, and b: I don't want to have to support it

I fully encourage anyone else taking the core usage ideas from dapper and
applying them to Java. The implementation will.be necessarily very
different, of course.

**Comment by NickCraver** [comment]
Closing this out as answered - we have no plans to support a Dapper in Java but think something similar would be awesome for the community to have :)
