### ISSUE TITLE
What  is Dapper different from many others ORM

### ISSUE THREAD

**Issue by wjkhappy14** [StackExchange/Dapper#860]
As we know,Dapper  is so   smaill,but so fast.
I want to know why Dapper  is so fast ?
Someone can help me ？

**Comment by mgravell** [comment]
- concentrate on solving the biggest problems, not solving everything
- for the things you do: do them well
- do them directly, without 17 layers of abstraction and indirection

that's it, really

**Comment by mgravell** [comment]
specific examples:

- no config files to parse
- no DSL to parse
- no query generation
- no abstract multi-DB targeting
- no change tracking / identity management

Most people don't need those for most things.

**Comment by NickCraver** [comment]
Closing out as answered above :)
