### ISSUE TITLE
Wrong number of parameters Issue

### ISSUE THREAD

**Issue by s1495k043** [StackExchange/Dapper#865]
My sql statement
`                select 
                first 100 * 
                from opd_reg
                where doc_code in ?docCode? and reg_no = ?regNo?`

My code
`var resut = conn.Query(sql, new { regNo = "058650", docCode = new[] { "4224", "4239" } });`

Exception
`ERROR [07001] [Informix .NET provider]Wrong number of parameters.`

And if I only use ?docCode? parameter,It works.

**Comment by strongdevx** [comment]
use` @` parameter prefix,like this:

```
select first 100 * from opd_reg where doc_code in @docCode and reg_no = @regNo
```

**Comment by s1495k043** [comment]
> use@ parameter prefix,like this:

I use  Informix.
