### ISSUE TITLE
A little wish

### ISSUE THREAD

**Issue by JHeLiu** [StackExchange/Dapper#867]
Hey, very much like your library, but I think the author can do an extension of the expression, such as simple conditional analysis, because you do not like to use EF, but they did not have the ability to analyze the expression, please? The author has not considered the preparation of an expression parsing library, type EF kind

**Comment by mgravell** [comment]
are you talking about LINQ expression trees? if so: it is very deliberate:

1. there is quite a lot of overhead in expression trees themselves
2. query generation from an expression tree is complex
3. query generation is provider specific, and the *core* of dapper tries very hard not to be provider specific
4. generated queries tend to be suboptimal, and we're very big on optimal

If you want to take the time to write an expression-tree based query generation tool, then great! but there aren't any plans to add that to dapper core at this time.

**Comment by phnx47** [comment]
@JHeLiu  I wrote library for this. Maybe, it is helpful for you. Simple and JOIN queries are supported
https://github.com/phnx47/MicroOrm.Dapper.Repositories

**Comment by JHeLiu** [comment]
@mgravell
Thank you very much for the author so late to answer my question, ha, forget I was in China. That is my little wish. Is to expect the author to have an extended expression to change these operations Thank you

**Comment by JHeLiu** [comment]
@phnx47 
Thank you, I see, I have to understand the next. But I would like to ask you? Will you follow this context? In fact, I want a very simple, that is, like EF can be resolved with the expression LINQ and then become a T-SQL dapper implementation of the right, the amount of capacity is limited, so ask you

**Comment by NickCraver** [comment]
I think if you want a context fully featured (which has many costs in both performance and maintenance) then Entity Framework Core is the way to go these days. They've done a lot of work to simplify things and IMO they've done a good job of it. I think, simply put, Dapper isn't a proper fit for your goals...but EF Core is :)

**Comment by JHeLiu** [comment]
@NickCraver No, I've always liked Dapper, but I wanted to merge an expression translator with Dapper, and I wanted to use the simpler, less powerful, third-order expression instead, because I used front-end good operations and were almost unusual Convenience. But in a complicated place I prefer to use Dapper. I've been looking for such a small expression translation library O(∩_∩)O  ╮(╯▽╰) ╭  n(*≧▽≦*)n
