### ISSUE TITLE
Will dapper work with Asp.Net Core 2.0 + Oracle 11?

### ISSUE THREAD

**Issue by Pandimca1** [StackExchange/Dapper#875]
Hi, I am new to dapper and going to work with a project (Asp.Net Core 2.0+Oracle 11). So i want to know dapper will work with Asp.Net Core 2.0 + Oracle 11?

**Comment by Postlagerkarte** [comment]
1.50.4-alpha 1 works with .NET 2.0 Core.  However you still need a oracle driver. Oracle currently does not provide one but they announced one will be ready end of this year. Until then you can either use the Mono.Data.OracleClientCore or System.Data.OracleClient (both on nuget). Be aware that both libraries behave badly with unicode. If you require support for unicode , there is a pr for the problem in the github repository of the mono oracle  client.

**Comment by NickCraver** [comment]
Yep as answered above, Dapper itself is provider agnostic. If an ADO.NET provider exists, we can run on it.
