### ISSUE TITLE
dynamic object property names != sql field names

### ISSUE THREAD

**Issue by agoretsky** [StackExchange/Dapper#878]
<img width="906" alt="screen shot 2017-11-10 at 21 00 48" src="https://user-images.githubusercontent.com/17613086/32672209-479dce46-c65b-11e7-91dd-e26af35d6187.png">

It looks like all sql field names maps to lowercase in C#.

but it doesn't match your documentation's example above:
```
var rows = connection.Query("select 1 A, 2 B union all select 3, 4");

Assert.Equal(1, (int)rows[0].A);
Assert.Equal(2, (int)rows[0].B);
Assert.Equal(3, (int)rows[1].A);
Assert.Equal(4, (int)rows[1].B);
```

.NET Core 2.0 app on Mac OSX Dapper v1.50.2, Npgsql v3.2.5

https://github.com/StackExchange/Dapper/issues/878

**Comment by agoretsky** [comment]
seems like Npgsql issue as NpgsqlDataReader.GetName() returns lowercase result

**Comment by rhubley** [comment]
I'll guess this is caused by the DBProvider, I believe npsql is case insensitive unless the column is created with quotes.
