### ISSUE TITLE
Bulk copy like method with UNION ALL

### ISSUE THREAD

**Issue by jarDotNet** [StackExchange/Dapper#881]
We're trying to build a dynamic DB migrator between SQL Server/Oracle using Dapper with DynamicParameters.

We're finding some problems with huge tables regarding physical memory, network latency or process time consumption.

As a test case we would like to know if it is possible to build something like this with Dapper:

INSERT INTO Quotes (Symbol, QuoteDate, Price)
SELECT  'AAA' , 12/15/2008, 2.44
    UNION ALL
SELECT  'BBB' , 12/15/2008, 7.42
    UNION ALL
SELECT  'CCC' ,12/16/2008, 9.11

Thanks in advance!

**Comment by jarDotNet** [comment]
Well it looks that there is an SQL limit regarding this bulk copy option:

> The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.

Is there any deal to perform something fast and similar using DataTable like this 3rd Benchmark old option?

http://blog.emirosmanoski.mk/Benchmarking-Dapper-Inserts/

Thanks.

**Comment by NickCraver** [comment]
You'll really want to use the bulk insert APIs directly for this. The `SqlBulkCopy` class is what you want to start with here, docs at: https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlbulkcopy.aspx

**Comment by jarDotNet** [comment]
Hi @NickCraver, I'm using `SqlBulkCopy` right now for SQL Server, but as I said at my first post, we need also to perform DB copy with Oracle...

**Comment by NickCraver** [comment]
Bah, I didn't see the reply here - I'm sure the fix has long-since passed need, but for anyone finding this, you'll want to use `OracleBulkCopy` in a very similar fashion here - docs at: https://docs.oracle.com/cd/E11882_01/win.112/e23174/OracleBulkCopyClass.htm#ODPNT7446 - This isn't something Dapper helps with directly, so closing out to tidy up.
