### ISSUE TITLE
ColumnAttribute not working for Query method

### ISSUE THREAD

**Issue by danguilherme** [StackExchange/Dapper#883]
Assume I have a stored procedure with the following interface:
```sql
Sp_Generate_ReportCards @id, @year, @schoolId
```
And it returns columns like:
`School | Code | [Ranking Position]`

Given that, I have a model mapping to these columns, and then I execute the procedure with a strongly typed `Query` call:

**Model:**
```csharp
using Base;
using Dapper;

namespace Db
{
    public class ReportCard : Db<ReportCard>
    {
        [Column("School")]
        public string School { get; set; }

        [Column("Code")]
        public string StudentCode { get; set; }

        [Column("Ranking Position")]
        public string RankingPosition { get; set; }
    }
}
```

**Query:**
```csharp
var reps = connection.Query<ReportCard>(
    @"EXEC Sp_Generate_ReportCards @id, @year, @schoolId",
    new { id, year, schoolId });
```

`reps` is a list, but only the `School` property of each item is filled up, the others are `null`. If I change the `School` **prop** to `SchoolName`, it comes null too (even with `Column` attribute untouched).

**Is the `ColumnAttribute` ignored for `Query` calls?**

**Comment by rhubley** [comment]
Column attribute is used in contrib, not in core dapper

**Comment by danguilherme** [comment]
Okay, so I just mapped by hand while I cannot edit the procedure:

```csharp
var reps = ExecuteQuery(@"EXEC Sp_Generate_ReportCard @assessmentId, @year, @schoolIds",
    new {
        id,
        year,
        schoolId
    }).Select(x => new ReportCard
    {
        School = x["School"].ToString(),
        StudentCode = x["Code"].ToString(),
        RankingPosition = x["Ranking Position"].ToString(),
    });
```

Thanks!
