### ISSUE TITLE
Delete 's'!

### ISSUE THREAD

**Issue by xiaolu6t** [StackExchange/Dapper#888]
We are not fool,pls delete 's' from table name.
name = type.Name + "s";
                    if (type.IsInterface() && name.StartsWith("I"))
                        name = name.Substring(1);

**Comment by rhubley** [comment]
If you want to override the convention you can provide a TableAttribute for the class with the name of the table you wish to use.

**Comment by NickCraver** [comment]
@rhubley is correct. See the plans in #722 to be able to adjust this behavior globally.

We cannot make any changes to this short of a major version (it is a breaking change), and even then such a change would need to have a backwards compat button, #722 aims at this with functional control.
