### ISSUE TITLE
Sql Paramter in Oracle should use ?P? or :P

### ISSUE THREAD

**Issue by abcplex** [StackExchange/Dapper#890]
I am very confused in writing oracle sql parameters in dapper. For example should I use,

    select :p from dual

Or

    select ?p? from dual

We have found some errors using `:p` that's why we moved to ?p?

**Comment by rhubley** [comment]
I use :p for all my Oracle queries to real tables, using the ManagedDataAccess Client, haven't seen any issues.

I've had issues with Oracle and selecting from dual for dummy queries

**Comment by cdonnellytx** [comment]
There was a bug in the 12.1 Unmanaged driver (4.121.2.0) where, if you had a multi-line comment with a slash in it eventually followed by a colon, it would treat it as having a phantom bind variable.

Example SQL:

```sql
select 1 /* /: */ from dual;
```

The bug no longer exists in the 18.3 Unmanaged driver, nor does it exist in the latest Managed Framework driver (19.6.0).

@abcplex was this the issue you saw?

**Comment by NickCraver** [comment]
Since this appears to be an underlying issue, closing out to cleanup. If that's _not_ the case, please ping and we'll re-open!
