### ISSUE TITLE
Support for Streams as parameters

### ISSUE THREAD

**Issue by jerchap** [StackExchange/Dapper#893]
Requesting support for marshaling a System.IO.Stream to a VarBinary parameter using streaming so I can pass large streams of data to sql without having to load it entirely into memory

**Comment by mgravell** [comment]
do you have an example of what this would look like in vanilla ado.net code?

**Comment by NickCraver** [comment]
Similar to #894, without an example or use case (we've only seen 1 request for this) and no follow-up, this isn't something we can chase down. If someone has examples/use cases for this, I'll re-open this for discussion!

**Comment by benjcallaghan** [comment]
I have a use case where files are being uploaded to my API and I need to save them into a SQL database without buffering the file. SQL supports this by accepting Streams as parameters for varbinary columns. In the following ADO.NET code, FileContent is varbinary(max) while the other two are simply varchar.

```c#
using (var connection = await _connectionFactory.CreateConnectionAsync(cancellationToken))
using (var command = new SqlCommand("[MySchema].[SaveFile]", connection)) {
  command.CommandType = CommandType.StoredProcedure;

  command.Parameters.AddWithValue("@FileName", file.FileName);
  command.Parameters.AddWithValue("@FileType", file.FileType);
  command.Parameters.AddWithValue("@FileContent", file.Contents);

  await command.ExecuteNonQueryAsync();
}
```

The documentation for this feature can be found at [MSDN](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sqlclient-streaming-support#sample----streaming-to-sql-server).

Similarly, here is the code I use to retrieve the file (again without buffering in my application):

```c#
var connection = await _connectionFactory.CreateConnectionAsync(cancellationToken);
var command = new SqlCommand("[DisputeAPI].[GetMastercardFile]", connection) {
  CommandType = CommandType.StoredProcedure
};
command.Parameters.AddWithValue("@Id", id);
var reader = await command.ExecuteReaderAsync(CommandBehavior.SequentialAccess, cancellationToken);

var fileType = reader.GetString(0);
var fileName = reader.GetString(1);
var contents = reader.GetStream(2);
```

It would be nice to have this ability in Dapper with automatic mapping between Stream and varbinary(max).

**Comment by bcallaghan-et** [comment]
@NickCraver As requested, a use case with ADO.NET examples has been provided. I have a similar use case in several different products. Please re-open this feature request.

**Comment by jerchap** [comment]
I am trying to implement this with a TypeHandler but it has limitations and doesn't meet the needs.  I've included ADO.Net samples below on how streaming to/from the db is implemented.  As for the comment around use case, I would have thought it was obvious.  If there is a lot of data it just doesn't make sense to load it into memory then push it to sql because that consumes resources on both the application side, and the sql server side which could be completely mitigated using a streaming approach.

```
public class StreamTypeHandler : SqlMapper.TypeHandler<System.IO.Stream>
{
    public override void SetValue(IDbDataParameter parameter, System.IO.Stream value)
    {
        parameter.Value = value;

        SqlParameter sqlParameter;
        if ((sqlParameter = (parameter as SqlParameter)) != null)
        {
            //Set up parameter to stream to database
            sqlParameter.SqlDbType = SqlDbType.Binary;
            sqlParameter.Size = -1;          
        }
    }
        
    public override Stream Parse(object value)
    {
        if (value is null)
        {
            return null;
        }

        byte[] binValue;
        if ((binValue = (value as byte[])) != null)
        {
            MemoryStream stream = new MemoryStream();
            stream.Write(binValue, 0, binValue.Length);

            return stream;
        }


        throw new NotSupportedException($"Can not convert {value.GetType()} to Stream.");
    }
}
```
The limitation is on the parse side, because by the time dapper calls the parse method it has already loaded the entire value into memory.


Here are ADO samples for streaming to the database:
```
public void InsertBinaryStream(System.IO.Stream strData)
{
    using (SqlConnection conn = new SqlConnection(this.ConnectionString))
    {
        conn.Open();

        using (SqlCommand cmd = new SqlCommand("INSERT INTO [StreamingSample] (BinaryData) VALUES (@bindata)", conn))
        {
            cmd.CommandTimeout = int.MaxValue;
            // Add a parameter which uses our stream
            // Size is set to -1 to indicate "MAX"
            cmd.Parameters.Add("@bindata", SqlDbType.Binary, -1).Value = strData;

            cmd.ExecuteNonQuery();
        }
    }
}
```

```
public void InsertTextStream(System.IO.Stream strText)
{
    using (SqlConnection conn = new SqlConnection(this.ConnectionString))
    {
        conn.Open();

        using (SqlCommand cmd = new SqlCommand("INSERT INTO [StreamingSample] (TextData) VALUES (@bindata)", conn))
        {
            cmd.CommandTimeout = int.MaxValue;
            // Add a parameter which uses our stream
            // Size is set to -1 to indicate "MAX"
            using (StreamReader rdr = new StreamReader(strText))
            {
                //May not actually be NVarchar,  SQL Server supports streaming Char, NChar, NVarChar, Xml
                cmd.Parameters.Add("@bindata", SqlDbType.NVarChar, -1).Value = rdr;
                cmd.ExecuteNonQuery();
            }
        }
    }
}
```

```
public void InsertXmlStream(System.IO.Stream strData)
{
    using (SqlConnection conn = new SqlConnection(this.ConnectionString))
    {
        conn.Open();

        using (SqlCommand cmd = new SqlCommand("INSERT INTO [StreamingSample] (XmlData) VALUES (@bindata)", conn))
        {
            cmd.CommandTimeout = int.MaxValue;
            // Add a parameter which uses our stream
            // Size is set to -1 to indicate "MAX"
            using (XmlTextReader rdr = new XmlTextReader(strData))
            {
                cmd.Parameters.Add("@bindata", SqlDbType.Xml, -1).Value = rdr;
                cmd.ExecuteNonQuery();
            }
        }
    }
}
```

Here is a sample for streaming from the database.  This will give you a stream object back.  From there you can parse the stream into whatever object you need (XDocument, XmlDocument, TextReader, etc)

```
public Stream ReadBinaryStream(int iID)
{
    using (SqlConnection conn = new SqlConnection(this.ConnectionString))
    {
        conn.Open();

        using (SqlCommand cmd = new SqlCommand("SELECT [BinaryData] FROM [StreamingSample] WHERE [id] = @id", conn))
        {
            cmd.CommandTimeout = int.MaxValue;
            cmd.Parameters.AddWithValue("id", iID);

            using (SqlDataReader reader = cmd.ExecuteReader())
            {
                if (reader.Read())
                {
                    //Get index of column, so we don't assume the column order of the resultset
                    int iColumnIndex = reader.GetOrdinal("MyData");
                    return reader.GetStream(iColumnIndex);
                }
            }
        }
    }

    return null;
}
```

**Comment by mgravell** [comment]
The main problem here, though, is lifetime, especially when reading data *from* the database; you still need to access the data sequentially here, IIRC, including both row-wise and column-wise, which makes it very hard to expose in a direct API - unless it is "single column, non-buffered rows". Perhaps one viable option is some kind of leased memory construct (perhaps tying into non-contiguous buffers). It is something that needs quite a lot of thought, is the biggest thing.

**Comment by jerchap** [comment]
There's probably a major use case where you read the stream for a single record.  What do you mean by lifetime?  Lifetime of what?

**Comment by mgravell** [comment]
by the lifetime here, I'm talking about the timing of how/when we provide the caller with a row of data, and what has been populated at that point; we can't read columns past the stream, IIRC (it has been a while since I tried, admittedly) - and we can't change row - without breaking the stream. This puts *lots* of limitations on the usual expectations that folks have. Frankly, I wonder whether the pragmatic thing here is for this to be a use of the `ExecuteReader` API (pretty sure we have that now), i.e. let Dapper deal with the command prep and exec, and let the consumer deal with the reader (i.e. *they* call `GetStream`). In fact, I *believe* the example you provide is broken - it disposes the stream before you've read anything from it, which means it will almost certainly break.

**Comment by jeffreywstevens** [comment]
Has something like SQL Server reader.GetStream(columnIndex) been implemented in Dapper yet?  This post is quite old.

I converted my code to native .NET SQL in the 2 cases where I needed to interact with a large varbinary.  The performance boost was exceptional. However, I hate to switch in and out of different frameworks in code. I prefer the Dapper style and its productivity gains.

**Comment by mgravell** [comment]
@jeffreywstevens the problem with that is scoping and making sure the stream is valid when you want to use it; unless we implement some kind of callback API, we will have change column, changed row, and/or closed the reader entirely - all before you even get to play with it. I'm happy to consider options but the tricky bit is coming up with a usage scenario that would be valid, without needing to buffer everything in advance. It kinda feels like a scenario where we'd want the caller to supply a `Func<Stream, Task>` so we can get the scoping right.

**Comment by alex-jitbit** [comment]
There's a simple workaround: use `DynamicParameters`. They seem to map to ADO.NET nicer. At least it works on latest version of Dapper. @mgravell how viable is this?

```c#
var dynParams = new DynamicParameters();
dynParams.Add("@bigFile", stream, DbType.Binary);
cn.Execute("UPDATE Table SET Column=@bigFile", dynParams);
```

IMPORTANT: make sure the stream is rewinded to zero-position (if you touched it and it support positioning).
