### ISSUE TITLE
Support for System.IO.TextReader parameter

### ISSUE THREAD

**Issue by jerchap** [StackExchange/Dapper#894]
Requesting support for marshaling a System.IO.TextReader to a NVarChar or Varchar parameter using streaming so I can pass large streams of data to sql without having to load it entirely into memory

**Comment by mgravell** [comment]
(you've probably guessed this if you're getting these notifications in
order, but...)

do you have an example of what this would look like in vanilla ado.net code?

**Comment by NickCraver** [comment]
Closing this out barring any new info - if someone has an example and use case, we're happy to take a look (and I'll re-open this issue)!
