### ISSUE TITLE
Using SqlHierarchId throws System.InvalidCastException 

### ISSUE THREAD

**Issue by Freydoonk** [StackExchange/Dapper#904]
I want to use SqlHierarchId in my .net project but when I try to read a SqlHierarchId from DB, System.InvalidCastException will occur. I have written a simple code which it's accessible in bellow link, to show this problem:

[SqlHierarchyIdTest](https://github.com/Freydoonk/SqlHierarchyIdTest)

I trace code and reach the  `QueryImpl<T>` in `SqlMapper` class. When Dapper tries to compare the type of value which is read by SqlDataReader, to the type of generic, confront two types of SqlHierarchyId!

![image](https://user-images.githubusercontent.com/5834491/34096361-4ed1f6cc-e3ea-11e7-98c9-612692dd9849.png)

**Comment by primez** [comment]
I have this issue also, but for me it just returns NULL.

**Comment by Freydoonk** [comment]
I solved my problem by adding this to App.config:

```
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.SqlServer.Types" publicKeyToken="89845dcd8080cc91" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-14.0.0.0" newVersion="14.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

@primez
