### ISSUE TITLE
How to install Dapper non-upstream version?

### ISSUE THREAD

**Issue by antgel** [StackExchange/Dapper#905]
Hi Dapper team,

We are considering forking Dapper to add some small functionality which we hope that we could even contribute as open source. How should we go about installing our fork on our test servers? Currently we use NuGet to install upstream Dapper, but we don't want to maintain a NuGet server just for that purpose.

We'd be happy to build a package locally and install it from S3, or similar direction.

**Comment by Tornhoof** [comment]
Local NuGet feeds, which are just directories.
https://docs.microsoft.com/en-us/nuget/hosting-packages/local-feeds

**Comment by NickCraver** [comment]
Tornhoof is correct here, that's how you'd go about it :)
