### ISSUE TITLE
Can you support mapping 1 row to 10 objects in Query?

### ISSUE THREAD

**Issue by fzhangddt** [StackExchange/Dapper#909]
Currently the method below only supports up to 7, can you increase it to 10? I have an object which is associated with 10 other objects.

public static IEnumerable<TReturn> Query<TFirst, TSecond, TThird, TFourth, TFifth, TSixth, TSeventh, TReturn>

Thank you very much!
Frank

**Comment by NickCraver** [comment]
There's maintenance and size to each of the overloads, so we stopped at 7 to fit the 99.9% use case. If you need more than this, please use the `params` overload which accepts `n` types here:
![image](https://user-images.githubusercontent.com/454813/80871097-b478c800-8c78-11ea-8e17-d103c373496f.png)
