### ISSUE TITLE
Referencing Dapper as a NuGet Package Reference breaks the Windows Workflow Activity Designer

### ISSUE THREAD

**Issue by dsbut** [StackExchange/Dapper#924]
As strange as the title sounds...it is true. Using VS Enterprise 2017 15.5.4, I've created an empty C# Workflow Foundation Activity Library project. Then, I referenced Dapper 1.5.0.2 as a NuGet Package Refence (i.e. **not** using packages.config). Then opening the designer for Activity1.xaml shows an OutOfMemoryException in the designer.

Removing the NuGet Package Reference to Dapper allows the designer to load normally.

Any ideas on what might be going on here?

**Comment by NickCraver** [comment]
Missed this when filed - I can't imagine what would be happening here - sounds like a tooling issue though. We're not a special library in any way here :-/

**Comment by NickCraver** [comment]
Going to close this out to tidy, but _if it's still an issue_ please poke and I'll help connect wit the VS team.

**Comment by dsbut** [comment]
> We're not a special library in any way here :-/
Totally agree on that! All things being equal, when the only change made to provoke the problem was to switch from `packages.config` to package references, there were really only two possible culprits, the VS IDE, or the package itself.

This ended-up being a bug in Visual Studio, which was reproducible with other select packages (not only Dapper). I also reported the problem to Microsoft,, and MS fixed the problem in an update to Visual Studio 2017, sometime in H1 2018. Either in a 15.5.x or 15.6.x release. Though off the top of my head, the exact version number it was fixed in escapes me.

Please pardon my neglect for not reporting back here the nature of the issue, once MS identified it.

**Comment by NickCraver** [comment]
No worries at all, I forget so many times - thanks for the follow-up!
