### ISSUE TITLE
Dapper.Contrib 1.50.0 -> 1.50.4 broke InsertAsync(IEnumerable)

### ISSUE THREAD

**Issue by snebjorn** [StackExchange/Dapper#930]
I can't quite pinpoint what is going on. But when I update Dapper.Contrib from 1.50.0 to 1.50.4 I get this exception

> System.InvalidOperationException : An enumerable sequence of parameters (arrays, lists, etc) is not allowed in this context
>    at Dapper.SqlMapper.GetCacheInfo(Identity identity, Object exampleParameters, Boolean addToCache) in ...\dapper\Dapper\SqlMapper.cs:line 1686

When calling `await _connection.InsertAsync(listOfEntities);`.

Anyone else getting this?

My Dapper version is 1.50.4. It works with this version combo:

- Dapper v1.50.4
- Dapper.Contrib v1.50.0

**Comment by d-franklin** [comment]
It's this line that's causing the issue.

https://github.com/StackExchange/Dapper/blob/a213b2aeee66ac0bff327ff19e70516fb629abe3/Dapper.Contrib/SqlMapperExtensions.Async.cs#L133

**Comment by bdrupieski** [comment]
What are you trying to insert? What does that type look like?

**Comment by snebjorn** [comment]
This doesn't throw
```
var list = new List<object>();
await _connection.InsertAsync(list);
```

This throws
```
var list = new List<object>().AsEnumerable();
await _connection.InsertAsync(list); // throws
```
