### ISSUE TITLE
ExecuteReader: Connection property has not been initialized.

### ISSUE THREAD

**Issue by dallasbeek** [StackExchange/Dapper#945]
Under some specific condition (which I have yet to figure out, probably a disposing prematurely) I'm getting 
ExecuteReader: Connection property has not been initialized. 
on line 
Line 389:                    reader = await ExecuteReaderWithFlagsFallbackAsync(cmd, wasClosed, CommandBehavior.SequentialAccess | CommandBehavior.SingleResult, cancel).ConfigureAwait(false);

when executing 
return await connection.QueryAsync<T>( sql )

Adding 

        internal IDbCommand SetupCommand(IDbConnection cnn, Action<IDbCommand, object> paramReader)
        {
            var cmd = cnn.CreateCommand();
            **cmd.Connection = cnn;**

makes the issue go away but I'm not sure I know the consequences of adding it?

**Comment by mgravell** [comment]
Sounds like a broken ADO.NET provider; what is the `IDbConnection` here, out of curiosity?

The suggested addition should be fine, but should also be unnecessary!

**Comment by dallasbeek** [comment]
Sql Server, and I will admit what I'm trying to do is very strange.  Essentially I'm porting over 
https://github.com/CollaboratingPlatypus/PetaPoco/blob/development/PetaPoco/Database.cs to execute against it's queries using Dapper.  It has this concept of a sharedConnection.  I've had issues with this in multi threaded scenarios before and was hoping Dapper would help alleviate some of those issues as well as provide a kick in performance.

**Comment by mgravell** [comment]
Sql Server is slightly ambiguous because I can think of at least 3 ways to connect to Sql Server via ADO.NET;     is this SqlClient?

**Comment by mgravell** [comment]
But is it `SqlConnection`?

It is curious, because `SqlConnection`'s implementation is (via reflector):


    public SqlCommand CreateCommand() => new SqlCommand(null, this);

with the constructor being:

    
```
public SqlCommand(string cmdText, SqlConnection connection) : this() {
    this.CommandText = cmdText;
    this.Connection = connection;
}
```

So *in theory*; the `.Connection` has *already been set!*. So; I'm curious, but *if this is `SqlConnection`*, I don't see how that can be possible!

**Comment by dallasbeek** [comment]
this one is on me,  I added mini profiler and extended DbConnection but apparently I wasn't setting the connection properly.

   public class RepositorySqlConnection : ProfiledDbConnection {
      public RepositorySqlConnection ( SqlConnection connection, MiniProfiler profiler )
          : base( connection, profiler ) {
         Connection = connection;
      }

      protected override DbCommand CreateDbCommand () {
         return new RepositorySqlCommand( new SqlCommand(), null, MiniProfiler.Current );
      }

      public SqlConnection Connection { get; set; }
   }

   public class RepositorySqlCommand : ProfiledDbCommand {
      public RepositorySqlCommand ( SqlCommand cmd, SqlConnection conn, MiniProfiler profiler )
          : base( cmd, conn, profiler ) {
         Command = cmd;
      }

      public SqlCommand Command { get; set; }
   }

SHOULD BE 
   public class RepositorySqlConnection : ProfiledDbConnection {
      public RepositorySqlConnection ( SqlConnection connection, MiniProfiler profiler )
          : base( connection, profiler ) {
         Connection = connection;
      }

      protected override DbCommand CreateDbCommand () {
         return new RepositorySqlCommand( new SqlCommand(), Connection, MiniProfiler.Current );
      }

      public SqlConnection Connection { get; set; }
   }

   public class RepositorySqlCommand : ProfiledDbCommand {
      public RepositorySqlCommand ( SqlCommand cmd, SqlConnection conn, MiniProfiler profiler )
          : base( cmd, conn, profiler ) {
         Connection = conn;
         Command = cmd;
      }

      public SqlCommand Command { get; set; }
   }

**Comment by mgravell** [comment]
I suspect I also wrote `ProfiledDbConnection`, so if I've made an error there - happy to "own" that!
