### ISSUE TITLE
InsertOrUpdate not return id

### ISSUE THREAD

**Issue by ignasivs** [StackExchange/Dapper#946]
When I use the InsertOrUpdate function of the Rainbow, it returns 1 when it inserts and 2 when it updates. How can I get the id of the object that has been updated or inserted?

I have the version of dapper 1.50.2 and of Rainbow.MySql 0.10.1

Thank you

**Comment by ignasivs** [comment]
The code is `var sesionId = newdb.Sesiones.InsertOrUpdate(sesion);`

**Comment by ignasivs** [comment]
@DominikHerold can help please?

**Comment by DominikHerold** [comment]
❎
Sorry I do not see any method `InsertOrUpdate`

**Comment by ignasivs** [comment]
@DominikHerold What it's wrong in the code?

`public static Tuple<int, int> AddOrUpdateSesionCarrera(sesiones sesion, out Pk15Error pk15error)
        {
            pk15error = new Pk15Error();
            try
            {
                using (var transaction = new TransactionScope())
                {
                    // Operaciones sobre la base de datos.
                    Db newdb = Pixelcomk15_OpenConnection.db;
                    OpenConnectionInstance connect = null;
                    if (!string.IsNullOrEmpty(Pixelcomk15_OpenConnection.CadenaConexion))
                    {
                        connect = new OpenConnectionInstance(Pixelcomk15_OpenConnection.CadenaConexion);
                        newdb = connect.db;
                    }

                    if (sesion.carrera != null)  
                    {
                        var sesionId = newdb.Sesiones.InsertOrUpdate(sesion); //TODO InsertOrUpdate not return id.
                        sesion.carrera.idSesion = (int)sesionId;
                        var carreraId = newdb.Carrera.InsertOrUpdate(sesion.carrera);
                        connect?.Dispose();
                        /* Devolvemos el id de la sesion */
                        return new Tuple<int, int>((int)sesionId, (int)carreraId);
                    }

                    // Aceptamos la transacción.
                    transaction.Complete();
                }
            }
            catch (OpenConexionDbException e)
            {
                pk15error.exception = e;
                pk15error.errorType = EnumeradosPixelComk15.TDapperError.DatabaseConnection;
                return null;
            }
            catch (Exception e)
            {
                pk15error.exception = e;
                pk15error.errorType = EnumeradosPixelComk15.TDapperError.DatabaseQuery;
                error.EscribeErrorBD("Error AddSesionCarrera: " + e.Message);
                throw new Exception("Error AddSesionCarrera: " + e.Message);
            }
            return null;
        }`

**Comment by mrgchr** [comment]
I think that `InsertOrUpdate(sesiones sesion)` method in your code is written by someone else, not by Dapper.Rainbow project.
I guess you are asking in wrong place.

**Comment by ignasivs** [comment]
Thanks for response but I think the method from Rainbow library. You can see it in this link
https://drive.google.com/file/d/11ZOD1xaR0olPEPG0FSrnXNqGr8yvsveJ/view?usp=sharing
@DominikHerold  @mrgchr

**Comment by mrgchr** [comment]
OK.

I guess you are using 'Dapper.Rainbow.MySql' pacage.(Not 'Dapper.Rainbow')
https://github.com/antonheryanto/dapper-rainbow-mysql

And I found `InsertOrUpdate` method in the repository.

https://github.com/antonheryanto/dapper-rainbow-mysql/blob/f2b1a6cd226e4032d6afcbfc9f0b019a17b53ea6/Dapper.Rainbow.MySql/Table.cs#L114

**Comment by ignasivs** [comment]
Thank you so much for your help! I thought that i was asking in the right place :(

**Comment by mrgchr** [comment]
No problem amigo. I hope you achieve your goal.

**Comment by NickCraver** [comment]
Closing out to cleanup - looks like the right place to ask was found :)
