### ISSUE TITLE
Add IsExists method to Dapper.Contrib

### ISSUE THREAD

**Issue by Caltor** [StackExchange/Dapper#951]
Would the Developers give consideration to adding a ```bool IsExists(int id)``` method to Dapper.Contrib please? This would make life easier for us, so we don't have to write this method for each table/model. Alternatively if you could make the GetTable() method public then I could use this to write it myself.

Many thanks
Caltor

**Comment by kelvindules** [comment]
They probably won't because it doesn't add much.
--
Is this to avoid duplicate rows? If it is, id should have an unique constraint and then you would deal with the possible **unique key violation** exception on Insert.

**Comment by NickCraver** [comment]
I'm not sure what the use case is here - when would you want to check existence but not return the result? If it's for inserting then that's not awesome behavior as you'd want an identity or sequence in most databases and an API that goes against that isn't good for almost any users.

**Comment by Caltor** [comment]
I can't remember why I wanted this now. I'll close it off.
