### ISSUE TITLE
Option to set the default ISqlAdapter

### ISSUE THREAD

**Issue by oferns** [StackExchange/Dapper#953]
If I want to use something like MiniProfiler with MySQL and Dapper.Contrib then I need to wrap the MySQlConnection. This causes Dapper.Contrib to use the default (wrong) ISqlAdapter. Please either add an argument to the UpdateAsync & Update methods to accept an ISqlAdapter (like the insert does) or allow us to specify the default adapter

**Comment by NickCraver** [comment]
You can currently control the adapter like this:
```c#
SqlMapperExtensions.GetDatabaseType = conn => "MySqlConnection";
```

I agree this isn't awesome, and want to look at this harder with #722 and related issues in v2, but it does work in current code.
