### ISSUE TITLE
Get original SQL error message on client-side using Dapper?

### ISSUE THREAD

**Issue by arslanaybars** [StackExchange/Dapper#959]
Is it possible the get original SQL error message by using dapper?
I would like to tell my case with using an example.

For Example; Let's say we have store procure and the procedure contains this couple line of SQL code

```
BEGIN TRY  
    -- Generate a divide-by-zero error.  
    SELECT 1/0;  
END TRY  
BEGIN CATCH  
    throw
END CATCH;  
GO  
```
and of course if we execute this sp it returns divide by zero exception:

> Divide by zero error encountered

Is it possible to take SQL throwing message with Dapper? here is dapper request call

   ```
 var data = sqlConnection.QueryFirstOrDefault<response>(QueryConstants.SpXXX,
 parameters, null, Constants.DAPPER_TIMEOUT, CommandType.StoredProcedure);
```
I am using sql server 2017 and Dapper 1.50.4.0

that's the [stackoverflow ](https://stackoverflow.com/questions/49066853/how-to-get-original-sql-error-message-on-client-side-using-dapper)question by me

**Comment by NickCraver** [comment]
Folding this into #943 - same request :)
