### ISSUE TITLE
Query does not throw SQL Exception

### ISSUE THREAD

**Issue by hknga1** [StackExchange/Dapper#961]
I am not sure if this issue is related to the issue below:

QueryAsync no longer throws SQL Exception from 1.50.*
https://github.com/StackExchange/Dapper/issues/563

When I tried to run connection.Query with a store procedure. It does not throw SQL Exception.

**Comment by myname182** [comment]
I am having the same issue with QueryAsync (and Query) using version 1.6.0.

**Comment by myname182** [comment]
I just upgraded t 1.50.4 and it seems to work there. Thank you.

**Comment by hknga1** [comment]
Thanks. It works now

**Comment by NickCraver** [comment]
Closing out to cleanup, resolved in 1.50.4
