### ISSUE TITLE
Dapper 1.50.4 not supported on Visual Studio 2012

### ISSUE THREAD

**Issue by loudenvier** [StackExchange/Dapper#962]
I've just tried installing 1.50.4 in Visual Studio 2012 and it failed with the error:

```
Install-Package : 'Dapper' already has a dependency defined for 'System.Data.SqlClient'.
At line:1 char:1
+ Install-Package Dapper
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

```
I was able to install 1.50.2 with no issues whatsoever (other than using an outdated version).

**Comment by NickCraver** [comment]
This points to an outdated package manager - ensure your NuGet client for VS is up to date and then give it another go. There *shouldn't* be anything preventing installation here. But we also don't have VS 2012 to test with so...

**Comment by loudenvier** [comment]
The version of nuget installed in my Visual Studio 2012 is 2.8.60318.667 . I believe this is the latest version available. I had other packages which didn't install due to the same error, and the developers told me they wouldn't be supporting Visual Studio 2012. I don't know exactly what causes it, but I believe that Dapper could try to keep support for older versions of Visual Studio, since people living in Third World Countries like Brazil  (where I am right now :-) ) may not have the funds to upgrade their Visual Studio 2012 Ultimate License (here Windows 10 costs a hefty U$ 300 (U$ 100 more than in the US) and we get paid a LOT less...

But I don't even know if it will be possible to keep compatibility with older Nuget Package Managers...

**Comment by NickCraver** [comment]
@loudenvier unfortunately this isn't something we can change - it's a NuGet issue that happens with newer SqlClient packages (and we have to depend on those packages or everyone else gets *other* SNI DLL errors). It's simply not possible to not-break users on any version of VS while supporting VS 2012. It's a crap situation and for that I'm sorry, but I don't think we have any decent options here.

**Comment by charlesroddie** [comment]
VS2017 community is a pretty decent option.
