### ISSUE TITLE
does Dapper Support SqlBulkCopy And an idea for StoredProcedure Call  ?

### ISSUE THREAD

**Issue by sgf** [StackExchange/Dapper#966]
does Dapper Support SqlBulkCopy ?

**Comment by mgravell** [comment]
in what capacity? what would you have Dapper do here, that can't already be done with `SqlBulkCopy` directly?

**Comment by sgf** [comment]
just more easyly like NPoco ?



And i have another idea for StoredProcedure Call Way.

How About design like this:

```
List<T> Fetch<T,TOut>(string sp_name,object inputParmaters,
ref TOut outputParmaters,out ReturnValue)

```
i think thats better like this:
```
var p = new DynamicParameters();
p.Add("@a", 11);
p.Add("@b", dbType: DbType.Int32, direction: ParameterDirection.Output);
p.Add("@c", dbType: DbType.Int32, direction: ParameterDirection.ReturnValue);
```

**Comment by sgf** [comment]
i have do it myself,so close this issue
