### ISSUE TITLE
Existing database

### ISSUE THREAD

**Issue by enemyofthedawn** [StackExchange/Dapper#968]
How can I use dapper with an existing database? A lot of tables, a lot of relations.

What's the recommended way ?

**Comment by mgravell** [comment]
Dapper is deliberately minimal; it doesn't attempt to be a full "does everything" tool like EF or LLBLGen Pro - and it doesn't include a schema export / code-generation tool. That said: we have historically made a lot of use of Dapper with our old L2S models, which means that you might have good success using [SqlMetal](https://docs.microsoft.com/en-us/dotnet/framework/tools/sqlmetal-exe-code-generation-tool) (the code-gen tool from L2S, shipped as part of the VS dev tools if you have the L2S package installed).

Personally, if I was starting from a blank code state (but existing databases), I'd be tempted to *throw together* a basic codegen tool (but this would be vendor/RDBMS specific) by querying the DB metadata tables (`sys.tables` and `sys.columns` on SQL Server, for example), just generating some basic POCOs. Beyond that: as I say: Dapper is a  minimal tool, so you'd need to handle queries etc as you need them.

If there is something more specific you are looking for, perhaps a good place to start would be: what do you *want* there to be?
