### ISSUE TITLE
why dapper get the wrong value for long type？

### ISSUE THREAD

**Issue by zredb** [StackExchange/Dapper#970]
![image](https://user-images.githubusercontent.com/8102504/37509149-225fde7e-2931-11e8-8344-0601ce12ffb9.png)
![image](https://user-images.githubusercontent.com/8102504/37509157-2d36ec52-2931-11e8-8b5b-e056bca9c842.png)

**Comment by mgravell** [comment]
How is ArrayTypeId defined (in both the C# and the DB), and what is the
RDBMS here? Dapper just assigns what it is given. This looks like an
overflow problem, hence why the definitions are relevant.

**Comment by zredb** [comment]
hi guy, 
       thank you for reply rapidly， in C# side ArrayTypeId and ID are both long type in base class, and database is Sqlite, and ArrayTypeId and ID are both bigint type,thank you!

**Comment by zredb** [comment]
The ID property is also different from the value in the database，but it seems not a overflow problem.

**Comment by mgravell** [comment]
> but it seems not a overflow problem.

It is definitely an overflow problem:

```
long l = 2405573754525900800L;
int i = (int)l; // -1618681856
```

What is the query here? Is it possible that your query also read some *smaller* values earlier on in the same query? The reason I ask is: sqlite has a very weak type model, which can really cause huge problems in some cases. Also, which exact ADO.NET provider are you using?

**Comment by zredb** [comment]
but most times it get the correct value 
![image](https://user-images.githubusercontent.com/8102504/37510244-782c282c-2935-11e8-9eb4-e791e14af167.png)

**Comment by mgravell** [comment]
> but most times it get the correct value

hence the questions I asked at the bottom of my previous reply; I'm trying to narrow down what happened; I have a hunch, but I'm trying to confirm it. What I **strongly suspect** has happened is that this is the "not the first" row, and that the first row in your query had a value in the int32 range. The weak type model of sqlite means that some providers will report query metadata based on the first row *only*, so if the first row has an int32-range value, it will claim that this column is an int32. Dapper will then generate code to handle the value as an int32. At some point in the query, the ado.net provider realises there are larger values, but it already promised an int32 value to the consumer, so things get very confused.

If we can confirm that this is indeed what happened, we might be able to find a way to make dapper compensate for sqlite's weak type model, but the first step is: confirming that this is what happened.

**Comment by zredb** [comment]
Hi mgravell, 
         The ID is generated by ID generation algorithm, and it always have 19 bits,so I think it impossibleto be taken for int32. 
         ADO.NET provider is:
![image](https://user-images.githubusercontent.com/8102504/37510975-ff29267a-2937-11e8-962a-d454d1dcd09a.png)

**Comment by zredb** [comment]
It is definitely an overflow problem:
![image](https://user-images.githubusercontent.com/8102504/37511110-9f62f63e-2938-11e8-9415-f96e37ac293f.png)
 but when it happened?

**Comment by mgravell** [comment]
> and it always have 19 bits,

and you're sure that's working? have you checked to see whether any of the values are between `-2147483648` and `2147483647` (inclusive)? I'm not saying that there *will be some*, but it is very much worth checking. Also; is it possible to share the SQL that is being executed here, so we can see if there's anything obvious there?

> but when it happened?

short answer - right now: *I don't know*. Happy to try and try to figure it out, but it is hard to do from just a few screenshots.

**Comment by zredb** [comment]
Hi, 
      Thank you for support until now, in the test table, now it only 19 records in it, and they all out of range -2147483648 to2147483647.
![image](https://user-images.githubusercontent.com/8102504/37512629-aa0171d8-293d-11e8-83ad-90213e13e39e.png)

      and the SQL is :
![image](https://user-images.githubusercontent.com/8102504/37512796-12c1657a-293e-11e8-86cb-cc4752ccfecc.png)
     I will provide more information if you need, thank you!

**Comment by zredb** [comment]
and the ParseArrangeArgument method code is as below:
private ArrangeArgument ParseArrangeArgument(SQLiteConnection cnn, IDataReader reader)
        {
            ArrangeArgument aa = null;

            var col = reader.GetOrdinal("TraceType");
            var type = (TraceType)reader.GetInt32(col);

            switch (type)
            {
                case TraceType.Fixed:
                    // reader.GetRowParser<FixedArrangeArgument>() is a delegate
                    aa = reader.GetRowParser<FixedArrangeArgument>()(reader);
                    break;

                case TraceType.Season:
                    aa = reader.GetRowParser<SeasonArrangeArgument>()(reader);

                    break;
             }
             return aa;
     }

**Comment by mgravell** [comment]
I'm not seeing anything obviously problematic, so right now: "I don't know"!  Very curious.

Could you kindly try:

    var atCol = reader.GetOrdinal("ArrayTypeID");
    var atType = reader.GetFieldType(atCol);

and see what `atType` is? is it `System.Int32`? `System.Int64`? something else?

**Comment by zredb** [comment]
![image](https://user-images.githubusercontent.com/8102504/37514077-e340bba8-2941-11e8-9433-ef22b6d62e00.png)
atType is System.Int32 not Int64 !!!

**Comment by mgravell** [comment]
Right; so that's the root of the problem - dapper is going to be asking the same question: "what type is this column?" - and if the sqlite data provider says "it's int32", then dapper's going to believe it.

As a follow-up, I wonder what happens if you do:

    var obj = reader[atCol];

(i.e. consume the value), then do both of:

    var atType = reader.GetFieldType(atCol); // is this now int64? or is it still int32?
    var actualType = obj.GetType(); // is this int32? or int64?


I would be *very* curious in ^^^ those two things

---

Fundamentally, I think there's two possible "fixes" here:

- have the sqlite provider not be stupid
- have dapper expect stupidity

Since I don't control the sqlite provider, I only really have control over the second one. It *does* involve me setting up sqlite locally, though, which is always fun...

**Comment by zredb** [comment]
Hi mgravell ,
      they both have Int32 types after consume the value.

**Comment by mgravell** [comment]
Then in that case: everything here is the sqlite provider; dapper doesn't create that reader - it just consumes it. If the provider isn't giving us back an int64, I don't see that there's anything I can do *at all*. The question then becomes: why has the sqlite provider given us the wrong data? on that: I don't know - I'm not a sqlite expert. At this point, however, I think it becomes a "sql provider" issue, not a dapper one.

**Comment by zredb** [comment]
thank you for support it and any other provider recommend to resolve this issue？

**Comment by mgravell** [comment]
You could try `Microsoft.Data.Sqlite`: https://www.nuget.org/packages/Microsoft.Data.Sqlite

This isn't a "recommendation" - I don't use sqlite so I can't advise "for" or "against" anything - simply: this seems an obvious thing to try.

**Comment by NickCraver** [comment]
From my experience: if you're using not-netstandard, you'll want the old provider, if you're on netstandard, use `Microsoft.Data.Sqlite`. The native DLL install via NuGet story is still very unintuitive and buggy IMO, but that's the split that works on the two sides. I've relayed this to the Microsoft team.

**Comment by NickCraver** [comment]
This is fixed in the `Microsoft.Data.Sqlite` provider package - anyone finding this, that's my recommendation to switch to as well at this point!

**Comment by rstarkov** [comment]
If you're using the `System.Data.SQLite` provider, make sure your column was created as `BIGINT` and not `INT` - I'm guessing this provider looks at the declared column type to decide how to return the data. This fixed the 32 bit truncation for me.
