### ISSUE TITLE
MatchNamesWithUnderscores for parameters

### ISSUE THREAD

**Issue by deerchao** [StackExchange/Dapper#973]
In such case:

	var companyId = 1;
	var items = await connection.QueryAsync<Record>(
		@"SELECT *
		FROM records
		WHERE company_id = @company_id",
		new { companyId })
		.ConfigureAwait(false);

It would be nice to be able to automatically map property `companyId` to the parameter `@company_id`.

**Comment by NickCraver** [comment]
Please see discussions (and add!) to this in #722. While we wouldn't allow this specifically, the plan is to allow either attributes or a function where you can allow this. The two-way binding on parameters is an interesting question indeed, I'd appreciate thoughts added there if you have time.

Closing this out to cleanup lots of issues today but I'd love it if you chimed in on #722 with thoughts and ideas.
