### ISSUE TITLE
Dynamic Parameters fails to bind repeating variables

### ISSUE THREAD

**Issue by cemremengu** [StackExchange/Dapper#974]
Say that I have query:

var myQuery = `SELECT * FROM A WHERE T_ID = :ID AND F_ID := ID`

Doing 

```
var parameters = new DynamicParameters();
parameters.AddDynamicParams(3);
await db.QueryAsync<dynamic>(myQuery, parameters);
```

I get

`ORA-01008: not all variables bound`

Is there any workaround for this? Or maybe there is another way?

**Comment by mgravell** [comment]
I would expect AddDynamicParameters(3) to fail in all scenarios.

This may be an X/Y problem. What are you trying to do here?

You may wish to try:

    Add("ID", 3)

Or simpler, just pass

    new { ID = 3 }

as the args object. Can you perhaps clarify what you are attempting to do?
As I might be missing some context / nuance.

**Comment by cemremengu** [comment]
The problem is that I don't know the names of the args in advance.  I just receive a query and a bunch of parameters to use (I know it's not the best design ever).

In addition to not knowing the name, I also don't know if the count of an argument. For example arg `:ID` might appear twice in the query but I will just receive `3` as the argument to use.

**Comment by mgravell** [comment]
In that case it might not be a good fit for using dapper to invoke the
command, as dapper is very particular about wanting names (even in the
"pseudo-positional" scenario for down-level ado.net providers it still
wants a name for the upstream code).

But not all is lost! If you want to use dapper for the *consuming* part,
you can still get a row parser - not at a PC but something like
SqlMapper.GetRowReader (it might be GetRowParser). This gives you a
function that you can call per row on an IDataReader to have dapper do the
parsing, so you would create the command and add the unnamed args, then
call ExecuteDataReader, get the parser, then invoke the parser per row.
Would that help at all?

**Comment by cemremengu** [comment]
Thanks so much! After fiddling around a bit (and actually using your answer [here](https://stackoverflow.com/a/47099888/586986)). Here is what I got working:

```
// Add parameters 
var parameters = new List<string>();

var cmd = new OracleCommand("SELECT * FROM DUAL WHERE 1210 = :id", con);

for (int i = 0; i < parameters.Count; i++)
{
	cmd.Parameters.Add("p" + i, parameters[i]);
}

var reader = cmd.ExecuteReader();

// ^^ Upper section is from the native driver

var rowReader = SqlMapper.GetRowParser<dynamic>(reader);
while (reader.Read())
{
	var row = rowReader(reader);
}
``
