### ISSUE TITLE
Different column and table names mapping

### ISSUE THREAD

**Issue by enemyofthedawn** [StackExchange/Dapper#978]
In my database I have a lot of columns and tables with prefixes prefix_tableName. I'd like to map it to just a class named TableName, how can I do this? If I'm not wrong there are no attribute mappings in dapper like [Column("name")], [Table("name")]

**Comment by vdaron** [comment]
Have a look a project that are based on Dapper (Dapper.Contrib, SimpleStack,...)

**Comment by enemyofthedawn** [comment]
@vdaron I took a quick look but couldn't find solution to my problem, there was indeed Table attribute but it wouldn't allow me to specify column name.

**Comment by vdaron** [comment]
It is possible with SimpleStack.Orm (https://github.com/SimpleStack/simplestack.orm) with the "Alias" attribute.

As the principal maintainer of Simplestack, I'm probably biased  :-)

**Comment by sdanyliv** [comment]
@enemyofthedawn, you have to try [linq2db](https://github.com/linq2db/linq2db). During T4 model generation, you can do everything that you want with class names, property names or add additional members. [Here](https://github.com/linq2db/linq2db/tree/master/Source/LinqToDB.Templates#customizing-generation-process) small samples.

**Comment by enemyofthedawn** [comment]
@sdanyliv it seems like I found it before even seeing your reply 😃

**Comment by NickCraver** [comment]
Looks like the options are sorted here so closing out to cleanup - any further thoughts would definitely be appreciated in #722 as I hope we get to v2 of this in the coming months.
