### ISSUE TITLE
Can I do this?

### ISSUE THREAD

**Issue by guopenglun** [StackExchange/Dapper#979]
int myID=100;
string Sqlstr=$("Select * from TableA where ID={myID} ");
Execute .....

**Comment by mgravell** [comment]
It is very bad practice. That does literal replacement in .NET before it
touches ADO.NET, so it is the same as regular concatenation.

Problems:

- SQL injection; perhaps not a huge problem with an integer, but still to
be avoided
- culture; how do integers format in the culture of the running application?
- plan cache explosion; the server can't efficiently reuse a plan that has
different SQL per value

Always prefer parameters, so:

where ID=@id

With

new { id = myID }

(Names here chosen simply to show that the local and param names don't need
to be the same)

**Comment by guopenglun** [comment]
thanks for your reply .
Your opinion is useful.
I think I know what to do  : )
