### ISSUE TITLE
I cant open the project in vs2015?why?how?

### ISSUE THREAD

**Issue by zpzhangwenhan** [StackExchange/Dapper#983]

**Comment by mgravell** [comment]
Dapper multi-targets multiple target frameworks/standards. The most convenient way for us to do that is via the new CSP project system (i.e. the slimline .csproj format that followed the abortive project.json stuff). VS2015 does not support that, AFAIK.

Options:

- consume the .nupkg files from nuget
- edit the files any way you like; build at the command-line via `dotnet build`
- use VSCode
- use Visual Studio 2017 (the "Community" version is free, and should work fine)
- create your own local .csproj file in the format required by VS2015, and add the files you need

We (the primary maintainers) *don't tend to have VS2015 installed*, so maintaining a VS2015 project is burdensome with zero benefit for us.

**Comment by NickCraver** [comment]
Going to close this out, Marc covers it all above and there's just no way this is changing the way the VS team is splitting support these days.
