### ISSUE TITLE
No exception, but select count(1) returns empty resultset

### ISSUE THREAD

**Issue by kwaazaar** [StackExchange/Dapper#995]
I execute a query which returns a count, similar to "select count(1) from mytable". In my opinion this query should always return a resultset with one row OR throw an exception.

In my production logs I now see that under heavy load the QueryAsync sometimes returns an empty resultset (at the same time the log also shows connection errors/timeouts for other parallel requests).

I use this code:

protected virtual async Task<IEnumerable<T>> TranQueryAsync<T>(string query, object param)
{
    return await _conn.QueryAsync<T>(query, param, _runningTransaction, 30).ConfigureAwait(false);
}

My code calls First() on the resulting IEnumerable, but I get the exception that the sequence contains no elements. I think this is not ok and the QueryAsync should have thrown an exception.

**Comment by mgravell** [comment]
`QueryAsync` doesn't *know* how many rows there are going to be, so it can't raise *more* of an exception - it really comes down to : did the underlying ADO.NET provider throw an exception? What *is* the underlying ADO.NET provider in this case, out of curiosity?

But: if the ADO.NET provider fails to report an error, there isn't much dapper can do.

Note: if you used `QueryFirstAsync` or `QuerySingleAsync`, then it *would* have thrown if it detected zero rows.

**Comment by NickCraver** [comment]
Closing out due to inactivity and answered above.

**Comment by VickyLund** [comment]
@kwaazaar - Did you ever find the root problem? 
We are also facing a similar issue but we are not able to find the root cause.
