### ISSUE TITLE
Dapper and refcursor

### ISSUE THREAD

**Issue by gmocontreras-dev** [StackExchange/Dapper#996]
Dear Friends,
how can I implement the execution of a query within an oracle package using RefCursor. 
I can not generate the example by the data type.
```
using (var connection = new OracleConnection(_connectionString))
            {
                connection.Open();
                var parameter = new DynamicParameters();
                parameter.Add("outp ", dbType: OracleDbType.RefCursor, direction: ParameterDirection.Output);
                resultado = connection.Query<Usuario>("PKG_.Get", parameter, commandType: CommandType.StoredProcedure).ToList();
                if (resultado == null) resultado = new List<Usuario>();
            }
```
I have problem with OracleDbType.RefCursor.
Thanks for your help.

**Comment by mgravell** [comment]
I can only speak for myself, but quite simply: "I don't know". I don't tend to use Oracle very often, and this isn't a feature I have needed. It might be that someone in the usual suspects is more familiar, but if not: this would be a scenario where I would ideally look to the community - and in particular those affected by the gap - to contribute. Which could mean a PR, or could just mean a more thorough discussion of the scenario and how you might implement it today with raw ADO.NET.

Of course, it could also be that this feature is already exposed somehow that I am ignorant of;

**Comment by dipdapdop** [comment]
You could try doing something like this to call a refcursor-returning Package Stored Function:

```
            var parms = new OracleDynamicParameters();
            using (var connection = new OracleConnection(validOraConnectionString))
            {
                parms.Add(":rc", dbType: OracleDbType.RefCursor, direction: ParameterDirection.ReturnValue);
                parms.Add(":in_code", "GBP", OracleDbType.Varchar2, ParameterDirection.Input);
                var result = connection.Query<dynamic>(
                    "begin :rc := PKG.GET_CURRENCIES(in_code => :in_code); END;",
                    parms,
                    commandType: CommandType.Text
                );
            }
```

You can also use the `Execute` Dapper extension method on the connection and use `parms.Get` to de-reference the ref cursor. 

For the `OracleDynamicParameters` class, you can try using:

https://gist.github.com/vijaysg/3096151

OR

https://github.com/DIPSASA/Dapper.Oracle/blob/master/src/Dapper.Oracle/OracleDynamicParameters.cs (This is a fork of https://gist.github.com/vijaysg/3096151).

Hope this is helpful to you.

**Comment by wast** [comment]
https://github.com/DIPSASA/Dapper.Oracle is handling this very well. Close issue?
