### ISSUE TITLE
Query and QueryMultiple throws null reference when results empty

### ISSUE THREAD

**Issue by rm2k** [StackExchange/Dapper#997]
`Query` and `QueryMultiple` throws null reference exception when my table doesn't have any records. When I have some records everything works as expected. 

Is that the correct behaviour. I was expecting an empty collection or at the least a `null`. 

    using (var conn = _provider.Connect())
    {
      var sql = @"select min(ColmnN) as small from [TableN]";
      var small = conn.Query<T>(sql); // <--- Throws Null Reference Exception --->
    }

    using (var conn = _provider.Connect())
    {
      var sql =
      @"
      select min(ColmnN) as small from [TableN]
      select max(ColmnN) as huge from [TableN]";

      using (var bounds = await conn.QueryMultipleAsync(sql))
      {
         var small = bounds.Read<T>(); // <--- throws Null Reference Exception   --->    
      }
    }

**Comment by SelvinPL** [comment]
It's not a bug ... you just don't know C# basics ...
https://ideone.com/AJHEqL

**Comment by rm2k** [comment]
@SelvinPL MIN/MAX for empty set throws InvalidOperationException. refresh your C# basics.

**Comment by SelvinPL** [comment]
:) well what MIN/MAX has common with C# if you are using it in SQL?

**Comment by rm2k** [comment]
now you jumping from c# basics to SQL?

**Comment by SelvinPL** [comment]
Dapper is a simple [object mapper](https://en.wikipedia.org/wiki/Object-relational_mapping) for .Net ... so we are talking about both SQL and C# ... so : **MIN/MAX for empty set will return NULL obviously** _casting null to non nullable type wilt throw NRE_ bold par means SQL , italic - C#

**Comment by NickCraver** [comment]
@SelvinPL it's not even apparent from the example what is happening, but your attitude is very unwelcome. Please do not behave like that here again.

@rm2k What is your `T` here? `int`? If so, you'll need to use a `int?` instead, so that a null result is properly handled. If not, can you provide more detail on what `T` is here?

**Comment by rm2k** [comment]
Thanks @SelvinPL But nothing is not a real issue especially when you don't even bother to get the full problem details.

**Comment by NickCraver** [comment]
I have removed the noise here. @rm2k When you do the read, indeed use `.ReadAsync<DateTime?>` instead, it's trying to cast the `null` to `DateTime` (invalid) otherwise, does that make sense? Whatever that `T` is, Dapper is trying to deserialize to.

**Comment by rm2k** [comment]
yeah @NickCraver that makes sense. Thanks again for chipping in. I'm closing the issue in the meantime.
